//! Project the ONE command registry from `hide-protocol` into the artifacts the
//! frontend consumes: the serialized catalog (`command_catalog.json`) and the
//! TypeScript that exposes the `CommandSpec` type plus the catalog array
//! (`commands.d.ts`).
//!
//! Same guarantee as the protocol codegen (Bible sec 15.7): the FE does not
//! hand-declare the command table. It comes from `hide_protocol::command_catalog`
//! through this deterministic emitter, so a catalog change flows into the golden
//! and fails the build until the FE artifact is regenerated.
//!
//! Model-free: pure deterministic codegen over a static table.

use hide_protocol::{command_catalog, CommandSpec};

/// The serialized command catalog, pretty-printed and newline-terminated. This
/// is the exact `goldens/command_catalog.json` artifact.
pub fn command_catalog_json() -> String {
    let mut s = serde_json::to_string_pretty(&command_catalog())
        .expect("the command catalog is plain data and always serializes");
    s.push('\n');
    s
}

/// The command TypeScript: the `CommandSpec` interface (and every enum it
/// references) generated from the schemars schema, followed by the catalog as a
/// typed const. This is the exact `goldens/commands.d.ts` artifact.
pub fn command_typescript() -> String {
    let (_roots, defs) = crate::schema::collect_root::<CommandSpec>();

    let mut out = String::new();
    out.push_str("// Generated by hide-sdk from the hide-protocol command registry. DO NOT EDIT BY HAND.\n");
    out.push_str("// The ONE command table: hide-protocol owns CommandSpec + command_catalog().\n");
    out.push_str("// Regenerate with `cargo run -p hide-sdk --bin hide-sdk-codegen`.\n");
    out.push_str("// A drift from the Rust catalog is caught by the golden-file test.\n\n");

    out.push_str(&crate::ts::emit_definitions(&defs));

    // The catalog itself, as a typed const. JSON is a valid TS expression, and
    // every enum value serializes to the same snake_case string literal the
    // generated union types above accept, so this type-checks against them.
    out.push_str("export const COMMAND_CATALOG: CommandSpec[] = ");
    let data = serde_json::to_string_pretty(&command_catalog())
        .expect("the command catalog is plain data and always serializes");
    out.push_str(&data);
    out.push_str(";\n");
    out
}
