//! Deterministic JSON-Schema-to-TypeScript emitter.
//!
//! This is the "no handwritten frontend mirror types" guarantee (Bible sec
//! 15.7): the frontend's protocol types are generated here, from the same
//! schemars schemas [`crate::schema`] exports, so they cannot drift from the
//! Rust wire types. A protocol change reshapes this output, and the golden-file
//! test then fails until the frontend types are regenerated.
//!
//! # Covered subset
//!
//! The emitter maps the JSON Schema shapes hide-protocol actually produces:
//!
//! - objects (`type: "object"` with `properties`) -> `export interface`, with a
//!   field made optional (`?`) when it is absent from `required`;
//! - string enums (`type: "string"` with `enum`) -> `export type` string-literal
//!   unions (a single-value enum becomes one string literal, which is how the
//!   `kind` / `method` discriminants render);
//! - tagged unions (`oneOf` / `anyOf`) -> `export type` unions, including the
//!   `Option<Ref>` shape `anyOf: [Ref, null]` -> `Ref | null`;
//! - nullable primitives (`type: ["string", "null"]`) -> `string | null`;
//! - arrays (`type: "array"`) -> `T[]` (unions parenthesized: `(A | B)[]`);
//! - `$ref` -> the referenced type name;
//! - maps (`type: "object"` with `additionalProperties`) -> `Record<string, V>`;
//! - the permissive schemas `true` / `{}` (schemars' rendering of
//!   `serde_json::Value`) -> `unknown`.
//!
//! Anything outside that subset falls back to `unknown` rather than emitting a
//! wrong type. hide-protocol stays inside the subset today; a future shape that
//! needs more (for example numeric enums or `allOf` intersections) would show up
//! as `unknown` in the golden and is the documented deferred remainder.
//!
//! # No dashes by construction
//!
//! Descriptions carried from Rust doc comments are normalized to ASCII hyphens
//! ([`normalize`]) before they enter a JSDoc block, so the generated `.ts`
//! stays free of en/em dashes regardless of upstream punctuation.

use serde_json::{Map, Value};

use crate::schema::collect_definitions;

/// Emit the full protocol TypeScript declarations as a stable string. This is
/// the exact artifact the golden-file test pins and the frontend consumes.
pub fn protocol_typescript() -> String {
    let (roots, defs) = collect_definitions();
    emit(&roots, &defs)
}

/// Emit `export` declarations for a set of schemars definitions, without the
/// protocol file header. Used by codegen surfaces that supply their own header
/// and then append their own data (the command catalog appends its const array).
pub fn emit_definitions(defs: &Map<String, Value>) -> String {
    let mut out = String::new();
    for (name, schema) in defs.iter() {
        emit_declaration(name, schema, &mut out);
    }
    out
}

fn emit(roots: &[String], defs: &Map<String, Value>) -> String {
    let mut out = String::new();
    out.push_str("// Generated by hide-sdk from hide-protocol. DO NOT EDIT BY HAND.\n");
    out.push_str("// Bible sec 15.7: one schema source generates the frontend types.\n");
    out.push_str("// Regenerate with `cargo run -p hide-sdk --bin hide-sdk-codegen`.\n");
    out.push_str("// A drift from the Rust wire types is caught by the golden-file test.\n");
    out.push_str("// Protocol version: hide.agent.v1\n");
    out.push_str(&format!("// Root types: {}\n\n", roots.join(", ")));

    // defs is a serde_json object (BTreeMap-backed, no preserve_order), so this
    // iteration is alphabetical and deterministic.
    for (name, schema) in defs.iter() {
        emit_declaration(name, schema, &mut out);
    }
    out
}

fn emit_declaration(name: &str, schema: &Value, out: &mut String) {
    if let Some(desc) = schema.get("description").and_then(Value::as_str) {
        push_doc(out, desc, "");
    }

    // String enum -> string-literal union alias.
    if let Some(en) = schema.get("enum").and_then(Value::as_array) {
        out.push_str(&format!("export type {name} = {};\n\n", union(literals(en))));
        return;
    }

    // Tagged union -> union alias.
    if let Some(variants) = one_of(schema) {
        let parts = variants.iter().map(ts_type).collect::<Vec<_>>();
        out.push_str(&format!("export type {name} = {};\n\n", union(parts)));
        return;
    }

    if schema.get("type").and_then(Value::as_str) == Some("object") {
        if let Some(props) = schema.get("properties").and_then(Value::as_object) {
            let required = required_set(schema);
            out.push_str(&format!("export interface {name} {{\n"));
            for (field, field_schema) in props.iter() {
                if let Some(desc) = field_schema.get("description").and_then(Value::as_str) {
                    push_doc(out, desc, "  ");
                }
                let opt = if required.contains(field.as_str()) { "" } else { "?" };
                out.push_str(&format!(
                    "  {}{}: {};\n",
                    ident(field),
                    opt,
                    ts_type(field_schema)
                ));
            }
            out.push_str("}\n\n");
            return;
        }
        // A map (additionalProperties) with no fixed properties.
        out.push_str(&format!("export type {name} = {};\n\n", ts_type(schema)));
        return;
    }

    // Anything else: a plain alias to the mapped type.
    out.push_str(&format!("export type {name} = {};\n\n", ts_type(schema)));
}

/// Map one schema node to a TypeScript type expression.
fn ts_type(schema: &Value) -> String {
    let map = match schema {
        // schemars renders `serde_json::Value` as the permissive boolean schema
        // `true`; `false` is the empty/never schema. Both become `unknown`.
        Value::Bool(_) => return "unknown".to_string(),
        Value::Object(map) => map,
        _ => return "unknown".to_string(),
    };

    if let Some(reference) = map.get("$ref").and_then(Value::as_str) {
        return ref_name(reference);
    }
    if let Some(en) = map.get("enum").and_then(Value::as_array) {
        return union(literals(en));
    }
    if let Some(variants) = one_of(schema) {
        let parts = variants.iter().map(ts_type).collect::<Vec<_>>();
        return union(parts);
    }

    match map.get("type") {
        Some(Value::String(t)) => ts_primitive(t, map),
        Some(Value::Array(types)) => {
            let parts = types
                .iter()
                .map(|t| ts_primitive(t.as_str().unwrap_or("unknown"), map))
                .collect::<Vec<_>>();
            union(parts)
        }
        _ => "unknown".to_string(),
    }
}

fn ts_primitive(t: &str, map: &Map<String, Value>) -> String {
    match t {
        "string" => "string".to_string(),
        "integer" | "number" => "number".to_string(),
        "boolean" => "boolean".to_string(),
        "null" => "null".to_string(),
        "array" => {
            let inner = map
                .get("items")
                .map(ts_type)
                .unwrap_or_else(|| "unknown".to_string());
            format!("{}[]", parenthesize(&inner))
        }
        "object" => {
            if let Some(props) = map.get("properties").and_then(Value::as_object) {
                inline_object(props, map)
            } else {
                match map.get("additionalProperties") {
                    Some(Value::Object(_)) => {
                        let value = ts_type(map.get("additionalProperties").unwrap());
                        format!("Record<string, {value}>")
                    }
                    Some(Value::Bool(false)) => "Record<string, never>".to_string(),
                    _ => "Record<string, unknown>".to_string(),
                }
            }
        }
        _ => "unknown".to_string(),
    }
}

/// An inline object literal type, used by `oneOf` variants (Item, Notification)
/// and inline `params` objects.
fn inline_object(props: &Map<String, Value>, schema: &Map<String, Value>) -> String {
    let required = required_set(&Value::Object(schema.clone()));
    let mut s = String::from("{ ");
    for (field, field_schema) in props.iter() {
        let opt = if required.contains(field.as_str()) { "" } else { "?" };
        s.push_str(&format!("{}{}: {}; ", ident(field), opt, ts_type(field_schema)));
    }
    s.push('}');
    s
}

// -- helpers ---------------------------------------------------------------

fn one_of(schema: &Value) -> Option<&Vec<Value>> {
    schema
        .get("oneOf")
        .or_else(|| schema.get("anyOf"))
        .and_then(Value::as_array)
}

fn literals(values: &[Value]) -> Vec<String> {
    values
        .iter()
        .map(|v| match v {
            Value::String(s) => format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\"")),
            other => other.to_string(),
        })
        .collect()
}

fn union(parts: Vec<String>) -> String {
    if parts.is_empty() {
        return "never".to_string();
    }
    parts.join(" | ")
}

/// Wrap a union in parentheses so `A | B` arrays render as `(A | B)[]`.
fn parenthesize(ty: &str) -> String {
    if ty.contains(" | ") {
        format!("({ty})")
    } else {
        ty.to_string()
    }
}

fn required_set(schema: &Value) -> std::collections::BTreeSet<String> {
    schema
        .get("required")
        .and_then(Value::as_array)
        .map(|a| {
            a.iter()
                .filter_map(Value::as_str)
                .map(str::to_string)
                .collect()
        })
        .unwrap_or_default()
}

fn ref_name(reference: &str) -> String {
    reference
        .rsplit('/')
        .next()
        .unwrap_or(reference)
        .to_string()
}

/// A field name is used bare when it is a valid TS identifier, else quoted.
fn ident(field: &str) -> String {
    let valid = !field.is_empty()
        && field.chars().enumerate().all(|(i, c)| {
            c == '_' || c == '$' || c.is_ascii_alphabetic() || (i > 0 && c.is_ascii_digit())
        });
    if valid {
        field.to_string()
    } else {
        format!("\"{}\"", field.replace('"', "\\\""))
    }
}

/// Emit a JSDoc block at the given indent, one line per source line, with
/// dashes normalized so the output is ASCII-clean.
fn push_doc(out: &mut String, desc: &str, indent: &str) {
    out.push_str(&format!("{indent}/**\n"));
    for line in normalize(desc).split('\n') {
        let line = line.replace("*/", "* /");
        out.push_str(&format!("{indent} * {line}\n"));
    }
    out.push_str(&format!("{indent} */\n"));
}

/// Replace en dash (U+2013) and em dash (U+2014) with a plain hyphen so no
/// generated text can carry a non-hyphen dash. Idempotent on ASCII input.
pub fn normalize(text: &str) -> String {
    text.replace('\u{2013}', "-").replace('\u{2014}', "-")
}
