//! Property-based parity gate for Event Horizon (EH).
//!
//! ## THE GATE
//!
//! For N=20 pseudo-random prompts across three length buckets, greedy output
//! must be byte-identical with HAWKING_QWEN_EVENT_HORIZON unset vs =1.
//! This generalises the single canned-prompt case in user_draft_parity_e2e.rs
//! to a property: losslessness must hold across diverse character types and
//! prompt lengths, not just repetitive Rust boilerplate.
//!
//! ## Determinism
//!
//! Prompts are generated from a seeded LCG (no external rand dep). The seed is
//! fixed so failures are reproducible: the same 20 prompts in the same order on
//! every run. The max_new_tokens cap is also fixed (GPU-CAP: 16 while KD owns
//! the GPU — un-cap to test longer windows).
//!
//! ## What is exercised
//!
//! - EH codepath in qwen_dense.rs ('ud_loop EH-ON branch, Verifier::verify_line,
//!   ProposalRouter::plan/record) across 20 diverse prompts.
//! - Short/medium/longer prompt buckets: code-y chars, mixed ASCII, prose-y runs.
//! - Both CPU fp16 fallback verify and (implicitly) the EH routing layer.
//!
//! Neural proposers are NOT enabled (kill-ledger rule). EH is exercised through
//! the UserNgram + SuffixArray free slots only.

#![cfg(target_os = "macos")]

use std::path::PathBuf;
use std::sync::{Mutex, OnceLock};

const WEIGHTS: &str = "../../models/qwen2.5-3b-instruct-q4_k_m.gguf";

// GPU-CAP: max_new_tokens=16 while KD job owns GPU; un-cap for full run.
// The logical test design uses {16,64,256} but all are capped here.
const MAX_NEW_TOKENS_CAP: usize = 16;

/// Number of pseudo-random prompts to generate and test.
const N_PROMPTS: usize = 20;

static SERIAL_GATE: OnceLock<Mutex<()>> = OnceLock::new();

// ── LCG parameters (Knuth MMIX) ───────────────────────────────────────────

const LCG_MUL: u64 = 6364136223846793005;
const LCG_ADD: u64 = 1442695040888963407;
const SEED: u64 = 0xdeadbeef_cafebabe_u64;

/// Advance a single LCG step and return the new state.
#[inline]
fn lcg_step(state: u64) -> u64 {
    state.wrapping_mul(LCG_MUL).wrapping_add(LCG_ADD)
}

// ── Prompt generation ─────────────────────────────────────────────────────

/// Character sets used to build prompts that resemble different domains.
/// Each variant is a slice of printable ASCII ranges mapped from a [0,1) u64.
mod charsets {
    /// Code-y: identifiers, operators, punctuation (favours [a-zA-Z0-9_:;<=>{}()])
    pub fn code_char(state: u64) -> u8 {
        const CODE: &[u8] = b"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ\
                               0123456789_:;=<>{}()[].,!+-*/&|^~# \n";
        CODE[((state >> 33) as usize) % CODE.len()]
    }

    /// Mixed ASCII: all printable characters (broader distribution).
    pub fn mixed_char(state: u64) -> u8 {
        0x20 + ((state >> 33) as u8 % 95)
    }

    /// Prose-y: biased toward lowercase letters, spaces, and punctuation.
    pub fn prose_char(state: u64) -> u8 {
        const PROSE: &[u8] = b"abcdefghijklmnopqrstuvwxyz      ,. !?abcdefghijklmnopqrstuvwxyz";
        PROSE[((state >> 33) as usize) % PROSE.len()]
    }
}

/// Generate `n` pseudo-random prompts from a deterministic seeded LCG.
///
/// Prompts 0..6   → code-y characters,  target max_new_tokens=16  (short)
/// Prompts 7..13  → mixed ASCII,         target max_new_tokens=64  (medium)
/// Prompts 14..19 → prose-y characters,  target max_new_tokens=256 (longer)
///
/// ALL max_new_tokens values are overridden to MAX_NEW_TOKENS_CAP=16 by the
/// caller to keep GPU smoke tiny while the KD job runs.
fn pseudo_rand_prompts(n: usize, seed: u64) -> Vec<String> {
    let mut state = seed;
    let mut prompts = Vec::with_capacity(n);

    for i in 0..n {
        // Prompt length: vary between ~40 and ~160 chars so the context
        // entering the forward pass differs non-trivially across cases.
        let base_len: usize = 40 + (i * 7 % 120); // 40..160

        let char_fn: fn(u64) -> u8 = if i < 7 {
            charsets::code_char
        } else if i < 14 {
            charsets::mixed_char
        } else {
            charsets::prose_char
        };

        let mut buf = Vec::with_capacity(base_len);
        for _ in 0..base_len {
            state = lcg_step(state);
            let ch = char_fn(state);
            // Ensure the generated byte is valid UTF-8 (printable ASCII always is).
            buf.push(ch);
        }

        // Safety: every byte is in 0x20..=0x7e (printable ASCII), so this is
        // always valid UTF-8.
        let s = String::from_utf8(buf)
            .expect("LCG generated non-UTF8 byte — invariant broken");
        prompts.push(s);
    }

    prompts
}

// ── Engine helpers ────────────────────────────────────────────────────────

fn weights_path() -> Option<PathBuf> {
    let p = PathBuf::from(WEIGHTS);
    if p.exists() {
        Some(p)
    } else {
        eprintln!("event_horizon_parity_prop: skipping — no weights at {WEIGHTS}");
        None
    }
}

fn make_engine(weights: &PathBuf) -> Box<dyn hawking_core::Engine> {
    // Mirror the env setup from user_draft_parity_e2e.rs exactly.
    // TCB=1: production Metal greedy path (required by the EH loop).
    std::env::set_var("HAWKING_QWEN_TCB", "1");
    // Disable prefix cache so the only variable per prompt is the EH flag.
    std::env::set_var("HAWKING_QWEN_PREFIX_CACHE", "0");
    // USER_DRAFT=1: EH requires the user-draft path to be active.
    std::env::set_var("HAWKING_QWEN_USER_DRAFT", "1");
    // PAIR_2R_INLINE=0: E3 is NOT consistent with the batched verify path;
    // auto-disable here mirrors the production guard in qwen_dense.rs.
    std::env::set_var("HAWKING_QWEN_PAIR_2R_INLINE", "0");
    let cfg = hawking_core::EngineConfig::default();
    hawking_core::model::load_engine(weights, cfg).expect("load engine")
}

/// No-spec engine: USER_DRAFT=0 disables ALL speculative decode → plain canonical
/// greedy. This is the TRUE oracle: EH-ON and the legacy OFF spec path must each
/// equal this (EH-OFF is itself a spec path and was proven non-lossless, so it is
/// NOT a valid reference — see eh_verify_kernel_losslessness_2026_06_21.md).
fn make_engine_nospec(weights: &PathBuf) -> Box<dyn hawking_core::Engine> {
    std::env::set_var("HAWKING_QWEN_TCB", "1");
    std::env::set_var("HAWKING_QWEN_PREFIX_CACHE", "0");
    std::env::set_var("HAWKING_QWEN_USER_DRAFT", "0");
    std::env::set_var("HAWKING_QWEN_PAIR_2R_INLINE", "0");
    std::env::remove_var("HAWKING_QWEN_EVENT_HORIZON");
    let cfg = hawking_core::EngineConfig::default();
    hawking_core::model::load_engine(weights, cfg).expect("load engine")
}

/// Run greedy generation and return the emitted token-id vector.
/// Does NOT return draft_accepted count — the property gate is correctness only.
fn gen_on_n(
    engine: &mut dyn hawking_core::Engine,
    prompt: &str,
    max_new_tokens: usize,
) -> Vec<u32> {
    let req = hawking_core::GenerateRequest {
        prompt: prompt.into(),
        max_new_tokens,
        sampling: hawking_core::SamplingParams {
            temperature: 0.0,
            seed: Some(42),
            ..Default::default()
        },
        stop: vec![],
        abort: None,
        max_stall_ms: 0,
        json_mode: false,
    };
    let mut ids: Vec<u32> = Vec::new();
    engine
        .generate(req, &mut |ev| {
            if let hawking_core::StreamEvent::Token { id, .. } = ev {
                ids.push(id);
            }
        })
        .expect("generate");
    ids
}

// ── THE GATE ──────────────────────────────────────────────────────────────

/// Property-based parity gate: for each of the 20 pseudo-random prompts,
/// greedy output must be byte-identical EH-OFF vs EH-ON.
///
/// Failures print the prompt index, a truncated prompt snippet, and both
/// token vectors so failures are debuggable without re-running manually.
#[test]
fn event_horizon_parity_property() {
    let Some(weights) = weights_path() else {
        return;
    };
    let _g = SERIAL_GATE.get_or_init(|| Mutex::new(())).lock().unwrap();

    let prompts = pseudo_rand_prompts(N_PROMPTS, SEED);
    assert_eq!(prompts.len(), N_PROMPTS);

    let mut failures: Vec<(usize, String)> = Vec::new();
    let mut pass_count = 0usize;

    for (i, prompt) in prompts.iter().enumerate() {
        // GPU-CAP: max_new_tokens=16 while KD job owns GPU; un-cap for full run.
        // The logical bucket (16/64/256) is noted in comments but not used while capped.
        let _logical_max = if i < 7 { 16 } else if i < 14 { 64 } else { 256 };
        let max_new_tokens = MAX_NEW_TOKENS_CAP;

        // ── NO-SPEC canonical greedy (the oracle) ─────────────────────────
        std::env::remove_var("HAWKING_QWEN_EVENT_HORIZON");
        let ref_ids = {
            let mut e = make_engine_nospec(&weights);
            gen_on_n(e.as_mut(), prompt, max_new_tokens)
        };

        // ── EH ON (user-draft spec + Event Horizon market) ────────────────
        std::env::set_var("HAWKING_QWEN_EVENT_HORIZON", "1");
        let on_ids = {
            let mut e = make_engine(&weights);
            gen_on_n(e.as_mut(), prompt, max_new_tokens)
        };
        std::env::remove_var("HAWKING_QWEN_EVENT_HORIZON");

        // ── EH OFF (legacy user-draft spec path) ──────────────────────────
        let off_ids = {
            let mut e = make_engine(&weights);
            gen_on_n(e.as_mut(), prompt, max_new_tokens)
        };

        // ── Assert: BOTH spec paths must equal no-spec canonical greedy ───
        let on_ok = on_ids == ref_ids;
        let off_ok = off_ids == ref_ids;
        if on_ok && off_ok {
            pass_count += 1;
        } else {
            let snippet: String = prompt.chars().take(60).collect();
            let which = match (on_ok, off_ok) {
                (false, false) => "EH-ON and OFF(spec) BOTH",
                (false, true) => "EH-ON",
                (true, false) => "OFF(legacy spec)",
                _ => unreachable!(),
            };
            let msg = format!(
                "prompt[{i}] {which} != no-spec greedy (snippet: {snippet:?})\n  \
                 REF(greedy): {ref_ids:?}\n  \
                 EH-ON      : {on_ids:?}\n  \
                 OFF(spec)  : {off_ids:?}"
            );
            eprintln!("\nEH PARITY FAIL: {msg}");
            failures.push((i, msg));
        }
    }

    // Restore safe state.
    std::env::set_var("HAWKING_QWEN_USER_DRAFT", "0");

    eprintln!(
        "\nEH parity property: {pass_count}/{N_PROMPTS} prompts bit-identical to no-spec canonical greedy"
    );

    if !failures.is_empty() {
        let summary = failures
            .iter()
            .map(|(_, m)| m.as_str())
            .collect::<Vec<_>>()
            .join("\n\n");
        panic!(
            "EH PARITY PROPERTY FAILED: {}/{} prompts had mismatches:\n\n{}",
            failures.len(),
            N_PROMPTS,
            summary
        );
    }
}
