#!/usr/bin/env bash
# Capture Phase 1 baseline hashes — token output anchor + kernel
# numerical anchor. These are committed to the repo and used by
# regression tests on every haul to detect drift.
#
# Usage:
#   ./tools/haul/capture-baseline.sh phase1                # capture both
#   ./tools/haul/capture-baseline.sh phase1 --tokens-only  # token only (no model load alternative)
#   ./tools/haul/capture-baseline.sh phase1 --kernels-only # kernel parity only
#
# Output:
#   tests/golden/_phase1_token_baseline.hashes
#   tests/golden/_phase1_kernel_baseline.hashes
#
# Memory-aware: token capture requires loading the 9 GB model and
# running 3-token prefill+decode. Calls `coexist.sh probe` first. If
# memory pressure is critical, refuses to run the token capture.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
PHASE="${1:-phase1}"
MODE="${2:---both}"

COEXIST="$REPO_ROOT/tools/haul/coexist.sh"
DISMANTLE="$REPO_ROOT/target/release/dismantle"
MODEL="$REPO_ROOT/models/deepseek-v2-lite-q4.gguf"
TOKEN_HASHES="$REPO_ROOT/tests/golden/_${PHASE}_token_baseline.hashes"
KERNEL_HASHES="$REPO_ROOT/tests/golden/_${PHASE}_kernel_baseline.hashes"

log() { printf '[capture-baseline] %s\n' "$*"; }

# Pick a hash tool. blake3 (b3sum) was the documented choice for the
# baselines; sha256 is the fallback when b3sum isn't installed. The
# baseline file header records which one was used so the verifier knows
# how to recompute.
pick_hasher() {
    if command -v b3sum >/dev/null 2>&1; then
        HASH_ALGO="blake3"
        HASH_CMD=(b3sum --no-names)
    else
        HASH_ALGO="sha256"
        HASH_CMD=(shasum -a 256)
    fi
}

run_hash() {
    # Reads stdin, prints just the hex digest (no filename column).
    if [[ "$HASH_ALGO" == "blake3" ]]; then
        "${HASH_CMD[@]}"
    else
        "${HASH_CMD[@]}" | awk '{print $1}'
    fi
}

pick_hasher
log "hasher: $HASH_ALGO (${HASH_CMD[*]})"

# ---- 1. Kernel baseline (cheap; no model needed) -------------------

capture_kernels() {
    log "kernel parity baseline → $KERNEL_HASHES"
    log "(deferred to first haul — generated by tests/correctness/phase1_kernel_parity.rs)"

    # Until the parity test exists in source, write a header-only file
    # so downstream `verify-evidence` knows the anchor exists. The
    # first haul's G1.1 will overwrite this with real per-kernel
    # hashes when it lands.
    cat > "$KERNEL_HASHES" <<EOF
# Phase 1 kernel-parity baseline
# Format: <kernel-name> <input-shape> <hash-hex>
# algo: $HASH_ALGO
# Captured by tests/correctness/phase1_kernel_parity.rs
# Each row anchors one (kernel, fixed input) → (output bytes) hash.
# A regression here means the Metal port produced different bytes
# than the CPU reference for the same input.
#
# Initial state: empty. First haul (G1.1) populates rmsnorm row;
# subsequent gates extend with their kernels.
EOF
    log "kernel baseline header written ($(wc -l < "$KERNEL_HASHES") lines)"
}

# ---- 2. Token baseline (needs model + coexist probe) ---------------

capture_tokens() {
    [[ -x "$COEXIST" ]] || { log "missing $COEXIST"; return 1; }
    "$COEXIST" probe >/dev/null
    local g=$?
    if [[ $g -eq 2 ]]; then
        log "memory pressure CRITICAL — refusing token capture (it needs ~12 GB peak briefly)"
        log "leave token baseline empty for now; first haul re-captures when pressure drops"
        cat > "$TOKEN_HASHES" <<EOF
# Phase 1 token-output baseline
# Format: <prompt-id> <max-new-tokens> <hash-hex of streamed decoded text>
# algo: $HASH_ALGO
# Captured by tools/haul/capture-baseline.sh while running the model
# at temp=0 greedy. Acts as an end-to-end forward-pass regression anchor.
#
# Initial state: empty (memory pressure prevented capture).
# Re-capture: ./tools/haul/capture-baseline.sh phase1 --tokens-only
EOF
        return 0
    fi

    [[ -x "$DISMANTLE" ]] || { log "missing $DISMANTLE — run cargo build --release"; return 1; }
    [[ -f "$MODEL" ]]    || { log "missing $MODEL — run tools/fetch-model.sh"; return 1; }

    log "memory check passed; running 3-token greedy capture (this takes ~30 seconds at Phase-0 CPU speed)"

    # Three short prompts, each producing 3 deterministic greedy tokens.
    local prompts=(
        "p001:Once upon a time"
        "p002:def quicksort(arr):"
        "p003:The capital of France is"
    )

    cat > "$TOKEN_HASHES" <<EOF
# Phase 1 token-output baseline
# Captured at: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Format: <prompt-id> <max-new-tokens> <hash-hex of streamed decoded text>
# algo: $HASH_ALGO
# Generation: temp=0 greedy, max_new_tokens=3, model=DeepSeek-V2-Lite-Chat-Q4_K_M
EOF

    for entry in "${prompts[@]}"; do
        local pid="${entry%%:*}"
        local prompt="${entry#*:}"
        log "  capturing $pid: ${prompt:0:40}…"

        # Run dismantle, hash the full streamed decoded text. The old
        # `head -c 4096` cap was silent truncation: 3 greedy tokens at
        # most decode to ~30 bytes, so the cap never bit, but keeping
        # it would mask any future expansion of token count or a
        # surprise stderr-on-stdout merge. Removed; the prompt
        # signature is the safety check.
        local out
        out="$("$DISMANTLE" generate \
            --weights "$MODEL" \
            --prompt "$prompt" \
            --max-new-tokens 3 \
            --temperature 0 \
            --max-stall-ms 60000 \
            2>/dev/null)" || {
            log "  $pid: dismantle exited non-zero; baseline incomplete"
            continue
        }

        local out_len="${#out}"
        if [[ $out_len -lt 1 ]]; then
            log "  $pid: empty output; skipping (baseline incomplete)"
            continue
        fi

        local hash
        hash="$(printf '%s' "$out" | run_hash)"
        printf '%s 3 %s\n' "$pid" "$hash" >> "$TOKEN_HASHES"
        log "  $pid: $hash (${out_len} bytes)"
    done

    log "token baseline written ($(grep -cE '^p[0-9]' "$TOKEN_HASHES") rows)"
}

# ---- 3. Dispatch ----------------------------------------------------

case "$MODE" in
    --both) capture_kernels; capture_tokens ;;
    --tokens-only)  capture_tokens ;;
    --kernels-only) capture_kernels ;;
    *) log "unknown mode: $MODE"; exit 1 ;;
esac

log "done"
