#!/usr/bin/env python3.12
"""Staged, opt-in resource overlay for Doctor V5 Ultra.

This module is deliberately not imported by the live Ultra supervisor.  It
provides the next supervisor revision with a hash-bound pending-only overlay,
measured-RSS admission decisions, CPU-token accounting, and a read-only schedule
simulator.  ``stage`` writes only below ``staged_acceleration``; no command in
this file changes the campaign plan, queue state, runtime specs, evidence, or
results.

Activation is two-key and fail-closed: a future supervisor must receive both the
overlay path and its canonical SHA-256, revalidate the live plan, and observe a
quiescent paused/drained checkpoint before it may consume the policy.  Existing
complete/negative/unsupported cells remain immutable; the overlay affects only
the admission order of pending work.
"""
from __future__ import annotations

import argparse
import datetime as dt
import fcntl
import hashlib
import json
import math
import os
from pathlib import Path
import subprocess
import sys
import tempfile
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import doctor_v5_post_120b as post_120b
import ram_scheduler


ULTRA_ROOT = ROOT / "reports/condense/doctor_v5_ultra"
PLAN = ULTRA_ROOT / "campaign_plan.json"
CAMPAIGN = ULTRA_ROOT / "campaign.json"
QUEUE_STATE = ULTRA_ROOT / "queue_state.json"
QUEUE_LOCK = ULTRA_ROOT / "queue.lock"
CHILD_RESOURCES = ULTRA_ROOT / "child_resources.jsonl"
OBSERVER_STATE = ULTRA_ROOT / "post_120b/observer_state.json"
HEAVY_LOCK = ROOT / "reports/cron/studio_heavy.lock"
STAGE_ROOT = ULTRA_ROOT / "staged_acceleration"
DEFAULT_OVERLAY = STAGE_ROOT / "stacked_admission_overlay.json"

SCHEMA = "hawking.doctor_v5_stacked_admission_overlay.v1"
SIMULATION_SCHEMA = "hawking.doctor_v5_stacked_admission_simulation.v1"
OBSERVER_STATE_SCHEMA = "hawking.doctor_v5_post_120b_observer_state.v1"
VERSION = "2026-07-15.2"
TERMINAL = frozenset({"complete", "negative", "unsupported"})

PROCESS_BUDGET_BYTES = 78_000_000_000
CURRENT_MARGIN_BYTES = 28_000_000_000
DYNAMIC_BASE_MARGIN_BYTES = 12_000_000_000
MIN_DYNAMIC_MARGIN_BYTES = 12_000_000_000
MAX_LANES = 8
RESIDENCY_FLOOR_BYTES = 4_000_000_000
RESIDENCY_BASE_WORKING_BYTES = 9_000_000_000
RESIDENCY_DENSE_FACTOR = 2.0
RESIDENCY_SHARD_FACTOR = 2.0
SWAP_STALE_TOLERANCE_MB = 1.0
CPU_GUARD_CORES = 2.0
UNKNOWN_LARGE_TIER_THRESHOLD_B = 16.0

ENV_OVERLAY = "DOCTOR_V5_STACKED_ADMISSION_OVERLAY"
ENV_OVERLAY_SHA256 = "DOCTOR_V5_STACKED_ADMISSION_SHA256"


class OverlayError(RuntimeError):
    """The overlay cannot be trusted or safely consumed."""


def _now() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")


def _canonical(value: Any) -> bytes:
    return json.dumps(
        value, sort_keys=True, separators=(",", ":"), ensure_ascii=False,
        allow_nan=False,
    ).encode("utf-8")


def _hash_value(value: Any) -> str:
    return hashlib.sha256(_canonical(value)).hexdigest()


def _without(value: dict[str, Any], key: str) -> dict[str, Any]:
    return {name: child for name, child in value.items() if name != key}


def _read_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_bytes())
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise OverlayError(f"cannot read JSON {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise OverlayError(f"JSON root is not an object: {path}")
    return value


def _file_reference(path: Path) -> dict[str, Any]:
    try:
        raw = path.read_bytes()
    except OSError as exc:
        raise OverlayError(f"cannot bind source {path}: {exc}") from exc
    try:
        relative = str(path.resolve().relative_to(ROOT.resolve()))
    except ValueError:
        relative = str(path.resolve())
    return {"path": relative, "sha256": hashlib.sha256(raw).hexdigest(),
            "bytes": len(raw)}


def _reference_matches(reference: Any) -> bool:
    if not isinstance(reference, dict) or set(reference) != {"path", "sha256", "bytes"}:
        return False
    try:
        path = (ROOT / reference["path"]).resolve(strict=True)
        raw = path.read_bytes()
    except (OSError, TypeError, ValueError):
        return False
    return len(raw) == reference["bytes"] \
        and hashlib.sha256(raw).hexdigest() == reference["sha256"]


def _observer_structure_errors(path: Path | None = None) -> list[str]:
    """Validate the live observer as mutable, self-hashed telemetry.

    The observer is atomically regenerated by ``doctor_v5_post_120b sync`` and
    therefore must not be byte-pinned from overlay staging through activation.
    It still has to be a genuine, internally sealed observer state produced by
    the currently reviewed observer source, and its immutable latest snapshot
    must resolve below the observer snapshot directory.
    """
    path = path or OBSERVER_STATE
    errors: list[str] = []
    expected_keys = {
        "schema", "version", "updated_at", "observer_source_sha256",
        "observer_source_bytes", "latest_generation_id",
        "latest_observation_id", "latest_observation",
        "final_interpretation_ready", "final_interpretation_packet",
        "final_interpretation_handoff", "eta",
        "gpt_oss_120b_execution_ready",
        "gpt_oss_120b_currently_disk_admissible", "final_gate_blockers",
        "source_deletion_permitted", "state_sha256",
    }
    try:
        if path.is_symlink() or not path.is_file():
            return ["live observer state is absent or is not a regular file"]
        state = _read_json(path)
    except (OSError, OverlayError):
        return ["live observer state is unreadable"]
    if set(state) != expected_keys or state.get("schema") != OBSERVER_STATE_SCHEMA:
        errors.append("live observer keys/schema are invalid")
    if state.get("state_sha256") != _hash_value(_without(state, "state_sha256")):
        errors.append("live observer self-hash is invalid")
    if state.get("source_deletion_permitted") is not False:
        errors.append("live observer source-deletion boundary is invalid")
    try:
        source = Path(post_120b.__file__).resolve(strict=True)
        source_raw = source.read_bytes()
    except OSError:
        errors.append("reviewed observer source is unreadable")
    else:
        if state.get("observer_source_sha256") != hashlib.sha256(source_raw).hexdigest() \
                or state.get("observer_source_bytes") != len(source_raw) \
                or state.get("version") != post_120b.VERSION:
            errors.append("live observer is not bound to the reviewed observer source")
    for name in ("latest_generation_id", "latest_observation_id"):
        value = state.get(name)
        if not isinstance(value, str) or len(value) != 64 \
                or any(character not in "0123456789abcdef" for character in value):
            errors.append(f"live observer {name} is invalid")
    latest = state.get("latest_observation")
    if not isinstance(latest, dict) or set(latest) != {"path", "sha256", "bytes"}:
        errors.append("live observer latest snapshot reference is invalid")
    else:
        try:
            raw_path = path.parent / latest["path"]
            if raw_path.is_symlink():
                raise ValueError("snapshot symlink")
            snapshot = raw_path.resolve(strict=True)
            snapshot.relative_to((path.parent / "snapshots").resolve(strict=True))
            if not snapshot.is_file():
                raise ValueError("snapshot is not regular")
            raw = snapshot.read_bytes()
            if len(raw) != latest["bytes"] \
                    or hashlib.sha256(raw).hexdigest() != latest["sha256"]:
                raise ValueError("snapshot artifact differs")
            snapshot_doc = json.loads(raw)
            if not isinstance(snapshot_doc, dict) \
                    or snapshot_doc.get("schema") \
                    != "hawking.doctor_v5_post_120b_observation.v1" \
                    or snapshot_doc.get("packet_sha256") \
                    != _hash_value(_without(snapshot_doc, "packet_sha256")) \
                    or snapshot_doc.get("packet_sha256") \
                    != state.get("latest_observation_id") \
                    or snapshot_doc.get("generation_id") \
                    != state.get("latest_generation_id") \
                    or snapshot_doc.get("source_deletion_permitted") is not False:
                raise ValueError("snapshot semantic identity differs")
            final_gate = snapshot_doc.get("final_gate")
            gpt_oss = snapshot_doc.get("gpt_oss_120b")
            execution_readiness = gpt_oss.get("execution_readiness") \
                if isinstance(gpt_oss, dict) else None
            if state.get("eta") != snapshot_doc.get("eta") \
                    or not isinstance(final_gate, dict) \
                    or state.get("final_interpretation_ready") \
                    != final_gate.get("ready") \
                    or state.get("final_gate_blockers") \
                    != final_gate.get("blockers") \
                    or not isinstance(gpt_oss, dict) \
                    or state.get("gpt_oss_120b_execution_ready") \
                    != gpt_oss.get("execution_ready") \
                    or not isinstance(execution_readiness, dict) \
                    or state.get("gpt_oss_120b_currently_disk_admissible") \
                    != execution_readiness.get("currently_disk_admissible"):
                raise ValueError("snapshot readiness linkage differs")
        except (json.JSONDecodeError, KeyError, OSError, TypeError, ValueError):
            errors.append("live observer latest snapshot artifact is invalid")
    disk_admissible = state.get("gpt_oss_120b_currently_disk_admissible")
    if not isinstance(state.get("final_interpretation_ready"), bool) \
            or not isinstance(state.get("gpt_oss_120b_execution_ready"), bool) \
            or (disk_admissible is not None and not isinstance(disk_admissible, bool)) \
            or not isinstance(state.get("eta"), dict) \
            or not isinstance(state.get("final_gate_blockers"), list) \
            or not all(isinstance(row, str) for row in state.get("final_gate_blockers", [])):
        errors.append("live observer readiness fields are invalid")
    if state.get("final_interpretation_ready") is False \
            and (state.get("final_interpretation_packet") is not None
                 or state.get("final_interpretation_handoff") is not None):
        errors.append("live observer has premature final-interpretation artifacts")
    if state.get("final_interpretation_ready") is True \
            and (not isinstance(state.get("final_interpretation_packet"), dict)
                 or not isinstance(state.get("final_interpretation_handoff"), dict)):
        errors.append("live observer final-interpretation references are invalid")
    return errors


def _reference_shape_valid(reference: Any) -> bool:
    if not isinstance(reference, dict) or set(reference) != {"path", "sha256", "bytes"}:
        return False
    digest, size, path = reference.get("sha256"), reference.get("bytes"), reference.get("path")
    return isinstance(path, str) and bool(path) \
        and isinstance(digest, str) and len(digest) == 64 \
        and all(character in "0123456789abcdef" for character in digest) \
        and isinstance(size, int) and not isinstance(size, bool) and size >= 0


def _lease_available(path: Path) -> bool:
    """Probe an advisory singleton lease without retaining it."""
    try:
        handle = path.open("a+")
    except OSError:
        return False
    try:
        try:
            fcntl.flock(handle.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            return False
        fcntl.flock(handle.fileno(), fcntl.LOCK_UN)
        return True
    except OSError:
        return False
    finally:
        handle.close()


def _fsync_dir(path: Path) -> None:
    descriptor = os.open(path, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def _atomic_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False).encode() + b"\n"
    descriptor, raw = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary = Path(raw)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
        _fsync_dir(path.parent)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


def _validate_live_documents(plan: dict[str, Any], campaign: dict[str, Any],
                             state: dict[str, Any]) -> None:
    if plan.get("schema") != "hawking.doctor_v5_ultra_campaign_plan.v1" \
            or plan.get("plan_sha256") != _hash_value(_without(plan, "plan_sha256")):
        raise OverlayError("campaign plan identity is invalid")
    if campaign.get("schema") != "hawking.doctor_v5_ultra_campaign.v1" \
            or campaign.get("plan_sha256") != plan["plan_sha256"] \
            or campaign.get("campaign_sha256") \
            != _hash_value(_without(campaign, "campaign_sha256")):
        raise OverlayError("campaign projection identity is invalid")
    if state.get("schema") != "hawking.doctor_v5_ultra_queue_state.v1" \
            or state.get("plan_sha256") != plan["plan_sha256"]:
        raise OverlayError("queue state identity is invalid")
    planned = {row.get("cell_id") for row in plan.get("cells", [])}
    projected = {row.get("cell_id") for row in campaign.get("cells", [])}
    stated = set(state.get("cells", {}))
    if len(planned) != 320 or planned != projected or planned != stated:
        raise OverlayError("live plan/campaign/state cell sets differ")


def _observed_tier_rss(plan: dict[str, Any], path: Path = CHILD_RESOURCES) \
        -> dict[str, dict[str, int]]:
    labels = {row["cell_id"]: row["model_label"] for row in plan["cells"]}
    result: dict[str, dict[str, int]] = {}
    try:
        handle = path.open("r", encoding="utf-8")
    except (OSError, UnicodeError):
        return result
    with handle:
        for line in handle:
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            if not isinstance(row, dict) or row.get("plan_sha256") != plan["plan_sha256"]:
                continue
            label = labels.get(row.get("cell_id"))
            value = row.get("tree_rss_bytes")
            if label is None or isinstance(value, bool) or not isinstance(value, int) \
                    or value <= 0:
                continue
            evidence = result.setdefault(label, {"peak_bytes": 0, "samples": 0})
            evidence["samples"] += 1
            evidence["peak_bytes"] = max(evidence["peak_bytes"], value)
    return result


def _projected_residency(cell: dict[str, Any], margin_bytes: int) -> int:
    manifest = cell["parameter_manifest"]
    if cell["admission"]["whole_parent_residency_assumed"]:
        projected = RESIDENCY_BASE_WORKING_BYTES + math.ceil(
            manifest["source_weight_bytes"] * RESIDENCY_DENSE_FACTOR
        )
    else:
        projected = RESIDENCY_BASE_WORKING_BYTES + math.ceil(
            manifest["largest_source_shard_bytes"] * RESIDENCY_SHARD_FACTOR
        )
    ceiling = PROCESS_BUDGET_BYTES - margin_bytes
    return max(RESIDENCY_FLOOR_BYTES, min(ceiling, projected))


def _tier_reservations(plan: dict[str, Any], evidence: dict[str, dict[str, int]],
                       margin_bytes: int) -> tuple[dict[str, int], set[str]]:
    representatives: dict[str, dict[str, Any]] = {}
    for cell in plan["cells"]:
        representatives.setdefault(cell["model_label"], cell)
    reservations: dict[str, int] = {}
    uncalibrated_large: set[str] = set()
    for label, cell in representatives.items():
        projected = _projected_residency(cell, margin_bytes)
        measured = evidence.get(label, {}).get("peak_bytes", 0)
        reservations[label] = min(
            PROCESS_BUDGET_BYTES - margin_bytes,
            max(RESIDENCY_FLOOR_BYTES, projected, measured),
        )
        nominal = cell.get("nominal_params_b")
        if isinstance(nominal, (int, float)) and nominal > UNKNOWN_LARGE_TIER_THRESHOLD_B \
                and measured <= 0:
            uncalibrated_large.add(label)
    return reservations, uncalibrated_large


def _thermal_probe() -> dict[str, Any]:
    try:
        process = subprocess.run(
            ["pmset", "-g", "therm"], capture_output=True, text=True,
            timeout=5, check=False,
        )
        output = (process.stdout + process.stderr).strip()
        return {"ok": ram_scheduler.thermal_output_ok(process.returncode, output),
                "returncode": process.returncode, "output": output[-1000:]}
    except Exception as exc:
        return {"ok": False, "error": f"{type(exc).__name__}: {exc}"}


def resource_health(snapshot: dict[str, Any], thermal: dict[str, Any], *,
                    swap_tolerance_mb: float = SWAP_STALE_TOLERANCE_MB) \
        -> dict[str, Any]:
    """Fail closed on unknown pressure/swap/power/thermal observations."""
    blockers: list[str] = []
    if snapshot.get("pressure_level") != 1:
        blockers.append("memory pressure is not normal or is unavailable")
    swap = snapshot.get("swap_used_mb")
    if isinstance(swap, bool) or not isinstance(swap, (int, float)) \
            or not math.isfinite(float(swap)) or float(swap) > swap_tolerance_mb:
        blockers.append("swap exceeds the stale-probe tolerance or is unavailable")
    if "AC Power" not in str(snapshot.get("power_source", "")):
        blockers.append("AC power is not confirmed")
    if thermal.get("ok") is not True:
        blockers.append("thermal state is not explicitly green")
    return {"ok": not blockers, "blockers": blockers,
            "swap_tolerance_mb": swap_tolerance_mb,
            "snapshot": snapshot, "thermal": thermal}


def dynamic_margin(labels: Iterable[str], evidence: dict[str, dict[str, int]],
                   nominal_by_label: dict[str, float]) -> int:
    """Select headroom from the weakest residency evidence in a proposed pool.

    Twelve GB is used only after each large tier has at least three persisted RSS
    samples.  A partially calibrated large tier keeps 20 GB, and a never-observed
    large tier keeps the legacy 28 GB in addition to its exclusive-canary rule.
    Whole-parent <=16B projections are conservative and need no warm-up penalty.
    """
    margin = DYNAMIC_BASE_MARGIN_BYTES
    for label in set(labels):
        if nominal_by_label.get(label, 0.0) <= UNKNOWN_LARGE_TIER_THRESHOLD_B:
            continue
        samples = evidence.get(label, {}).get("samples", 0)
        if samples <= 0:
            margin = max(margin, CURRENT_MARGIN_BYTES)
        elif samples < 3:
            margin = max(margin, 20_000_000_000)
    return margin


def cpu_launch_gate(samples: Iterable[float], *, logical_cores: int | None = None,
                    guard_cores: float = CPU_GUARD_CORES,
                    consecutive_saturated: int = 3) -> dict[str, Any]:
    """Soft oversubscription gate with hysteresis.

    CPU saturation is not an evidence-corruption condition, so this gate pauses
    launches but never stops a running lane.  Unknown/non-finite observations
    fail closed whenever work is already live.
    """
    cores = logical_cores if logical_cores is not None else os.cpu_count()
    if isinstance(cores, bool) or not isinstance(cores, int) or cores <= 0 \
            or not math.isfinite(guard_cores) or not 0 <= guard_cores < cores \
            or isinstance(consecutive_saturated, bool) \
            or not isinstance(consecutive_saturated, int) or consecutive_saturated < 1:
        return {"ok": False, "blockers": ["CPU envelope is invalid"]}
    values = list(samples)
    if any(isinstance(value, bool) or not isinstance(value, (int, float))
           or not math.isfinite(float(value)) or value < 0 for value in values):
        return {"ok": False, "blockers": ["CPU utilization probe is invalid"]}
    budget = float(cores) - guard_cores
    tail = values[-consecutive_saturated:]
    saturated = len(tail) >= consecutive_saturated \
        and all(float(value) >= budget for value in tail)
    return {"ok": not saturated,
            "blockers": (["CPU budget saturated across the hysteresis window"]
                         if saturated else []),
            "logical_cores": cores, "guard_cores": guard_cores,
            "budget_cores": budget, "samples": values,
            "consecutive_saturated": consecutive_saturated}


def admission_decision(*, active_reservations: Iterable[int],
                       candidate_reservation: int, margin_bytes: int,
                       health: dict[str, Any], cpu_samples: Iterable[float],
                       live_labels: Iterable[str], candidate_label: str,
                       uncalibrated_large: set[str]) -> dict[str, Any]:
    """Pure launch decision for a future overlay-aware supervisor."""
    blockers: list[str] = []
    reservations = list(active_reservations)
    values = reservations + [candidate_reservation, margin_bytes]
    if any(isinstance(value, bool) or not isinstance(value, int) or value < 0
           for value in values):
        blockers.append("RAM reservation inputs are invalid")
    elif sum(reservations) + candidate_reservation + margin_bytes \
            > PROCESS_BUDGET_BYTES:
        blockers.append("candidate exceeds the measured RAM admission envelope")
    if health.get("ok") is not True:
        blockers.extend(f"resource: {row}" for row in health.get("blockers", []))
    cpu = cpu_launch_gate(cpu_samples)
    if cpu.get("ok") is not True:
        blockers.extend(f"cpu: {row}" for row in cpu.get("blockers", []))
    labels = list(live_labels)
    if candidate_label in uncalibrated_large and labels:
        blockers.append("uncalibrated large tier requires an exclusive canary lane")
    if any(label in uncalibrated_large for label in labels):
        blockers.append("an uncalibrated large-tier canary already owns the pool")
    return {"admit": not blockers, "blockers": blockers,
            "reserved_after_bytes": sum(reservations) + candidate_reservation,
            "margin_bytes": margin_bytes, "cpu": cpu}


def _process_rows() -> list[dict[str, Any]]:
    try:
        process = subprocess.run(
            ["ps", "-axo", "pid=,ppid=,pgid=,%cpu=,rss=,state="],
            capture_output=True, text=True, timeout=5, check=True,
        )
    except Exception as exc:
        raise OverlayError(f"process CPU/RSS probe failed: {exc}") from exc
    rows: list[dict[str, Any]] = []
    for line in process.stdout.splitlines():
        fields = line.split()
        if len(fields) < 6:
            continue
        try:
            rows.append({
                "pid": int(fields[0]), "ppid": int(fields[1]), "pgid": int(fields[2]),
                "cpu_percent": float(fields[3]), "rss_bytes": int(fields[4]) * 1024,
                "state": fields[5],
            })
        except ValueError:
            continue
    return rows


def _active_resource_sample(campaign: dict[str, Any]) -> dict[str, Any]:
    active = campaign.get("active_children", {})
    if not isinstance(active, dict):
        raise OverlayError("campaign active_children is invalid")
    rows = _process_rows()
    lanes: list[dict[str, Any]] = []
    for cell_id, child in active.items():
        if not isinstance(child, dict) or isinstance(child.get("pgid"), bool) \
                or not isinstance(child.get("pgid"), int):
            raise OverlayError(f"active child identity is invalid: {cell_id}")
        pgid = child["pgid"]
        children = [row for row in rows if row["pgid"] == pgid]
        if not children:
            raise OverlayError(f"active process group is not observable: {cell_id}")
        lanes.append({
            "cell_id": cell_id, "pgid": pgid,
            "cpu_cores": round(sum(row["cpu_percent"] for row in children) / 100.0, 3),
            "tree_rss_bytes": sum(row["rss_bytes"] for row in children),
            "reserved_bytes": child.get("reserved_bytes"),
            "max_tree_rss_bytes": child.get("max_tree_rss_bytes"),
            "process_count": len(children),
        })
    return {
        "sampled_at": _now(), "logical_cores": os.cpu_count(),
        "cpu_guard_cores": CPU_GUARD_CORES,
        "cpu_budget_cores": max(1.0, float(os.cpu_count() or 1) - CPU_GUARD_CORES),
        "active_cpu_cores": round(sum(row["cpu_cores"] for row in lanes), 3),
        "active_tree_rss_bytes": sum(row["tree_rss_bytes"] for row in lanes),
        "lanes": lanes,
    }


def _terminal_seal(campaign: dict[str, Any]) -> dict[str, Any]:
    rows = []
    for cell in campaign["cells"]:
        if cell["status"] not in TERMINAL:
            continue
        rows.append({
            "cell_id": cell["cell_id"], "status": cell["status"],
            "cell_identity_sha256": cell["cell_identity_sha256"],
            "runtime_spec_sha256": cell.get("runtime_spec_sha256"),
            "result_sha256": cell.get("result_sha256"),
            "execution_receipt_sha256": cell.get("execution_receipt_sha256"),
            "disposition_sha256": cell.get("disposition_sha256"),
        })
    rows.sort(key=lambda row: row["cell_id"])
    return {"count": len(rows), "rows_sha256": _hash_value(rows), "rows": rows}


def _remaining_durations(plan: dict[str, Any], campaign: dict[str, Any],
                         observation_time: dt.datetime, speedup: float) \
        -> dict[str, float]:
    if not math.isfinite(speedup) or speedup <= 0:
        raise OverlayError("speedup must be finite and positive")
    _, _, keyed_rates, _ = post_120b._runtime_rates(campaign)
    projected = {row["cell_id"]: row for row in campaign["cells"]}
    durations: dict[str, float] = {}
    for cell in plan["cells"]:
        row = projected[cell["cell_id"]]
        if row["status"] in TERMINAL:
            durations[cell["cell_id"]] = 0.0
            continue
        key = f"{cell['branch']}@{cell['rate_id']}"
        estimate = keyed_rates[key] * cell["exact_stored_parameter_count"] / 1e9
        if row["status"] == "running":
            child = campaign.get("active_children", {}).get(cell["cell_id"], {})
            started = post_120b._parse_time(child.get("started_at")) \
                if isinstance(child, dict) else None
            started = started or post_120b._parse_time(row.get("started_at"))
            if started is not None:
                elapsed = max(0.0, (observation_time - started).total_seconds())
                estimate = max(estimate * 0.1, estimate - elapsed)
        durations[cell["cell_id"]] = estimate / speedup
    return durations


def _candidate_order(pending: Iterable[str], plan_cells: dict[str, dict[str, Any]],
                     reservations: dict[str, int], free_bytes: int) -> list[str]:
    """Best-fill first, retaining plan priority as a deterministic tie-breaker."""
    return sorted(
        pending,
        key=lambda cell_id: (
            reservations[plan_cells[cell_id]["model_label"]] > free_bytes,
            -min(reservations[plan_cells[cell_id]["model_label"]], free_bytes),
            plan_cells[cell_id]["priority"], cell_id,
        ),
    )


def simulate(plan: dict[str, Any], campaign: dict[str, Any], *,
             margin_bytes: int, speedup: float = 1.0,
             include_unready_120b: bool = False,
             max_lanes: int = MAX_LANES,
             evidence: dict[str, dict[str, int]] | None = None) -> dict[str, Any]:
    """Dependency-preserving, RAM-packed schedule simulation.

    An uncalibrated >16B tier is deliberately restricted to one live lane until
    its first persisted high-water observation.  This makes the first 120B cell a
    canary even in the explicit non-executable 120B scenario.
    """
    if isinstance(margin_bytes, bool) or not isinstance(margin_bytes, int) \
            or not MIN_DYNAMIC_MARGIN_BYTES <= margin_bytes < PROCESS_BUDGET_BYTES:
        raise OverlayError("margin is outside the dynamic safety envelope")
    if isinstance(max_lanes, bool) or not isinstance(max_lanes, int) \
            or not 1 <= max_lanes <= MAX_LANES:
        raise OverlayError("max_lanes is invalid")
    observed = evidence if evidence is not None else _observed_tier_rss(plan)
    reservations, uncalibrated_large = _tier_reservations(plan, observed, margin_bytes)
    plan_cells = {row["cell_id"]: row for row in plan["cells"]}
    nominal_by_label = {
        row["model_label"]: float(row["nominal_params_b"]) for row in plan["cells"]
    }
    state = {row["cell_id"]: row for row in campaign["cells"]}
    allowed = {
        cell_id for cell_id, cell in plan_cells.items()
        if cell["model_label"] != "120B" or include_unready_120b
    }
    if any(state[cell_id]["status"] == "blocked-execution" for cell_id in allowed):
        return {"ok": False, "blocker": "one or more cells are blocked-execution"}
    finished = {cell_id for cell_id in allowed if state[cell_id]["status"] in TERMINAL}
    dependency_complete = {
        cell_id for cell_id in allowed if state[cell_id]["status"] == "complete"
    }
    pending = {
        cell_id for cell_id in allowed
        if state[cell_id]["status"] not in TERMINAL | {"running"}
    }
    now = dt.datetime.now(dt.timezone.utc)
    durations = _remaining_durations(plan, campaign, now, speedup)
    running: dict[str, tuple[float, int, str]] = {}
    for cell_id in allowed:
        if state[cell_id]["status"] != "running":
            continue
        label = plan_cells[cell_id]["model_label"]
        running[cell_id] = (durations[cell_id], reservations[label], label)
    elapsed = 0.0
    peak_lanes = len(running)
    peak_reserved = sum(row[1] for row in running.values())
    launch_counts: dict[str, int] = {}
    first_wave: list[str] = list(sorted(running))
    sub_cells = {cell_id for cell_id in allowed
                 if plan_cells[cell_id]["model_label"] != "120B"}
    sub_boundary = 0.0 if sub_cells <= finished else None
    ceiling = PROCESS_BUDGET_BYTES - margin_bytes
    while pending or running:
        used = sum(row[1] for row in running.values())
        free = ceiling - used
        for cell_id in _candidate_order(pending, plan_cells, reservations, free):
            if len(running) >= max_lanes:
                break
            cell = plan_cells[cell_id]
            label = cell["model_label"]
            if not set(cell["dependencies"]) <= dependency_complete:
                continue
            reserve = reservations[label]
            proposed_labels = [row[2] for row in running.values()] + [label]
            effective_margin = max(
                margin_bytes,
                dynamic_margin(proposed_labels, observed, nominal_by_label),
            )
            if used + reserve + effective_margin > PROCESS_BUDGET_BYTES:
                continue
            if label in uncalibrated_large and running:
                continue
            if any(row[2] in uncalibrated_large for row in running.values()):
                continue
            running[cell_id] = (elapsed + durations[cell_id], reserve, label)
            pending.remove(cell_id)
            used += reserve
            launch_counts[label] = launch_counts.get(label, 0) + 1
            if elapsed == 0.0 and cell_id not in first_wave:
                first_wave.append(cell_id)
        peak_lanes = max(peak_lanes, len(running))
        peak_reserved = max(peak_reserved, sum(row[1] for row in running.values()))
        if not running:
            return {"ok": False,
                    "blocker": "dependency/resource simulation reached no runnable cell"}
        elapsed = min(row[0] for row in running.values())
        just_finished = {
            cell_id for cell_id, row in running.items() if row[0] <= elapsed + 1e-9
        }
        for cell_id in just_finished:
            del running[cell_id]
        finished.update(just_finished)
        dependency_complete.update(just_finished)
        if sub_boundary is None and sub_cells <= finished:
            sub_boundary = elapsed
    return {
        "ok": True, "margin_bytes": margin_bytes,
        "admission_ceiling_bytes": ceiling, "speedup": speedup,
        "include_unready_120b": include_unready_120b,
        "sub_120b_seconds": round(sub_boundary or 0.0, 3),
        "through_120b_seconds": round(elapsed, 3) if include_unready_120b else None,
        "peak_lanes": peak_lanes, "peak_reserved_bytes": peak_reserved,
        "first_wave": first_wave, "launch_counts_by_tier": launch_counts,
        "reservations": reservations,
        "uncalibrated_large_tiers": sorted(uncalibrated_large),
        "semantics": (
            "heuristic dependency schedule; 120B inclusion is scenario-only until "
            "the reviewed execution gate passes; CPU-token contention is not applied to ETA"
        ),
    }


def build_overlay() -> dict[str, Any]:
    plan, campaign, state = _read_json(PLAN), _read_json(CAMPAIGN), _read_json(QUEUE_STATE)
    _validate_live_documents(plan, campaign, state)
    observer_errors = _observer_structure_errors()
    if observer_errors:
        raise OverlayError("live observer is structurally unready: "
                           + "; ".join(observer_errors))
    evidence = _observed_tier_rss(plan)
    reservations, uncalibrated = _tier_reservations(
        plan, evidence, DYNAMIC_BASE_MARGIN_BYTES
    )
    try:
        snapshot = ram_scheduler.resource_snapshot(str(ROOT))
    except Exception as exc:
        snapshot = {"error": f"{type(exc).__name__}: {exc}"}
    thermal = _thermal_probe()
    health = resource_health(snapshot, thermal)
    active_sample = _active_resource_sample(campaign)
    observer = _read_json(OBSERVER_STATE)
    ready_120b = observer.get("gpt_oss_120b_execution_ready") is True
    scenarios = []
    projected_120b_evidence = dict(evidence)
    # Sensitivity only: this is the static 120B streaming reservation promoted to
    # a hypothetical three-sample high-water.  It cannot authorize execution.
    representative_120b = next(
        cell for cell in plan["cells"] if cell["model_label"] == "120B"
    )
    projected_120b_evidence["120B"] = {
        "peak_bytes": _projected_residency(
            representative_120b, DYNAMIC_BASE_MARGIN_BYTES
        ),
        "samples": 3,
    }
    post_canary_scenarios = []
    for speedup in (1.0, 1.5, 2.0, 3.0):
        scenarios.append(simulate(
            plan, campaign, margin_bytes=DYNAMIC_BASE_MARGIN_BYTES,
            speedup=speedup, include_unready_120b=True, evidence=evidence,
        ))
        post_canary_scenarios.append(simulate(
            plan, campaign, margin_bytes=DYNAMIC_BASE_MARGIN_BYTES,
            speedup=speedup, include_unready_120b=True,
            evidence=projected_120b_evidence,
        ))
    current = simulate(
        plan, campaign, margin_bytes=CURRENT_MARGIN_BYTES, speedup=1.0,
        include_unready_120b=True, evidence=evidence,
    )
    policy = {
        "process_budget_bytes": PROCESS_BUDGET_BYTES,
        "base_margin_bytes": DYNAMIC_BASE_MARGIN_BYTES,
        "minimum_margin_bytes": MIN_DYNAMIC_MARGIN_BYTES,
        "max_lanes": MAX_LANES,
        "swap_stale_tolerance_mb": SWAP_STALE_TOLERANCE_MB,
        "cpu": {
            "logical_cores": os.cpu_count(), "guard_cores": CPU_GUARD_CORES,
            "admission_rule": (
                "sample aggregate process-group CPU; do not admit when observed active "
                "cores reach logical_cores-minus-guard; declared worker thread counts are "
                "not additive CPU reservations"
            ),
            "oversubscription_stop_rule": (
                "CPU saturation pauses new launches but never invalidates or kills evidence; "
                "RAM/swap/thermal hard guards retain stop authority"
            ),
        },
        "reservation_rule": (
            "max(static residency projection, persisted same-tier process-tree RSS high-water)"
        ),
        "dynamic_margin_rule": (
            "12 GB for calibrated large tiers; 20 GB with one or two persisted samples; "
            "legacy 28 GB plus exclusivity for an unobserved >16B tier"
        ),
        "uncalibrated_large_tier_rule": (
            "one exclusive canary lane until a persisted high-water RSS sample exists"
        ),
        "candidate_order": (
            "dependency-ready best RAM fill, then immutable plan priority and cell_id"
        ),
        "continuous_guards": {
            "aggregate_tree_rss_stop_at_bytes": PROCESS_BUDGET_BYTES,
            "pressure_level_required": 1,
            "swap_used_mb_max": SWAP_STALE_TOLERANCE_MB,
            "thermal_green_required": True,
            "ac_power_required": True,
            "victim_policy": "terminate/reap largest-RSS lane, retain pending resumability",
        },
    }
    overlay: dict[str, Any] = {
        "schema": SCHEMA, "version": VERSION, "created_at": _now(),
        "mode": "pending_only_opt_in",
        "source_bindings": {
            "plan": _file_reference(PLAN), "campaign": _file_reference(CAMPAIGN),
            "queue_state": _file_reference(QUEUE_STATE),
            "child_resources": _file_reference(CHILD_RESOURCES),
            "observer_source": _file_reference(Path(post_120b.__file__).resolve()),
            # Point-in-time provenance only. The live observer is mutable and
            # receives a structural/self-hash check at activation instead of
            # an impossible byte-for-byte compare-and-swap requirement.
            "observer_state_at_stage": _file_reference(OBSERVER_STATE),
            "plan_sha256": plan["plan_sha256"],
        },
        "immutable_terminal_seal": _terminal_seal(campaign),
        "policy": policy,
        "measured_tier_residency": evidence,
        "effective_tier_reservations": reservations,
        "uncalibrated_large_tiers": sorted(uncalibrated),
        "resource_health_at_stage": health,
        "active_resource_sample": active_sample,
        "simulation": {
            "schema": SIMULATION_SCHEMA,
            "current_fixed_margin_scenario": current,
            "dynamic_margin_scenarios": scenarios,
            "post_canary_reservation_sensitivity": post_canary_scenarios,
            "post_canary_sensitivity_is_admission_evidence": False,
            "gpt_oss_120b_execution_ready": ready_120b,
            "projection_only_120b": not ready_120b,
        },
        "promotion": {
            "automatic_live_redeployment_permitted": False,
            "requires_queue_status": ["paused", "drained"],
            "requires_zero_active_children": True,
            "requires_zero_heavy_children": True,
            "requires_plan_sha256_match": True,
            "requires_terminal_seal_subset_match": True,
            "requires_live_observer_structural_readiness": True,
            "requires_resource_health_reprobe": True,
            "requires_overlay_path_env": ENV_OVERLAY,
            "requires_overlay_sha256_env": ENV_OVERLAY_SHA256,
            "atomic_sequence": [
                "request drain using the existing supervisor control contract",
                "wait for all children to be reaped and leases released",
                "rebuild overlay against the checkpoint campaign projection",
                "verify plan identity and terminal seal; acquire singleton and heavy leases",
                "start the reviewed overlay-aware supervisor with both activation keys",
                "on any failure, remove activation keys and resume the unchanged supervisor",
            ],
            "rollback": (
                "overlay changes no cell identity, runtime spec, result, receipt, disposition, "
                "or completed evidence; rollback is removal of the two activation keys"
            ),
        },
    }
    overlay["overlay_sha256"] = _hash_value(overlay)
    return overlay


def validate_overlay(overlay: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    if overlay.get("schema") != SCHEMA or overlay.get("version") != VERSION:
        errors.append("overlay schema/version mismatch")
    if overlay.get("mode") != "pending_only_opt_in":
        errors.append("overlay mode is not pending-only")
    if overlay.get("overlay_sha256") != _hash_value(_without(overlay, "overlay_sha256")):
        errors.append("overlay canonical hash mismatch")
    policy = overlay.get("policy")
    if not isinstance(policy, dict) \
            or policy.get("process_budget_bytes") != PROCESS_BUDGET_BYTES \
            or policy.get("minimum_margin_bytes", 0) < MIN_DYNAMIC_MARGIN_BYTES:
        errors.append("overlay resource envelope is weaker than the reviewed minimum")
    simulation = overlay.get("simulation")
    if not isinstance(simulation, dict) \
            or simulation.get("schema") != SIMULATION_SCHEMA \
            or not isinstance(simulation.get("gpt_oss_120b_execution_ready"), bool) \
            or not isinstance(simulation.get("projection_only_120b"), bool) \
            or simulation.get("projection_only_120b") \
            == simulation.get("gpt_oss_120b_execution_ready"):
        errors.append("overlay 120B simulation/readiness anchor is invalid")
    bindings = overlay.get("source_bindings")
    expected_bindings = {
        "plan", "campaign", "queue_state", "child_resources",
        "observer_source", "observer_state_at_stage", "plan_sha256",
    }
    if not isinstance(bindings, dict) or set(bindings) != expected_bindings \
            or not all(_reference_shape_valid(bindings.get(name)) for name in (
                "plan", "campaign", "queue_state", "child_resources",
                "observer_source", "observer_state_at_stage",
            )):
        errors.append("overlay source-binding provenance is invalid")
    promotion = overlay.get("promotion")
    if not isinstance(promotion, dict) \
            or promotion.get("automatic_live_redeployment_permitted") is not False \
            or promotion.get("requires_zero_active_children") is not True \
            or promotion.get("requires_terminal_seal_subset_match") is not True \
            or promotion.get("requires_live_observer_structural_readiness") is not True:
        errors.append("overlay promotion is not fail-closed")
    return errors


def activation_preflight(overlay: dict[str, Any], plan: dict[str, Any],
                         campaign: dict[str, Any], state: dict[str, Any],
                         health: dict[str, Any], *,
                         singleton_lease_available: bool | None = None,
                         heavy_lease_available: bool | None = None) -> dict[str, Any]:
    blockers = validate_overlay(overlay)
    if overlay.get("source_bindings", {}).get("plan_sha256") != plan.get("plan_sha256"):
        blockers.append("live plan does not match overlay")
    bindings = overlay.get("source_bindings", {})
    for name in (
            "plan", "campaign", "queue_state", "child_resources",
            "observer_source"):
        if not _reference_matches(bindings.get(name)):
            blockers.append(f"source binding changed or is invalid: {name}")
    blockers.extend(_observer_structure_errors())
    if not any(row.startswith("live observer") for row in blockers):
        observer = _read_json(OBSERVER_STATE)
        staged_ready = overlay.get("simulation", {}).get(
            "gpt_oss_120b_execution_ready"
        )
        if staged_ready is True \
                and observer.get("gpt_oss_120b_execution_ready") is not True:
            blockers.append("live observer regressed from staged 120B readiness")
    active = campaign.get("active_children")
    if not isinstance(active, dict) or active:
        blockers.append("campaign is not quiescent")
    if state.get("status") not in {"paused", "drained"}:
        blockers.append("queue is not paused/drained")
    sealed = overlay.get("immutable_terminal_seal", {})
    current = _terminal_seal(campaign)
    sealed_rows = {row["cell_id"]: row for row in sealed.get("rows", [])
                   if isinstance(row, dict) and isinstance(row.get("cell_id"), str)}
    current_rows = {row["cell_id"]: row for row in current["rows"]}
    if any(current_rows.get(cell_id) != row for cell_id, row in sealed_rows.items()):
        blockers.append("one or more terminal records changed after staging")
    if health.get("ok") is not True:
        blockers.extend(f"resource: {item}" for item in health.get("blockers", []))
    if singleton_lease_available is not True:
        blockers.append("queue singleton lease is not available")
    if heavy_lease_available is not True:
        blockers.append("studio heavy lease is not available")
    return {"ready": not blockers, "blockers": blockers,
            "terminal_rows_sealed": len(sealed_rows),
            "terminal_rows_current": len(current_rows)}


def load_activated_overlay(env: dict[str, str] | None = None) -> dict[str, Any] | None:
    """Two-key loader for a future overlay-aware supervisor.

    Absence means current behavior.  Partial configuration or any identity error
    raises instead of silently falling back.
    """
    source = os.environ if env is None else env
    raw_path, expected = source.get(ENV_OVERLAY), source.get(ENV_OVERLAY_SHA256)
    if raw_path is None and expected is None:
        return None
    if not raw_path or not expected:
        raise OverlayError("both stacked-admission activation keys are required")
    path = Path(raw_path).resolve(strict=True)
    try:
        path.relative_to(STAGE_ROOT.resolve(strict=True))
    except (OSError, ValueError) as exc:
        raise OverlayError("activated overlay escapes the staged root") from exc
    overlay = _read_json(path)
    errors = validate_overlay(overlay)
    if errors:
        raise OverlayError("invalid activated overlay: " + "; ".join(errors))
    if expected != overlay["overlay_sha256"]:
        raise OverlayError("activation SHA does not match overlay")
    return overlay


def _summary(overlay: dict[str, Any]) -> dict[str, Any]:
    scenarios = overlay["simulation"]["dynamic_margin_scenarios"]
    return {
        "schema": overlay["schema"], "overlay_sha256": overlay["overlay_sha256"],
        "mode": overlay["mode"],
        "terminal_cells_sealed": overlay["immutable_terminal_seal"]["count"],
        "resource_health": overlay["resource_health_at_stage"]["ok"],
        "active_cpu_cores": overlay["active_resource_sample"]["active_cpu_cores"],
        "active_tree_rss_bytes": overlay["active_resource_sample"]["active_tree_rss_bytes"],
        "uncalibrated_large_tiers": overlay["uncalibrated_large_tiers"],
        "current_fixed_margin": overlay["simulation"]["current_fixed_margin_scenario"],
        "dynamic_scenarios": [
            {"speedup": row.get("speedup"), "sub_120b_seconds": row.get("sub_120b_seconds"),
             "through_120b_seconds": row.get("through_120b_seconds"),
             "peak_lanes": row.get("peak_lanes"), "ok": row.get("ok")}
            for row in scenarios
        ],
        "post_canary_sensitivity": [
            {"speedup": row.get("speedup"), "sub_120b_seconds": row.get("sub_120b_seconds"),
             "through_120b_seconds": row.get("through_120b_seconds"),
             "peak_lanes": row.get("peak_lanes"), "ok": row.get("ok")}
            for row in overlay["simulation"]["post_canary_reservation_sensitivity"]
        ],
        "promotion_ready_now": False,
        "promotion_reason": "live campaign must drain to a checkpoint first",
    }


def _main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("status", help="read-only live dry-run")
    stage = sub.add_parser("stage", help="write an inert hash-bound overlay")
    stage.add_argument("--output", type=Path, default=DEFAULT_OVERLAY)
    audit = sub.add_parser("audit", help="validate an overlay and activation gates")
    audit.add_argument("--overlay", type=Path, default=DEFAULT_OVERLAY)
    args = parser.parse_args()

    if args.command in {"status", "stage"}:
        overlay = build_overlay()
        if args.command == "stage":
            output = args.output.resolve()
            try:
                output.relative_to(STAGE_ROOT.resolve())
            except ValueError as exc:
                raise OverlayError("stage output must remain below staged_acceleration") from exc
            _atomic_json(output, overlay)
        print(json.dumps(_summary(overlay), indent=2, sort_keys=True))
        return 0

    overlay = _read_json(args.overlay.resolve())
    plan, campaign, state = _read_json(PLAN), _read_json(CAMPAIGN), _read_json(QUEUE_STATE)
    _validate_live_documents(plan, campaign, state)
    try:
        snapshot = ram_scheduler.resource_snapshot(str(ROOT))
    except Exception as exc:
        snapshot = {"error": f"{type(exc).__name__}: {exc}"}
    preflight = activation_preflight(
        overlay, plan, campaign, state, resource_health(snapshot, _thermal_probe()),
        singleton_lease_available=_lease_available(QUEUE_LOCK),
        heavy_lease_available=_lease_available(HEAVY_LOCK),
    )
    print(json.dumps({"overlay_sha256": overlay.get("overlay_sha256"),
                      "validation_errors": validate_overlay(overlay),
                      "activation_preflight": preflight}, indent=2, sort_keys=True))
    return 0 if not validate_overlay(overlay) else 1


if __name__ == "__main__":
    try:
        raise SystemExit(_main())
    except OverlayError as exc:
        print(f"doctor_v5_stacked_admission: {exc}", file=sys.stderr)
        raise SystemExit(2)
