#!/usr/bin/env python3.12
"""Doctor Prime Part V - reusable CAUSAL INTERVENTION harness for qwen3_moe-shaped parents.

WHY. The Qwen campaign's single most informative measurement was not a weight-error study, it was
the pair of causal controls D1/D2: hold everything at teacher fidelity except ONE named component,
run the real forward, read the loss off the output distribution. Those controls were hand-wired
into the campaign ladder and died with it. This module makes them a parameterised API so the next
parent is diagnosed on day one instead of month three.

WHAT IT COMPOSES. An Intervention names, per block, which components are supplied by the STUDENT
(i.e. LESIONED); everything else is supplied by the teacher:

    attention | router | experts | norms | final_norm | lm_head

plus three surgical extras:

    router_mask            restrict routing to a survivor subset (the D1 lesion)
    teacher_tensors        exact critical-tensor substitution by name/prefix, overriding everything
    reset_to_teacher_after hidden-state reset: after block k, x_student := x_teacher (lockstep)

From those primitives every boundary the campaign needed falls out:

    teacher router + student experts      Intervention(student={"experts"})
    student router + teacher outputs      Intervention(student={"router"})
    teacher attention + student MoE       Intervention(student={"router","experts"})
    student attention + teacher MoE       Intervention(student={"attention"})
    teacher organ injection (per organ)   drop that organ from student_components
    per-block scoping                     student_blocks=(...)
    exact critical-tensor substitution    teacher_tensors=("model.layers.3.mlp.experts.",)
    teacher final norm / unembed          leave "final_norm"/"lm_head" out of student_components
    hidden-state reset after block k      reset_to_teacher_after=(k,)

DEGRADATION PROPAGATION GRAPH (the point of the whole file). Two block-scoped sweeps over the same
driver answer the question "where do I treat?" instead of "which tensor is loudest":

    prefix_teacher[k]   blocks 0..k teacher, k+1.. student   -> damage still generated by the TAIL
    suffix_teacher[k]   blocks 0..k student, k+1.. teacher   -> damage the teacher tail CANNOT wash
                                                                out, i.e. IRREVERSIBLE damage

ONSET is the first block whose marginal contribution to prefix_teacher exceeds a fraction of the
total; IRREVERSIBLE is the first k at which suffix_teacher stops returning to teacher quality.

HONESTY BOUNDARY. This file is validated against a SYNTHETIC TWIN (a 2-layer / 4-expert / hidden-16
qwen3_moe with random bf16 weights on real safetensors shards, the same fixture as
tests/test_qwen_real_forward.py). The twin validates the MECHANISM - that composition, masking,
substitution and hidden-state reset do exactly what they claim - and NOTHING about any parent.
Random weights carry no capability, so every number the self-check prints is a mechanism receipt,
not a science result. symKL / argmax on a calibration batch remain OUTPUT-SPACE PROXIES; they are
losses and are reported as losses.

BIT LAW. This harness is pure diagnosis. It proposes, schedules and promotes no payload, so it
consumes no share of the 1.0 bits/weight ceiling. Any treatment it motivates must still be billed
at INSTALLED bits through tools/foundry/one_bit_ceiling.py.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from dataclasses import dataclass, replace
from typing import Any, Callable, Iterable, Sequence

import numpy as np

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

import qwen_real_forward as Q  # noqa: E402

COMPONENTS = ("embeddings", "attention", "router", "experts", "norms", "final_norm", "lm_head")
_BLOCK_SCOPED = ("attention", "router", "experts", "norms")


# ── intervention ──────────────────────────────────────────────────────────────────────────────
@dataclass(frozen=True)
class Intervention:
    """Which components come from the STUDENT. Everything unnamed comes from the teacher.

    Lesions, not repairs: an intervention names what is DEGRADED, so composing two interventions is
    the union of their lesions and never silently heals one of them. student_blocks=None means
    "all blocks"; a tuple scopes the block-scoped components to those block indices. final_norm /
    lm_head are not block-scoped and honour student_components alone.
    """
    label: str = "iv"
    student_components: frozenset[str] = frozenset()
    student_blocks: tuple[int, ...] | None = None
    router_mask: tuple[int, ...] | None = None
    teacher_tensors: tuple[str, ...] = ()
    reset_to_teacher_after: tuple[int, ...] = ()

    def __post_init__(self) -> None:
        bad = set(self.student_components) - set(COMPONENTS)
        if bad:
            raise ValueError(f"unknown components {sorted(bad)}; known = {COMPONENTS}")

    # stable, label-independent identity so results are keyed reproducibly
    @property
    def id(self) -> str:
        payload = json.dumps({
            "student_components": sorted(self.student_components),
            "blocks": None if self.student_blocks is None else sorted(self.student_blocks),
            "router_mask": None if self.router_mask is None else sorted(self.router_mask),
            "teacher_tensors": sorted(self.teacher_tensors),
            "reset_after": sorted(self.reset_to_teacher_after),
        }, sort_keys=True)
        return hashlib.sha1(payload.encode()).hexdigest()[:12]

    def student_at(self, block: int, component: str) -> bool:
        if component not in self.student_components:
            return False
        if component not in _BLOCK_SCOPED or self.student_blocks is None:
            return True
        return block in self.student_blocks

    def __or__(self, other: "Intervention") -> "Intervention":
        if self.router_mask is not None and other.router_mask is not None \
                and set(self.router_mask) != set(other.router_mask):
            raise ValueError("cannot compose two different router masks")
        if (self.student_blocks is None) != (other.student_blocks is None) \
                and (self.student_components and other.student_components):
            raise ValueError("cannot compose all-block and block-scoped interventions; "
                             "make both explicit")
        blocks = None if self.student_blocks is None else tuple(
            sorted(set(self.student_blocks) | set(other.student_blocks or ())))
        return Intervention(
            label=f"{self.label}+{other.label}",
            student_components=self.student_components | other.student_components,
            student_blocks=blocks,
            router_mask=self.router_mask if self.router_mask is not None else other.router_mask,
            teacher_tensors=tuple(sorted(set(self.teacher_tensors) | set(other.teacher_tensors))),
            reset_to_teacher_after=tuple(sorted(
                set(self.reset_to_teacher_after) | set(other.reset_to_teacher_after))),
        )

    def __sub__(self, organs: Iterable[str]) -> "Intervention":
        """Teacher organ injection: drop these components from the lesion set."""
        drop = set(organs)
        return replace(self, label=f"{self.label}-{'+'.join(sorted(drop))}",
                       student_components=self.student_components - drop)

    def to_json(self) -> dict[str, Any]:
        return {"label": self.label, "id": self.id,
                "student_components": sorted(self.student_components),
                "student_blocks": self.student_blocks,
                "router_mask": self.router_mask,
                "teacher_tensors": list(self.teacher_tensors),
                "reset_to_teacher_after": list(self.reset_to_teacher_after)}


ALL_TEACHER = Intervention("all_teacher", frozenset())            # no lesions
ALL_STUDENT = Intervention("all_student", frozenset(COMPONENTS))  # every component lesioned


# ── readers: student degradation + exact tensor substitution ──────────────────────────────────
class TransformReader:
    """Wraps a reader and applies fn(name, array) -> array. The student parent, without a second
    checkpoint on disk. Any reader with has/bf16/bf16_rows/source_dir works."""

    def __init__(self, inner: Any, fn: Callable[[str, np.ndarray], np.ndarray]):
        self.inner, self.fn = inner, fn
        self.source_dir = getattr(inner, "source_dir", None)

    def has(self, name: str) -> bool: return self.inner.has(name)
    def source_present(self) -> bool: return self.inner.source_present()
    def shard_of(self, name: str) -> str: return self.inner.shard_of(name)
    def close(self) -> None: self.inner.close()

    def bf16(self, name: str) -> np.ndarray:
        return self.fn(name, self.inner.bf16(name))

    def bf16_rows(self, name: str, rows: list[int]) -> np.ndarray:
        return self.fn(name, self.inner.bf16(name))[rows]


class HybridReader:
    """Student reader, except tensors whose name matches a teacher_tensors prefix come from the
    teacher byte-exactly. This is 'exact critical-tensor substitution'."""

    def __init__(self, student: Any, teacher: Any, patterns: Sequence[str]):
        self.student, self.teacher, self.patterns = student, teacher, tuple(patterns)
        self.source_dir = getattr(student, "source_dir", None)

    def _side(self, name: str) -> Any:
        return self.teacher if any(name.startswith(p) or name == p for p in self.patterns) \
            else self.student

    def has(self, name: str) -> bool: return self.student.has(name)
    def source_present(self) -> bool: return self.student.source_present()
    def shard_of(self, name: str) -> str: return self.student.shard_of(name)
    def close(self) -> None: pass          # borrowed readers; owners close them

    def bf16(self, name: str) -> np.ndarray:
        return self._side(name).bf16(name)

    def bf16_rows(self, name: str, rows: list[int]) -> np.ndarray:
        return self._side(name).bf16_rows(name, rows)


def student_forward(teacher: Q.QwenRealForward,
                    fn: Callable[[str, np.ndarray], np.ndarray]) -> Q.QwenRealForward:
    """Build a student parent by transforming the teacher's tensors on read (own expert cache)."""
    from bounded_cache import PressureAwareCache
    return Q.QwenRealForward(TransformReader(teacher.reader, fn), teacher.g,
                             cache=PressureAwareCache("doctor-student", verbose=False))


# ── metrics (output-space PROXIES, reported as losses) ────────────────────────────────────────
def _logsoftmax(z: np.ndarray) -> np.ndarray:
    z = z.astype(np.float64)
    z = z - z.max(axis=-1, keepdims=True)
    return z - np.log(np.exp(z).sum(axis=-1, keepdims=True))


def sym_kl(a: np.ndarray, b: np.ndarray) -> float:
    la, lb = _logsoftmax(a), _logsoftmax(b)
    pa, pb = np.exp(la), np.exp(lb)
    return float(np.mean(((pa - pb) * (la - lb)).sum(axis=-1)))


def argmax_agree(a: np.ndarray, b: np.ndarray) -> float:
    return float(np.mean(a.argmax(axis=-1) == b.argmax(axis=-1)))


# ── driver ────────────────────────────────────────────────────────────────────────────────────
class CausalHarness:
    """Applies an Intervention through the existing qwen_real_forward machinery.

    teacher and student are two QwenRealForward instances over the SAME geometry. The student is
    normally the teacher's reader wrapped in a degradation (student_forward), so the only
    difference between the streams is the treatment under test.
    """

    def __init__(self, teacher: Q.QwenRealForward, student: Q.QwenRealForward,
                 break_composition: bool = False):
        if (teacher.g.n_layers, teacher.g.hidden) != (student.g.n_layers, student.g.hidden):
            raise ValueError("teacher/student geometry mismatch")
        self.teacher, self.student, self.g = teacher, student, teacher.g
        # self-check lever: mis-wires the "experts" component so it always resolves to the teacher,
        # i.e. an intervention that claims to lesion experts silently does not. Used ONLY to prove
        # the assertions in selfcheck() actually fire when the composition is wrong.
        self.break_composition = break_composition
        self._baseline: dict[tuple[int, ...], np.ndarray] = {}

    # -- component selection -------------------------------------------------------------------
    def _pick(self, iv: Intervention, L: int, comp: str,
              student: Q.QwenRealForward) -> Q.QwenRealForward:
        st = iv.student_at(L, comp)
        if self.break_composition and comp == "experts":
            st = False          # mis-wire ONE component: experts silently sourced from the teacher
        return student if st else self.teacher

    # -- MoE with independently sourced router and experts (the D1/D2 seam) --------------------
    def _moe(self, router_f: Q.QwenRealForward, expert_f: Q.QwenRealForward, L: int,
             x: np.ndarray, mask: tuple[int, ...] | None) -> np.ndarray:
        g = self.g
        gate_w = router_f.reader.bf16(f"model.layers.{L}.mlp.gate.weight")
        logits = x @ gate_w.T
        if mask is not None:
            keep = np.zeros(gate_w.shape[0], dtype=bool)
            keep[list(mask)] = True
            logits = np.where(keep[None, :], logits, -np.inf)
        out = np.zeros_like(x)
        for p in range(x.shape[0]):
            idx, wts = Q.route_topk(logits[p], g.top_k, g.norm_topk_prob)
            xp, acc = x[p], np.zeros(g.hidden, dtype=np.float32)
            for e, gw in zip(idx, wts):
                ex = expert_f._get_expert(L, int(e), None)
                acc += gw * (ex["down"] @ Q.swiglu(ex["gate"] @ xp, ex["up"] @ xp))
            out[p] = acc
        return out

    def _block(self, iv: Intervention, L: int, x: np.ndarray,
               student: Q.QwenRealForward) -> np.ndarray:
        g = self.g
        att = self._pick(iv, L, "attention", student)
        x = x + att._attention(L, x)
        nf = self._pick(iv, L, "norms", student)
        h = Q.rmsnorm(x, nf.reader.bf16(f"model.layers.{L}.post_attention_layernorm.weight"), g.eps)
        rf = self._pick(iv, L, "router", student)
        ef = self._pick(iv, L, "experts", student)
        return x + self._moe(rf, ef, L, h, iv.router_mask)

    # -- full forward under an intervention ----------------------------------------------------
    def logits(self, token_ids: Sequence[int], iv: Intervention,
               max_blocks: int | None = None) -> np.ndarray:
        g = self.g
        student = self.student
        if iv.teacher_tensors:
            from bounded_cache import PressureAwareCache
            student = Q.QwenRealForward(
                HybridReader(student.reader, self.teacher.reader, iv.teacher_tensors), g,
                cache=PressureAwareCache("doctor-hybrid", verbose=False))
        nb = g.n_layers if max_blocks is None else min(max_blocks, g.n_layers)
        ids = list(token_ids)

        # The embedding table is a LESIONABLE component like any other. It was previously read
        # unconditionally from the student, which meant ALL_TEACHER was not all-teacher: an
        # embedding lesion contaminated the baseline by 0.111 symKL, roughly 26x the entire
        # reported intervention signal. A diagnosis harness whose control is contaminated cannot
        # attribute anything, which is the precise failure class this campaign exists to prevent.
        emb_src = student if "embeddings" in iv.student_components else self.teacher
        x = emb_src.reader.bf16_rows("model.embed_tokens.weight", ids)
        resets = set(iv.reset_to_teacher_after)
        xt = self.teacher.reader.bf16_rows("model.embed_tokens.weight", ids) if resets else None

        for L in range(nb):
            x = self._block(iv, L, x, student)
            if xt is not None:
                xt = self._block(ALL_TEACHER, L, xt, student)
                if L in resets:
                    x = xt.copy()
        if nb < g.n_layers:
            return x                                              # partial: raw hidden state
        fn = student if "final_norm" in iv.student_components else self.teacher
        lm = student if "lm_head" in iv.student_components else self.teacher
        x = Q.rmsnorm(x, fn.reader.bf16("model.norm.weight"), g.eps)
        name = "model.embed_tokens.weight" if g.tie else "lm_head.weight"
        return x @ lm.reader.bf16(name).T

    def baseline(self, token_ids: Sequence[int]) -> np.ndarray:
        key = tuple(token_ids)
        if key not in self._baseline:
            self._baseline[key] = self.logits(token_ids, ALL_TEACHER)
        return self._baseline[key]

    def run(self, token_ids: Sequence[int], iv: Intervention) -> dict[str, Any]:
        ref = self.baseline(token_ids)
        got = self.logits(token_ids, iv)
        return {"intervention": iv.to_json(), "id": iv.id, "label": iv.label,
                "sym_kl": sym_kl(ref, got), "argmax_agreement": argmax_agree(ref, got),
                "n_positions": int(ref.shape[0])}

    # -- degradation propagation graph ---------------------------------------------------------
    def propagation_graph(self, token_ids: Sequence[int],
                          lesion: Iterable[str] = ("router", "experts"),
                          onset_frac: float = 0.05,
                          irreversible_frac: float = 0.10) -> dict[str, Any]:
        """Where does degradation BEGIN, and where does it become IRREVERSIBLE?

        healed[k]: blocks 0..k teacher, rest student  -> loss still produced by the tail
        residual[k]: blocks 0..k student, rest teacher -> loss the teacher tail cannot repair
        """
        comps = frozenset(lesion)                       # the components the student supplies
        n = self.g.n_layers
        blocks = list(range(n))
        healed, residual = [], []
        for k in range(-1, n):
            tail = tuple(blocks[k + 1:])                # student runs the TAIL (teacher prefix)
            head = tuple(blocks[:k + 1])                # student runs the HEAD (teacher suffix)
            healed.append(self.run(token_ids, Intervention(
                f"prefix_teacher_{k}", comps, student_blocks=tail))["sym_kl"])
            residual.append(self.run(token_ids, Intervention(
                f"suffix_teacher_{k}", comps, student_blocks=head))["sym_kl"])
        # healed[0] is k=-1: no teacher blocks at all == full student loss on the lesion
        total = healed[0] if healed[0] > 0 else 1.0
        marginal = [healed[i] - healed[i + 1] for i in range(len(healed) - 1)]  # gain from block i
        onset = next((i for i, m in enumerate(marginal) if m > onset_frac * total), None)
        irreversible = next((k for k in range(n) if residual[k + 1] > irreversible_frac * total),
                            None)
        return {
            "lesion_components": sorted(comps),
            "teacher_components_kept": sorted(set(COMPONENTS) - comps),
            "n_blocks": n,
            "full_student_sym_kl": healed[0],
            "healed_sym_kl_by_k": healed,            # index 0 == k=-1
            "residual_sym_kl_by_k": residual,
            "marginal_damage_by_block": marginal,
            "onset_block": onset,
            "irreversible_block": irreversible,
            "onset_frac": onset_frac,
            "irreversible_frac": irreversible_frac,
        }


# ── synthetic twin + self-check ───────────────────────────────────────────────────────────────
def _twin(tmp: str, seed: int = 0):
    """Reuse the sealed tiny-qwen3_moe fixture from the real-forward test suite."""
    tests = os.path.join(_HERE, "tests")
    if tests not in sys.path:
        sys.path.insert(0, tests)
    import test_qwen_real_forward as T
    from pathlib import Path
    from bounded_cache import PressureAwareCache
    g = T._build_tiny_checkpoint(Path(tmp), seed=seed)
    reader = Q.SafetensorsIndexReader(Path(tmp))
    teacher = Q.QwenRealForward(reader, g, cache=PressureAwareCache("doctor-teacher", verbose=False))
    return teacher, g


def _deep_twin(tmp: str, n_layers: int = 8, seed: int = 3):
    """Same tiny qwen3_moe, but DEEP enough for the propagation graph to say something. Reuses the
    test suite's real-safetensors writer; only the layer count changes."""
    tests = os.path.join(_HERE, "tests")
    if tests not in sys.path:
        sys.path.insert(0, tests)
    import test_qwen_real_forward as T
    from pathlib import Path
    from bounded_cache import PressureAwareCache
    cfg = dict(T.TINY_CONFIG, num_hidden_layers=n_layers)
    g = Q.QwenGeometry(cfg)
    rng = np.random.default_rng(seed)
    rnd = lambda *sh, scale=0.08: (rng.standard_normal(sh) * scale).astype(np.float32)
    ones = lambda n: (1.0 + rng.standard_normal(n) * 0.02).astype(np.float32)
    t: dict[str, np.ndarray] = {
        "model.embed_tokens.weight": rnd(g.vocab, g.hidden, scale=0.2),
        "model.norm.weight": ones(g.hidden),
        "lm_head.weight": rnd(g.vocab, g.hidden, scale=0.2),
    }
    for L in range(n_layers):
        b = f"model.layers.{L}."
        t[b + "self_attn.q_proj.weight"] = rnd(g.q_out, g.hidden)
        t[b + "self_attn.k_proj.weight"] = rnd(g.kv_out, g.hidden)
        t[b + "self_attn.v_proj.weight"] = rnd(g.kv_out, g.hidden)
        t[b + "self_attn.o_proj.weight"] = rnd(g.hidden, g.q_out)
        t[b + "self_attn.q_norm.weight"] = ones(g.head_dim)
        t[b + "self_attn.k_norm.weight"] = ones(g.head_dim)
        t[b + "input_layernorm.weight"] = ones(g.hidden)
        t[b + "post_attention_layernorm.weight"] = ones(g.hidden)
        t[b + "mlp.gate.weight"] = rnd(g.n_experts, g.hidden)
        for e in range(g.n_experts):
            t[b + f"mlp.experts.{e}.gate_proj.weight"] = rnd(g.moe_inter, g.hidden)
            t[b + f"mlp.experts.{e}.up_proj.weight"] = rnd(g.moe_inter, g.hidden)
            t[b + f"mlp.experts.{e}.down_proj.weight"] = rnd(g.hidden, g.moe_inter)
    d = Path(tmp)
    T._write_safetensors(d / "model-00001-of-00001.safetensors", t)
    (d / "model.safetensors.index.json").write_text(json.dumps(
        {"metadata": {"total_size": 0},
         "weight_map": {n: "model-00001-of-00001.safetensors" for n in t}}))
    (d / "config.json").write_text(json.dumps(cfg))
    reader = Q.SafetensorsIndexReader(d)
    return Q.QwenRealForward(reader, g, cache=PressureAwareCache("deep-teacher", verbose=False)), g


def _pack(name: str, arr: np.ndarray) -> np.ndarray:
    """Crude sub-bit-ish expert 'packing': per-row 2-level sign codebook on gate/up/down only.
    Not a proposal - a lesion with a known shape, used to prove the harness sees it."""
    if ".mlp.experts." not in name:
        return arr
    mu = np.abs(arr).mean(axis=-1, keepdims=True)
    return (np.sign(arr) * mu).astype(np.float32)


def selfcheck(break_composition: bool = False, verbose: bool = True) -> dict[str, Any]:
    import tempfile
    with tempfile.TemporaryDirectory() as tmp:
        teacher, g = _twin(tmp)
        student = student_forward(teacher, _pack)
        H = CausalHarness(teacher, student, break_composition=break_composition)
        ids = [1, 5, 9, 2, 17, 4]
        ref = H.baseline(ids)

        # 0. the teacher path through the harness must reproduce the plain forward exactly.
        plain = teacher.logits_for(ids, positions="all")
        assert np.allclose(ref, plain, atol=1e-4), "ALL_TEACHER != unmodified forward"

        # 1. D1 analog: perfect (teacher) experts, routing masked to a survivor subset.
        survivors = tuple(range(g.n_experts // 2))
        d1 = Intervention("D1_route_masked", frozenset(), router_mask=survivors)
        # 2. D2 analog: full router, experts packed (student).
        d2 = Intervention("D2_experts_packed", frozenset({"experts"}))
        # 3. both lesions together (the composed artifact).
        s1 = d1 | d2
        r1, r2, rs = H.run(ids, d1), H.run(ids, d2), H.run(ids, s1)

        assert r1["sym_kl"] > 0.0, "masking routing did not move the output distribution"
        assert r2["sym_kl"] > 0.0, "packing experts did not move the output distribution"
        assert abs(r1["sym_kl"] - r2["sym_kl"]) > 1e-6, \
            "routing lesion and expert lesion are indistinguishable - composition is not wired"
        assert rs["sym_kl"] > 0.0 and rs["id"] not in (r1["id"], r2["id"]), "composition lost"
        assert ALL_STUDENT.id != ALL_TEACHER.id and d1.id != d2.id, "ids are not discriminative"

        # 4. hidden-state reset after the LAST block must equal the teacher exactly (everything the
        #    student computed is discarded); reset after block k must equal a teacher prefix 0..k.
        last = g.n_layers - 1
        lesion_all_blocks = frozenset(_BLOCK_SCOPED)   # head stays teacher
        full_reset = Intervention("reset_last", lesion_all_blocks,
                                  reset_to_teacher_after=(last,))
        assert H.run(ids, full_reset)["sym_kl"] < 1e-9, "reset after last block did not restore"
        k = 0
        via_reset = H.logits(ids, Intervention("r", lesion_all_blocks,
                                               reset_to_teacher_after=(k,)))
        via_prefix = H.logits(ids, Intervention("p", lesion_all_blocks,
                                                student_blocks=tuple(range(k + 1, g.n_layers))))
        assert np.allclose(via_reset, via_prefix, atol=1e-4), \
            "hidden reset at k != teacher prefix 0..k (shared embedding) - driver is wrong"

        # 5. exact critical-tensor substitution: naming every expert tensor back to the teacher
        #    must cancel the expert lesion completely.
        exact = Intervention("exact_expert_sub", frozenset({"experts"}),
                             teacher_tensors=tuple(
                                 f"model.layers.{L}.mlp.experts." for L in range(g.n_layers)))
        assert H.run(ids, exact)["sym_kl"] < 1e-9, "teacher_tensors substitution did not take"

        # 5b. head boundary: a student that degrades ONLY the final norm + unembed must move the
        #     output iff those components are named, and be inert otherwise.
        head_only = student_forward(
            teacher, lambda n, a: a * 0.5 if n in ("model.norm.weight", "lm_head.weight") else a)
        HH = CausalHarness(teacher, head_only, break_composition=break_composition)
        assert HH.run(ids, Intervention("head_student", frozenset({"final_norm", "lm_head"})
                                        ))["sym_kl"] > 0.0, "final_norm/lm_head boundary is dead"
        assert HH.run(ids, ALL_STUDENT - {"final_norm", "lm_head"})["sym_kl"] < 1e-9, \
            "head lesion leaked into the block components"

        # 6. propagation graph over the expert lesion.
        graph = H.propagation_graph(ids, lesion=("experts",))
        assert len(graph["healed_sym_kl_by_k"]) == g.n_layers + 1
        assert graph["healed_sym_kl_by_k"][-1] < 1e-9, "all-teacher prefix must be lossless"
        assert graph["residual_sym_kl_by_k"][0] < 1e-9, "all-teacher suffix must be lossless"
        student.reader.close()
        teacher.reader.close()

    # 7. deep twin: the propagation graph on 8 blocks, where onset/irreversibility can differ.
    with tempfile.TemporaryDirectory() as tmp2:
        dt, _dg = _deep_twin(tmp2, n_layers=8)
        ds = student_forward(dt, _pack)
        DH = CausalHarness(dt, ds, break_composition=break_composition)
        deep = DH.propagation_graph(ids, lesion=("experts",))
        assert deep["healed_sym_kl_by_k"][-1] < 1e-9 and deep["residual_sym_kl_by_k"][0] < 1e-9
        assert deep["full_student_sym_kl"] > 0.0, "deep twin lesion is invisible"
        ds.reader.close()
        dt.reader.close()

    if True:
        out = {"artifact": "tools/condense/doctor_causal_harness.py",
               "scope": "MECHANISM ONLY - synthetic twin with random bf16 weights. No parent, no "
                        "capability, no rate is claimed. symKL/argmax are output-space PROXIES and "
                        "are reported as losses.",
               "bit_law": "diagnostic harness; proposes no payload, bills no bits against the "
                          "1.0 bits/weight ceiling.",
               "twin_2block": "reuses tests/test_qwen_real_forward.py::_build_tiny_checkpoint",
               "twin_8block": "same fixture writer, num_hidden_layers=8",
               "student_lesion": "per-row sign*mean codebook on mlp.experts.* only",
               "D1_route_masked": r1, "D2_experts_packed": r2, "S1_composed": rs,
               "sub_additive": bool(rs["sym_kl"] < r1["sym_kl"] + r2["sym_kl"]),
               "parts_sum_sym_kl": r1["sym_kl"] + r2["sym_kl"],
               "propagation_graph_2block": graph,
               "propagation_graph_8block": deep}
        if verbose:
            print(json.dumps(out, indent=2))
        return out


def selfcheck_fails_when_broken() -> bool:
    """Mutate WHICH component is teacher and confirm an assertion fires."""
    try:
        selfcheck(break_composition=True, verbose=False)
    except AssertionError:
        return True
    return False


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--self-check", action="store_true")
    ap.add_argument("--report", type=str, default=None)
    a = ap.parse_args(argv)
    if not a.self_check:
        ap.print_help()
        return 0
    out = selfcheck(verbose=a.report is None)
    out["self_check_fails_when_broken"] = selfcheck_fails_when_broken()
    if a.report:
        os.makedirs(os.path.dirname(a.report), exist_ok=True)
        with open(a.report, "w") as fh:
            json.dump(out, fh, indent=2)
        print(f"wrote {a.report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
