"""Emit the consolidated H-ROADMAP-REVISED for ~/Downloads.

The four generated parts plus the compression measurement, wrapped in an
execution directive written the way the campaign directives are written: as
instructions to whoever runs Hawking next, not as description of what exists.

Generated, never hand-maintained. If a number here disagrees with
civilization/ROADMAP_STATE.json, this file is wrong and the state file is right,
so regenerate rather than edit.
"""
from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DOCS = REPO / "docs" / "roadmap"
STATE = REPO / "civilization" / "ROADMAP_STATE.json"
OUT = Path.home() / "Downloads" / "H-ROADMAP-REVISED.md"

PARTS = (
    "PART_I_VERIFIED_TODAY.md",
    "PART_II_ACTION_PLAN.md",
    "PART_III_CONSTITUTION_AND_RESEARCH.md",
    "COMPRESSION.md",
    "APPENDIX_LINEAGE.md",
)


def _header(state: dict) -> str:
    return f"""# H-ROADMAP — REVISED

Recompiled {datetime.now(UTC).strftime('%Y-%m-%d')}. Supersedes the 9645-line
H-ROADMAP.md, which is preserved verbatim and hashed at
docs/roadmap-lineage/ and remains the historical authority for anything this
document does not carry forward.

THIS FILE IS GENERATED by `python3 -m tools.roadmap.emit_revised`. Do not edit
it. If a number here disagrees with civilization/ROADMAP_STATE.json, this file
is wrong -- regenerate it.

    software connections remaining     {state['software_connection_remaining_count']}
    net future burden                  {state['net_future_burden']}
    capabilities integrated            {len(state['integrated_capabilities'])}
    experiment required                {len(state['experiment_required'])}
    long-run evidence required         {len(state['long_run_required'])}
    physical hardware required         {len(state['hardware_required'])}
    unknown research                   {len(state['unknown_research'])}
    evidence levels                    {state['evidence_levels']}

READ THIS FIRST. Nothing in PART I is complete because a file exists. Every
capability prints `absent` where its evidence is absent. PHYSICALLY_MEASURED is
zero across all 71 gates: no present capability rests on a physical measurement,
and that is the floor by design.

"""


def _directive(state: dict) -> str:
    active = state["active_actions"]
    hcli_owned = [a for a in active if a.startswith(("AGENTOS_", "HCLI_", "FPGA_", "FLASH_DENSE", "QWEN27_", "VMCP_AGENTOS", "VMCP_COMPACT", "VMCP_RECEIPT"))]
    return f"""
# PART II-B — EXECUTION DIRECTIVE

Written as instruction, not description. Whoever runs Hawking next executes this
without re-deriving it.

## 0. THE RULES THAT OUTRANK THE PLAN

    Do not fake an experiment result, a long-duration autonomy claim, a GPU
    measurement, an ANE measurement, an FPGA physical measurement, or DGX/eGPU
    behaviour. Build the infrastructure up to that boundary and stop there,
    saying which side of the line each artifact is on.

    Simulated is not measured. STATIC is not FUNCTIONAL_SIM is not
    HARDWARE_MEASURED. Never merge tiers to make a number look better.

    A capability is not BUILT because a file exists. It is BUILT when a non-test
    caller reaches it AND its own acceptance criterion has been demonstrated by
    a real run. Registration is not wiring. An import is not a call.

    Do not weaken, skip, delete or mark-slow a test to make a number. If a
    target is only reachable by checking less, MISS THE TARGET and report the
    honest floor.

    Fix the producer, not the artifact. Correcting a receipt leaves the thing
    that wrote it still wrong, and the next run restores the defect.

## 1. THE PRIMARY OBJECTIVE

    DRIVE software_connection_remaining TOWARD ZERO. It is {state['software_connection_remaining_count']}.

    A software connection is closed when, and only when: a non-test call site
    reaches the capability's named symbol, a verifier exercises it, and the
    verifier fails when the connection is cut. Prove the last part by cutting it.

    {len(hcli_owned)} of the {len(active)} belong to the parallel HCLI campaign. DO NOT
    implement those here. Represent their truth and their downstream gates, and
    let that campaign land them.

## 2. BEFORE WRITING CODE, CHECK WHETHER THE WORK EXISTS

    Every closure in this campaign so far was truth-finding, not code-writing:

        a receipt measured against a directory that had been reaped, whose
          version string matched on both sides so nothing flagged it;
        a capability PARKED on "openpty EPERM in this sandbox" that runs fine
          here, a per-context fact stated as a permanent one;
        three gates that declared no implementing symbol, so no call could ever
          match them however many production callers existed.

    So for each remaining connection, in this order:
        1. Does the gate NAME the symbol whose call counts? If not, that is the
           bug. VMCP_RECEIPT_LAW carries symbols= and reads BUILT; three others
           carried none and read as unwired scaffolding for months.
        2. Does its cited evidence point at a path that still exists, at the
           commit it claims? Re-run the producer; never edit the receipt.
        3. Is its blocker a live measurement or a stale sentence? Test the
           blocker before believing it.
        4. Only then write code.

## 3. THE VERIFICATION LAW IS NOT OPTIONAL

    EQUIVALENCE BETWEEN TWO EXECUTIONS OF THE SAME IMPLEMENTATION DOES NOT PROVE
    THE DEFINING PROPERTY.

    Before calling any capability verified, ask: what is its defining property,
    and does ANY test assert it against an independent source? Transcribe the
    property from the obligation, not from the code under test.

    Mutation-check anything load-bearing. Break the line, confirm the test
    fails, restore it, grep your marker. This probe found three live holes in
    code already described as bit-identical.

    {len(state['built_but_no_verifier'])} gates are BUILT with NO test citing them at all:
    {', '.join(state['built_but_no_verifier'])}.
    That is the highest-risk set in the graph. BUILT is not verified.

## 4. ODYSSEY — STREAMING, NO GLOBAL BARRIER

    I produces a law/scar/genome, II tests transfer immediately, III attacks I
    and II concurrently. II and III overlap heavily and remain epistemically
    distinct. There is NO global barrier.

    Measure separately, never as one number: time to first useful law, time to
    first transfer, time to first adversarial attack, time to a complete
    I+II+III cycle. First complete recurring cycle targets <= 48h wall.

    Read ModelLake state FROM DISK before planning. Stale "still downloading"
    prose must not survive contact with the specimen registry.

## 5. FPGA — EVERYTHING POSSIBLE BEFORE THE BOARD

    Canonical first target is the AMD/Xilinx Alveo U50DD / XCU50-class, 8 GB
    HBM2. Board performance is UNMEASURED until physical activation, and no
    receipt may say otherwise.

    {len(state['hardware_required'])} gates wake on hardware. Complete the pre-board path -- machine
    genome, HWIR, HBM topology, resource/cycle simulator, module description,
    organ mapping, placement, host/transport model, adaptation clocks -- and do
    not build generic multi-board abstraction before U50 tuition unless it
    demonstrably reduces U50 work itself. Generalize AFTER evidence.

## 6. WHAT NOT TO DO

    Do not expand an open research question into implementation tasks before
    evidence selects it. {len(state['unknown_research'])} question is genuinely open; leave it that way.

    Do not perform the large presentation/nomenclature refactor underneath an
    active science run. Freeze a known-good runtime commit first, do it in an
    isolated worktree, merge only after parity.

    Do not reap the aud* worktrees. preserve/aud-lane-parent-04193ccbc holds
    hcli/backends.py::repair_absent_required_arrays and its 87-line test, which
    exist nowhere else. Most of that commit was absorbed BY COPY, which is what
    makes it look landed. "dirty=0 and the files exist in HEAD" is not
    absorption; `git merge-base --is-ancestor` is.

"""


def build() -> Path:
    state = json.loads(STATE.read_text())
    body = [_header(state), _directive(state)]
    for name in PARTS:
        body.append((DOCS / name).read_text())
        body.append("\n")
    OUT.write_text("\n".join(body))
    return OUT


if __name__ == "__main__":
    print(build())
