#!/usr/bin/env python3.12
"""Unified retired-controller engine shells (S6 F2 C1).

One independent pytest nodeid per former retired shell case. Bodies remain in
``_retired_shell`` (S2-owned; imported only). Param rows are an inline literal so the
F1 extractor expands stable ``py_param`` identities.

For non-collision rows, ``slot`` is None and the runner treats ``name`` as the identity
label. Only rows that share (family, kind, name) carry an explicit class-qualified slot
from the old shell files.
"""
from __future__ import annotations
import sys
from pathlib import Path as _Path_repo
_REPO = _Path_repo(__file__).resolve().parents[3]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from pathlib import Path

import pytest

from tools.condense.tests._retired_shell import run


@pytest.mark.parametrize(
    "family,kind,name,slot",
    [
        ('eco', 'checkpoint', 'test_empty_dict_checkpoint_not_accepted', None),
        ('eco', 'checkpoint', 'test_idempotent_send_with_fake_sender', None),
        ('eco', 'lease', 'test_calibration_release_bound_and_deferred', None),
        ('eco', 'lifecycle', 'test_gate_refuses_running_campaign', None),
        ('eco', 'lifecycle', 'test_gate_refuses_without_signature', None),
        ('eco', 'lifecycle', 'test_gate_refuses_wrong_generation_even_when_signed', None),
        ('eco', 'lifecycle', 'test_selftest_green', 'TestEcoActivation.test_selftest_green'),
        ('eco', 'lifecycle', 'test_signed_go_activates_then_rollback', None),
        ('eco', 'lifecycle', 'test_wrong_plan_signature_rejected', None),
        ('eco', 'lifecycle', 'test_admissible_now_is_disk_consistent', None),
        ('eco', 'lifecycle', 'test_dense_405b_blocked', None),
        ('eco', 'lifecycle', 'test_each_parent_has_lifecycle_and_evidence_requirement', None),
        ('eco', 'lifecycle', 'test_gptoss_adapter_built_others_must_build', None),
        ('eco', 'lifecycle', 'test_scaling_prior_seeds_candidate_labeled_prior_only', None),
        ('eco', 'lifecycle', 'test_selftest_green', 'TestEcoAdmission.test_selftest_green'),
        ('eco', 'lifecycle', 'test_activation_gate_refuses_running', None),
        ('eco', 'lifecycle', 'test_admission_no_prior', None),
        ('eco', 'lifecycle', 'test_import_and_plan_and_materialize_against_mini_campaign', None),
        ('eco', 'lifecycle', 'test_passport_selftest', None),
        ('eco', 'lifecycle', 'test_pipeline_valid', None),
        ('eco', 'lifecycle', 'test_selftest_all_green', None),
        ('eco', 'lifecycle', 'test_imports_terminal_skips_running', None),
        ('eco', 'lifecycle', 'test_queue_plan_mismatch_refused', None),
        ('eco', 'lifecycle', 'test_selftest_green', 'TestEcoImport.test_selftest_green'),
        ('eco', 'lifecycle', 'test_wrong_plan_refused', None),
        ('eco', 'lifecycle', 'test_identity_edge_content_addressed', None),
        ('eco', 'lifecycle', 'test_identity_edge_rejects_bad_parent', None),
        ('eco', 'lifecycle', 'test_mint_and_verify_roundtrip', None),
        ('eco', 'lifecycle', 'test_missing_dimension_refused', None),
        ('eco', 'lifecycle', 'test_physical_bytes_rejects_runtime_role', None),
        ('eco', 'lifecycle', 'test_selftest_green', 'TestEcoPassport.test_selftest_green'),
        ('eco', 'lifecycle', 'test_advance_blocks_on_unmet_requires', None),
        ('eco', 'lifecycle', 'test_canonical_order_matches_directive', None),
        ('eco', 'lifecycle', 'test_every_passport_dimension_produced', None),
        ('eco', 'lifecycle', 'test_offline_hydrate_stops_at_gap', None),
        ('eco', 'lifecycle', 'test_passport_validator_enforced', None),
        ('eco', 'lifecycle', 'test_rollback_reverts_only_dependents', None),
        ('eco', 'lifecycle', 'test_runnable_progression', None),
        ('eco', 'lifecycle', 'test_selftest_green', 'TestEcoPipeline.test_selftest_green'),
        ('eco', 'lifecycle', 'test_awaiting_evidence_from_cohort', None),
        ('eco', 'lifecycle', 'test_byte_ceiling_from_device', None),
        ('eco', 'lifecycle', 'test_codec_control_fail_is_unresolved_pending_doctor', None),
        ('eco', 'lifecycle', 'test_diagnose_cases', None),
        ('eco', 'lifecycle', 'test_disposition_does_not_set_collapse_boundary', None),
        ('eco', 'lifecycle', 'test_disposition_is_resolved_fail', None),
        ('eco', 'lifecycle', 'test_doctor_program_from_diagnosis', None),
        ('eco', 'lifecycle', 'test_doctor_tried_but_out_of_contract_is_resolved_fail', None),
        ('eco', 'lifecycle', 'test_pass_bracket_and_stop', None),
        ('eco', 'lifecycle', 'test_selftest_green', 'TestEcoPlanner.test_selftest_green'),
        ('eco', 'lifecycle', 'test_unproven_when_no_evidence', None),
        ('eco', 'lifecycle', 'test_compose_shows_progress_and_blocked', None),
        ('eco', 'lifecycle', 'test_selftest_green', 'TestEcoStatus.test_selftest_green'),
        ('eco', 'lifecycle', 'test_calibrate_selftest', None),
        ('eco', 'lifecycle', 'test_intent_template_is_unsigned_and_bound', None),
        ('eco', 'lifecycle', 'test_launchd_plist_written_not_installed', None),
        ('eco', 'lifecycle', 'test_watch_selftest', None),
        ('eco', 'lifecycle', 'test_watch_waits_and_blocks_without_intent', None),
        ('eco', 'reseal', 'test_tampered_signature_rejected', None),
        ('eco', 'reseal', 'test_plan_is_sealed_and_covers_parents', None),
        ('eco', 'reseal', 'test_missing_status_does_not_break_seal', None),
        ('eco', 'reseal', 'test_seal_tamper_flagged', None),
        ('eco', 'reseal', 'test_tamper_detected_on_verify', None),
        ('eco', 'spec_repro', 'test_spec_is_valid_topo_order', None),
        ('eco', 'spec_repro', 'test_spec_sha256_is_deterministic_content_address', None),
        ('glm52', 'checkpoint', 'test_controller_checkpoint_binds_every_notification_head', None),
        ('glm52', 'checkpoint', 'test_crash_restart_replays_checkpoint_and_authenticates_heartbeat', None),
        ('glm52', 'checkpoint', 'test_exact_one_entry_crash_tail_is_recovered', None),
        ('glm52', 'checkpoint', 'test_restart_recovers_exact_event_tail_after_checkpoint_write_crash', None),
        ('glm52', 'checkpoint', 'test_write_is_atomic_idempotent_and_refuses_different_contract', None),
        ('glm52', 'fences_run', 'test_authority_record_freezes_last_token_logits_dsa_and_router_choices', None),
        ('glm52', 'fences_run', 'test_authority_refusal_precedes_plan_probe_git_resource_and_live_child', None),
        ('glm52', 'fences_run', 'test_each_production_authority_mismatch_refuses_before_any_live_process', None),
        ('glm52', 'fences_run', 'test_fence_not_false_blocks', None),
        ('glm52', 'fences_run', 'test_fp64_authority_materializes_physical_weights_without_f32_matvec', None),
        ('glm52', 'fences_run', 'test_full_traversal_authorized_false_when_floors_fail', None),
        ('glm52', 'fences_run', 'test_full_traversal_authorized_true_only_when_all_floors_clear', None),
        ('glm52', 'fences_run', 'test_pre_xet_authority_is_non_circular_and_post_xet_freeze_is_mandatory', None),
        ('glm52', 'fences_run', 'test_top_level_authorization_fields_remain_false_on_synthetic', None),
        ('glm52', 'launcher', 'test_full_model_receipts_admit_composition', None),
        ('glm52', 'launcher', 'test_source_grounding_rejects_symlink_and_hardlink', None),
        ('glm52', 'launcher', 'test_static_destination_symlink_and_partial_symlink_never_touch_victim', None),
        ('glm52', 'launcher', 'test_symlinked_root_refusal', None),
        ('glm52', 'launcher', 'test_symlinked_shard_refusal', None),
        ('glm52', 'launcher', 'test_worker_config_rejects_symlink_hardlink_and_nondeterministic_timestamp', None),
        ('glm52', 'lease', 'test_cli_gate_status_release', None),
        ('glm52', 'lease', 'test_concurrent_duplicate_prepare_has_one_winner', None),
        ('glm52', 'lease', 'test_exclusive_writer_never_deletes_a_racing_foreign_destination', None),
        ('glm52', 'lease', 'test_grounded_terminal_receipt_rederives_pass_and_refuses_blocked_release', None),
        ('glm52', 'lease', 'test_notification_semantic_audit_requires_and_uses_exact_held_lease', None),
        ('glm52', 'lease', 'test_persistent_run_audits_under_lease_at_each_dispatch_boundary', None),
        ('glm52', 'lease', 'test_preflight_never_calls_unleased_notification_audit', None),
        ('glm52', 'lease', 'test_production_authority_verifier_replays_exact_event_checkpoint_and_lease', None),
        ('glm52', 'lease', 'test_read_only_audit_rejects_wrong_configuration_and_unheld_lease', None),
        ('glm52', 'lease', 'test_release_records_free_bytes', None),
        ('glm52', 'lease', 'test_release_reruns_the_gate', None),
        ('glm52', 'lease', 'test_singleton_lease_refuses_second_worker_and_releases_after_failure', None),
        ('glm52', 'lease', 'test_static_symlink_lease_attack_is_rejected_before_target_write', None),
        ('glm52', 'lease', 'test_terminal_currentness_repeats_remote_then_refuses_lease_binding_drift', None),
        ('glm52', 'lease', 'test_the_byte_budget_evicts_least_recently_used_and_releases_the_backend_copy', None),
        ('glm52', 'lifecycle', 'test_a_cache_hit_re_reads_nothing_and_keeps_the_same_key', None),
        ('glm52', 'lifecycle', 'test_accepted_shapes_normalize_identically', None),
        ('glm52', 'lifecycle', 'test_ambiguity_requires_separately_signed_exact_reconciliation', None),
        ('glm52', 'lifecycle', 'test_anchored_writer_refuses_replaced_artifact_directory', None),
        ('glm52', 'lifecycle', 'test_any_hash_or_discrete_failure_refuses', None),
        ('glm52', 'lifecycle', 'test_artifact_manifest_rejects_fake_metrics_extra_files_and_corruption', None),
        ('glm52', 'lifecycle', 'test_attestation_and_freeze_bind_every_immutable_input', None),
        ('glm52', 'lifecycle', 'test_attestation_rejects_invalid_controller_anchor', None),
        ('glm52', 'lifecycle', 'test_attested_result_rejects_unknown_field_and_stale_hmac', None),
        ('glm52', 'lifecycle', 'test_attested_result_rejects_wrong_plan_evidence_with_fresh_hmac', None),
        ('glm52', 'lifecycle', 'test_authenticator_roles_reject_same_key_material', None),
        ('glm52', 'lifecycle', 'test_band_summary_threshold_keys', None),
        ('glm52', 'lifecycle', 'test_bootstrap_binds_only_existing_authenticated_readiness_bytes', None),
        ('glm52', 'lifecycle', 'test_bootstrap_main_uses_only_evidence_keychain_and_never_enables_dispatch', None),
        ('glm52', 'lifecycle', 'test_both_sidecar_key_suffix_variants_accepted', None),
        ('glm52', 'lifecycle', 'test_build_is_deterministic_for_explicit_timestamp', None),
        ('glm52', 'lifecycle', 'test_builds_exact_official_contract_and_losslessly_maps_eviction', None),
        ('glm52', 'lifecycle', 'test_byte_scenarios_reconcile_and_never_change_ranks', None),
        ('glm52', 'lifecycle', 'test_caffeinate_parent_exact_argv_rejects_any_program_drift', None),
        ('glm52', 'lifecycle', 'test_caffeinate_parent_validation', None),
        ('glm52', 'lifecycle', 'test_capability_is_issued_in_process_exactly_once_and_rechecks_state', None),
        ('glm52', 'lifecycle', 'test_capability_suite_is_shared_with_capability_gate', None),
        ('glm52', 'lifecycle', 'test_capability_suite_refuses_ambiguous_custom_tokens', None),
        ('glm52', 'lifecycle', 'test_capped_rank_512_cannot_enter_rank_512_floor', None),
        ('glm52', 'lifecycle', 'test_centered_regresses_to_production_svd', None),
        ('glm52', 'lifecycle', 'test_committed_policy_is_the_exact_deterministic_build', None),
        ('glm52', 'lifecycle', 'test_confirm_phrase_constant', None),
        ('glm52', 'lifecycle', 'test_continuous_memory_threshold_aborts_blocked_stream_and_never_publishes', None),
        ('glm52', 'lifecycle', 'test_contract_derived_bootstrap_writes_valid_fail_closed_configs', None),
        ('glm52', 'lifecycle', 'test_contract_v3_refuses_xet_only_source_identity', None),
        ('glm52', 'lifecycle', 'test_created_at_is_explicit_real_utc', None),
        ('glm52', 'lifecycle', 'test_created_at_must_be_explicit_and_deterministic', None),
        ('glm52', 'lifecycle', 'test_current_code_hash_mismatch', None),
        ('glm52', 'lifecycle', 'test_declared_capabilities_name_every_refusal_the_module_can_raise', None),
        ('glm52', 'lifecycle', 'test_declared_window_is_derived_only_from_validated_contract', None),
        ('glm52', 'lifecycle', 'test_deletion_never_touches_protected_trees', None),
        ('glm52', 'lifecycle', 'test_derives_exact_conservative_official_policy', None),
        ('glm52', 'lifecycle', 'test_deterministic_canonical_member_selection', None),
        ('glm52', 'lifecycle', 'test_disk_floor_is_hard_without_soft_allow', None),
        ('glm52', 'lifecycle', 'test_down_dual_analysis_fit_hold_z_correspondence_and_separation', None),
        ('glm52', 'lifecycle', 'test_down_equal_bytes_input_vs_output_side_at_same_rank', None),
        ('glm52', 'lifecycle', 'test_down_no_gaussian_path_without_gate_up', None),
        ('glm52', 'lifecycle', 'test_duplicate_layers_must_match_and_conflicts_fail', None),
        ('glm52', 'lifecycle', 'test_empty_reviewed_registry_hard_blocks_every_claimed_adapter', None),
        ('glm52', 'lifecycle', 'test_encoded_bytes_marks_arithmetic_not_physical_file', None),
        ('glm52', 'lifecycle', 'test_equal_byte_budget_across_arms', None),
        ('glm52', 'lifecycle', 'test_evaluate_tensor_identical_fit_holdout_hashes_across_arms', None),
        ('glm52', 'lifecycle', 'test_eviction_journal_read_is_bounded', None),
        ('glm52', 'lifecycle', 'test_eviction_rejects_same_content_identity_swap_and_journal_replay', None),
        ('glm52', 'lifecycle', 'test_eviction_rejects_target_renamed_to_unlisted_stash', None),
        ('glm52', 'lifecycle', 'test_evidence_band_boundaries', None),
        ('glm52', 'lifecycle', 'test_exact_completion_contract', None),
        ('glm52', 'lifecycle', 'test_exact_per_layer_route_conservation', None),
        ('glm52', 'lifecycle', 'test_exact_prepared_send_started_committed_lifecycle_and_redacted_receipt', None),
        ('glm52', 'lifecycle', 'test_existing_closure_inputs_are_frozen_and_fetch_has_prerequisite_gates', None),
        ('glm52', 'lifecycle', 'test_explicit_mean_does_not_get_a_free_extra_direction', None),
        ('glm52', 'lifecycle', 'test_explicit_mean_includes_mean_direction_and_is_orthogonal', None),
        ('glm52', 'lifecycle', 'test_extra_shard', None),
        ('glm52', 'lifecycle', 'test_fake_stream_materializes_exact_scheduled_shard_and_authenticates_receipt', None),
        ('glm52', 'lifecycle', 'test_final_sampler_failure_never_publishes_or_claims_a_valid_final_sample', None),
        ('glm52', 'lifecycle', 'test_final_schedule_rejects_semantic_result_without_controller_commit', None),
        ('glm52', 'lifecycle', 'test_fit_holdout_identity_across_calls', None),
        ('glm52', 'lifecycle', 'test_freeze_does_not_mutate_any_input', None),
        ('glm52', 'lifecycle', 'test_freeze_refuses_contract_without_exact_resource_policy', None),
        ('glm52', 'lifecycle', 'test_freeze_refuses_misplaced_or_duplicate_resource_policy_bindings', None),
        ('glm52', 'lifecycle', 'test_freeze_rejects_auth_for_another_campaign', None),
        ('glm52', 'lifecycle', 'test_freeze_rejects_reauthenticated_result_without_controller_anchor', None),
        ('glm52', 'lifecycle', 'test_full_phase_chain_and_transactional_eviction_preserve_other_paths', None),
        ('glm52', 'lifecycle', 'test_gaussian_selection_blocks', None),
        ('glm52', 'lifecycle', 'test_git_final_currentness_rejects_upstream_advance', None),
        ('glm52', 'lifecycle', 'test_git_provenance_requires_clean_exact_pushed_head', None),
        ('glm52', 'lifecycle', 'test_green_gate_and_confirmed_exact_deletion', None),
        ('glm52', 'lifecycle', 'test_hash_mismatch_shard', None),
        ('glm52', 'lifecycle', 'test_hash_or_size_failure_retains_partial_and_publishes_nothing', None),
        ('glm52', 'lifecycle', 'test_head_and_journal_deletion_or_prefix_rollback_are_detected', None),
        ('glm52', 'lifecycle', 'test_import_and_intent_build_are_body_and_stream_free', None),
        ('glm52', 'lifecycle', 'test_inflight_periodic_sample_cannot_race_clean_stream_exit', None),
        ('glm52', 'lifecycle', 'test_injected_verifier_and_provider_cannot_mutate_authoritative_view', None),
        (
            'glm52',
            'lifecycle',
            'test_inline_disk_floor_refuses_before_first_body_write_and_retains_empty_partial',
            None,
        ),
        ('glm52', 'lifecycle', 'test_invalid_dtype_fails_closed', None),
        ('glm52', 'lifecycle', 'test_invalid_expert_range_fails_closed', None),
        ('glm52', 'lifecycle', 'test_invalid_shape_fails_closed', None),
        ('glm52', 'lifecycle', 'test_launchd_plist_is_caffeinated_restartable_and_secret_free', None),
        ('glm52', 'lifecycle', 'test_launchd_plist_rejects_injection_and_every_argument_drift', None),
        ('glm52', 'lifecycle', 'test_layer_78_remains_unobserved_in_records', None),
        ('glm52', 'lifecycle', 'test_low_traffic_not_in_promotion_floor', None),
        ('glm52', 'lifecycle', 'test_measurement_math_changed_blocks', None),
        ('glm52', 'lifecycle', 'test_member_selective_loading_never_asks_for_non_topk', None),
        ('glm52', 'lifecycle', 'test_midstream_ram_violation_retains_written_partial_but_never_publishes', None),
        ('glm52', 'lifecycle', 'test_milestone_ladder_has_no_artificial_ceiling', None),
        ('glm52', 'lifecycle', 'test_missing_confirm_flag_cli', None),
        ('glm52', 'lifecycle', 'test_missing_layer_78_unobserved_and_covered_count', None),
        ('glm52', 'lifecycle', 'test_missing_shard', None),
        ('glm52', 'lifecycle', 'test_monitor_rejects_clock_regression_and_exact_gap_latency_overruns', None),
        ('glm52', 'lifecycle', 'test_monitor_sampling_failure_is_fail_closed_while_stream_is_active', None),
        ('glm52', 'lifecycle', 'test_notification_audit_bypass_is_synthetic_and_explicit_only', None),
        ('glm52', 'lifecycle', 'test_notification_static_readiness_never_claims_semantic_replay', None),
        ('glm52', 'lifecycle', 'test_numerical_equivalence_declares_tied_not_explicit_mean_unique', None),
        ('glm52', 'lifecycle', 'test_only_safe_nonplaceholder_chat_digest_is_accepted', None),
        ('glm52', 'lifecycle', 'test_orchestration_executes_exact_12_then_two_full_hashes_and_attests', None),
        ('glm52', 'lifecycle', 'test_panel_assignment', None),
        ('glm52', 'lifecycle', 'test_parent_journal_lock_and_fifo_replacement_are_detected', None),
        ('glm52', 'lifecycle', 'test_partial_eviction_reconciles_but_identity_swap_fails_closed', None),
        ('glm52', 'lifecycle', 'test_partial_hash_drift_at_delete_reports_state', None),
        ('glm52', 'lifecycle', 'test_path_escape_protected_target_refusal', None),
        ('glm52', 'lifecycle', 'test_pause_and_stop_directives_are_consumed_only_by_boundary', None),
        ('glm52', 'lifecycle', 'test_per_row_duplicate_fails_closed', None),
        ('glm52', 'lifecycle', 'test_persistent_run_refuses_missing_audit_before_first_heartbeat', None),
        ('glm52', 'lifecycle', 'test_phase_chain_rejects_anchor_predecessor_and_producer_replay', None),
        (
            'glm52',
            'lifecycle',
            'test_phase_receipts_are_explicitly_non_authoritative_and_public_eviction_refuses',
            None,
        ),
        ('glm52', 'lifecycle', 'test_plan_covers_math_and_both_live_prompts_without_execution', None),
        ('glm52', 'lifecycle', 'test_post_link_replacement_plus_directory_fsync_failure_preserves_foreign_file', None),
        ('glm52', 'lifecycle', 'test_poststream_prepublish_swapout_is_observed_before_any_visible_artifact', None),
        ('glm52', 'lifecycle', 'test_prepare_has_no_caller_facts_status_anchor_or_timestamp', None),
        ('glm52', 'lifecycle', 'test_production_writer_accepts_only_canonical_lowercase_json_and_is_one_use', None),
        ('glm52', 'lifecycle', 'test_provenance_covers_every_planner_input_and_runtime_lock', None),
        ('glm52', 'lifecycle', 'test_public_eviction_entry_point_remains_a_hard_blocker', None),
        ('glm52', 'lifecycle', 'test_public_validation_has_no_orphan_bypass', None),
        ('glm52', 'lifecycle', 'test_real_capsules_all_87_loaded_members_verified', None),
        ('glm52', 'lifecycle', 'test_real_shard_routed_expert_executes_and_matches_a_direct_pq_execute', None),
        ('glm52', 'lifecycle', 'test_real_utc_calendar_and_timestamp_order_are_enforced', None),
        ('glm52', 'lifecycle', 'test_receipt_binds_attempt_start_sequence_hash_and_both_telegram_identities', None),
        ('glm52', 'lifecycle', 'test_receipt_binds_exact_index_and_reconciles_tps', None),
        ('glm52', 'lifecycle', 'test_receipt_refuses_wrong_index_or_unreconciled_rate', None),
        ('glm52', 'lifecycle', 'test_reconcile_recovers_absence_after_durable_quarantine_event', None),
        ('glm52', 'lifecycle', 'test_refuse_non_exact_topk_member_path', None),
        ('glm52', 'lifecycle', 'test_refuse_non_topk_member_name', None),
        ('glm52', 'lifecycle', 'test_refuses_a_backend_result_of_the_wrong_shape', None),
        ('glm52', 'lifecycle', 'test_refuses_a_backend_that_does_not_declare_the_protocol', None),
        ('glm52', 'lifecycle', 'test_refuses_a_control_tensor_that_carries_no_packed_payload', None),
        ('glm52', 'lifecycle', 'test_refuses_a_file_that_is_not_a_gravity_shard', None),
        ('glm52', 'lifecycle', 'test_refuses_a_rate_claim_the_payload_bytes_do_not_support', None),
        ('glm52', 'lifecycle', 'test_refuses_a_rotated_geometry', None),
        ('glm52', 'lifecycle', 'test_refuses_a_rung_that_is_not_production_r0', None),
        ('glm52', 'lifecycle', 'test_refuses_a_shard_whose_format_version_is_newer_than_the_reader', None),
        ('glm52', 'lifecycle', 'test_refuses_a_tensor_that_cannot_fit_the_whole_byte_budget', None),
        ('glm52', 'lifecycle', 'test_refuses_an_absent_tensor_by_name', None),
        ('glm52', 'lifecycle', 'test_refuses_an_input_whose_length_disagrees_with_the_geometry', None),
        ('glm52', 'lifecycle', 'test_refuses_more_than_one_subspace', None),
        ('glm52', 'lifecycle', 'test_refuses_when_the_backend_vetoes_the_geometry', None),
        ('glm52', 'lifecycle', 'test_refuses_when_the_descriptor_element_count_disagrees_with_the_payload', None),
        ('glm52', 'lifecycle', 'test_refuses_when_the_descriptor_geometry_disagrees_with_the_payload', None),
        ('glm52', 'lifecycle', 'test_replaced_marker_is_never_overwritten_or_unlinked_at_finish', None),
        ('glm52', 'lifecycle', 'test_requested_rank_ne_total_rank_excluded_even_if_flag_wrong', None),
        ('glm52', 'lifecycle', 'test_resource_policy_requires_exact_contract_binding_and_frozen_floor', None),
        ('glm52', 'lifecycle', 'test_resource_receipt_must_match_exact_required_policy', None),
        ('glm52', 'lifecycle', 'test_retained_ledger_log_cache_survive', None),
        ('glm52', 'lifecycle', 'test_revision_0_hash_mismatch', None),
        ('glm52', 'lifecycle', 'test_route_row_indices', None),
        ('glm52', 'lifecycle', 'test_runtime_agreement_rejects_shape_and_nonfinite', None),
        ('glm52', 'lifecycle', 'test_runtime_agreement_requires_exact_discrete_and_continuous_bounds', None),
        ('glm52', 'lifecycle', 'test_runtime_timestamp_attack_aborts_active_stream_and_never_publishes', None),
        ('glm52', 'lifecycle', 'test_sample_timestamp_freshness_boundaries_are_exact', None),
        ('glm52', 'lifecycle', 'test_selftest_entry_point', None),
        ('glm52', 'lifecycle', 'test_selftest_entrypoint', None),
        ('glm52', 'lifecycle', 'test_signal_latch_wakes_persistent_wait_without_applying_mid_phase', None),
        ('glm52', 'lifecycle', 'test_signal_latches_until_boundary_then_emits_safe_stop_heartbeat', None),
        ('glm52', 'lifecycle', 'test_simulated_live_consumer', None),
        ('glm52', 'lifecycle', 'test_size_mismatch_shard', None),
        ('glm52', 'lifecycle', 'test_slow_cooperative_abort_records_quiescence_deadline_before_safe_return', None),
        ('glm52', 'lifecycle', 'test_source_grounding_rejects_missing_wrong_hash_and_same_size_corruption', None),
        ('glm52', 'lifecycle', 'test_sparse_schedule_and_direct_u8_names_cover_every_expert_stage', None),
        ('glm52', 'lifecycle', 'test_stale_baseline_timestamp_fails_before_any_stream_and_never_publishes', None),
        ('glm52', 'lifecycle', 'test_stale_measurement_receipt_binding', None),
        ('glm52', 'lifecycle', 'test_stale_xet_input_binding_is_rejected', None),
        ('glm52', 'lifecycle', 'test_state_gates_freeze_inputs_and_require_all_terminal_evidence', None),
        ('glm52', 'lifecycle', 'test_status_documents_logout_and_reboot_limitations', None),
        ('glm52', 'lifecycle', 'test_stream_start_and_all_coverage_crossings_come_from_window_ledger', None),
        ('glm52', 'lifecycle', 'test_summary_refuses_incomplete_rung', None),
        ('glm52', 'lifecycle', 'test_summary_requires_every_partition_and_every_answer', None),
        ('glm52', 'lifecycle', 'test_sustained_command_requests_curve_and_progress', None),
        ('glm52', 'lifecycle', 'test_swiglu_and_score_linear_no_gaussian', None),
        ('glm52', 'lifecycle', 'test_telegram_rotation_receipt_binds_live_distinct_keys', None),
        ('glm52', 'lifecycle', 'test_terminal_coverage_rejects_gaps_fake_billing_and_unjustified_omission', None),
        ('glm52', 'lifecycle', 'test_terminal_currentness_refuses_a_different_deterministic_rebuild', None),
        ('glm52', 'lifecycle', 'test_terminal_writer_revalidates_every_artifact_before_pass', None),
        ('glm52', 'lifecycle', 'test_the_backend_receives_the_decoded_codes_and_the_explicit_cache_key', None),
        ('glm52', 'lifecycle', 'test_the_cpu_reference_backend_matches_a_direct_pq_execute', None),
        ('glm52', 'lifecycle', 'test_top_level_run_execs_exact_caffeinate_argv_then_validates_child_path', None),
        ('glm52', 'lifecycle', 'test_traversal_is_rejected_for_contract_and_artifact_manifests', None),
        ('glm52', 'lifecycle', 'test_uncentered_differs_from_centered_when_mean_dominates', None),
        ('glm52', 'lifecycle', 'test_unsupported_and_premature_milestones_fail_closed', None),
        ('glm52', 'lifecycle', 'test_visibility_gate_rechecks_swap_immediately_before_atomic_rename', None),
        ('glm52', 'lifecycle', 'test_worker_authentication_role_check_requires_distinct_grounding_without_leak', None),
        ('glm52', 'lifecycle', 'test_worker_heartbeat_rejects_forged_hmac_and_identity', None),
        ('glm52', 'lifecycle', 'test_wrong_confirmation', None),
        ('glm52', 'preflight', 'test_no_process_probe_fail_closed', None),
        ('glm52', 'preflight', 'test_preflight_and_build_command_refuse_missing_rotated_digest', None),
        ('glm52', 'preflight', 'test_preflight_reports_each_production_blocker_without_side_effects', None),
        ('glm52', 'preflight', 'test_read_only_audit_performs_no_write_repair_anchor_or_send', None),
        ('glm52', 'preflight', 'test_read_only_audit_rejects_crash_gaps_without_recovery', None),
        ('glm52', 'preflight', 'test_read_only_audit_rejects_fifo_lock_and_controller_bound_head_rollback', None),
        ('glm52', 'preflight', 'test_read_only_audit_replays_exact_lifecycle_without_private_keys', None),
        ('glm52', 'preflight', 'test_status_is_read_only', None),
        ('glm52', 'reseal', 'test_attestation_rejects_semantically_tampered_raw_result', None),
        ('glm52', 'reseal', 'test_attested_result_rejects_changed_raw_seal_even_with_fresh_hmac', None),
        ('glm52', 'reseal', 'test_authenticated_worker_target_substitution_cannot_override_controller_file', None),
        ('glm52', 'reseal', 'test_contract_rejects_resealed_resource_policy_substitution', None),
        ('glm52', 'reseal', 'test_count_and_schedule_tampering_fail_even_when_resealed', None),
        ('glm52', 'reseal', 'test_derivation_is_deterministic_and_seal_detects_tamper', None),
        ('glm52', 'reseal', 'test_final_schedule_rejects_absent_tampered_and_arbitrary_xet_evidence', None),
        ('glm52', 'reseal', 'test_freeze_rejects_plan_and_preliminary_seal_substitution', None),
        ('glm52', 'reseal', 'test_malformed_sealed_array_hash_fails', None),
        ('glm52', 'reseal', 'test_matching_sealed_raw_array_hash_passes', None),
        ('glm52', 'reseal', 'test_mismatched_sealed_array_hash_fails', None),
        ('glm52', 'reseal', 'test_missing_sealed_array_hash_fails', None),
        ('glm52', 'reseal', 'test_official_contract_authority_uses_authenticated_runtime_bound_seal', None),
        ('glm52', 'reseal', 'test_omitted_or_unsealed_input_is_rejected', None),
        ('glm52', 'reseal', 'test_resealed_entry_tamper_and_clean_tail_truncation_fail', None),
        ('glm52', 'reseal', 'test_same_path_controller_reseal_and_root_redirection_is_rejected', None),
        ('glm52', 'reseal', 'test_sealed_capsule_hash_bound_not_file_hash', None),
        ('glm52', 'reseal', 'test_sealed_receipt_verifies_and_blocks_replay', None),
        ('glm52', 'reseal', 'test_signed_intent_target_substitution_and_refused_capability_write_nothing', None),
        ('glm52', 'reseal', 'test_stale_reseal_binding', None),
        ('glm52', 'reseal', 'test_tampered_frozen_audit_readiness_blocks_before_heartbeat', None),
        ('glm52', 'reseal', 'test_validate_rebuilds_and_rejects_resealed_substitution', None),
        ('glm52', 'reseal', 'test_validate_rejects_every_resealed_nested_shape_or_value_drift', None),
        ('glm52', 'reseal', 'test_validator_rejects_reauthenticated_final_schedule_tampering', None),
        ('glm52', 'reseal', 'test_window_seal_regrounds_every_prerequisite_artifact', None),
        ('glm52', 'reseal', 'test_worker_config_binds_exact_controller_bytes_seal_and_runtime_targets', None),
        ('glm52', 'reseal', 'test_worker_config_replacement_cannot_reseal_an_alternate_contract', None),
        ('glm52', 'session_mode', 'test_roles_are_ed25519_distinct_and_private_keys_do_not_enter_journal', None),
        ('glm52', 'spec_repro', 'test_adapter_source_inspection_rejects_noop_effects_and_test_eviction', None),
        ('glm52', 'spec_repro', 'test_final_schedule_reopens_semantic_xet_and_binds_controller_commit', None),
        ('glm52', 'spec_repro', 'test_source_passes_the_workers_own_registry_admission_inspector', None),
        ('glm52', 'spec_seal_run', 'test_allocator_dispositions_are_only_activation_aware_and_pass_through', None),
        (
            'glm52',
            'spec_seal_run',
            'test_allocator_dispositions_are_only_activation_aware_and_pass_through_root_surface',
            None,
        ),
        ('glm52', 'spec_seal_run', 'test_assemble_writes_index_openable_for_tensor_fetch', None),
        ('glm52', 'spec_seal_run', 'test_assembly_check_grades_official_map_not_packer_against_itself', None),
        ('glm52', 'spec_seal_run', 'test_bf16_pass_through_widening_is_little_endian_shift', None),
        ('glm52', 'spec_seal_run', 'test_bf16_pass_through_widening_is_little_endian_shift_root_surface', None),
        ('glm52', 'spec_seal_run', 'test_format_rejects_overlapping_payload_spans', None),
        ('glm52', 'spec_seal_run', 'test_format_source_executes_factorized_matvec_and_rows', None),
        ('glm52', 'spec_seal_run', 'test_payload_level_serialize_deserialize_roundtrip_both_sides', None),
        ('glm52', 'spec_seal_run', 'test_payload_level_serialize_deserialize_roundtrip_both_sides_root_surface', None),
        ('glm52', 'spec_seal_run', 'test_roundtrip_writer_reader_preserves_shape_dtype_and_values', None),
        ('glm52', 'spec_seal_run', 'test_roundtrip_writer_reader_preserves_shape_dtype_and_values_root_surface', None),
        ('glm52', 'spec_seal_run', 'test_shard_hash_binds_runtime_bytes', None),
        ('glm52', 'spec_seal_run', 'test_validate_payload_magics_accepts_clean_and_rejects_corrupt', None),
        ('glm52', 'spec_seal_run', 'test_validate_payload_magics_accepts_clean_and_rejects_corrupt_root_surface', None),
        ('glm52', 'spec_seal_run', 'test_zero_byte_descriptor_counts_as_missing_not_complete', None),
        ('gptoss', 'checkpoint', 'test_delivery_is_idempotent', None),
        ('gptoss', 'lifecycle', 'test_7b_result_is_bad_but_exposes_speed_only_headroom', None),
        ('gptoss', 'lifecycle', 'test_all_disposition_format_is_unavailable', None),
        ('gptoss', 'lifecycle', 'test_classify_result_branches', None),
        ('gptoss', 'lifecycle', 'test_cli_dry_run', None),
        ('gptoss', 'lifecycle', 'test_cli_writes_to_out_dir', None),
        ('gptoss', 'lifecycle', 'test_decision_is_bad_and_not_optimizable_when_quality_misses', None),
        ('gptoss', 'lifecycle', 'test_decision_is_good_when_one_branch_passes_quality_floor', None),
        ('gptoss', 'lifecycle', 'test_emits_all_eight_artifacts', None),
        ('gptoss', 'lifecycle', 'test_eta_block_renders_blocked_reason_and_count', None),
        ('gptoss', 'lifecycle', 'test_eta_block_renders_through_120b_gated_reason', None),
        ('gptoss', 'lifecycle', 'test_eta_block_renders_through_120b_point', None),
        ('gptoss', 'lifecycle', 'test_evidence_classification_valid_and_present', None),
        ('gptoss', 'lifecycle', 'test_exact_four_branch_rung_is_detected_once', None),
        ('gptoss', 'lifecycle', 'test_horizon_lines_dropped_before_truncation', None),
        ('gptoss', 'lifecycle', 'test_horizon_lines_marked_planning_projection', None),
        ('gptoss', 'lifecycle', 'test_incomplete_branch_prevents_rung', None),
        ('gptoss', 'lifecycle', 'test_keychain_values_never_enter_launch_arguments', None),
        ('gptoss', 'lifecycle', 'test_missing_g4_degrades_gracefully', None),
        ('gptoss', 'lifecycle', 'test_mixed_format_scopes_result_to_measured_branches', None),
        ('gptoss', 'lifecycle', 'test_mixed_terminal_rung_is_evidence_validated', None),
        ('gptoss', 'lifecycle', 'test_next_rung_falls_back_to_campaign_rates_when_observer_blocked', None),
        ('gptoss', 'lifecycle', 'test_next_rung_skips_mixed_terminal_rung', None),
        ('gptoss', 'lifecycle', 'test_next_rung_uses_remaining_branch_work', None),
        ('gptoss', 'lifecycle', 'test_no_inversion_when_proxy_direction_holds', None),
        ('gptoss', 'lifecycle', 'test_organ_sensitivity_inversion_detected', None),
        ('gptoss', 'lifecycle', 'test_pareto_structure_prunes_only_strictly_dominated_branches', None),
        ('gptoss', 'lifecycle', 'test_provisional_when_campaign_not_final', None),
        ('gptoss', 'lifecycle', 'test_quality_only_pass_is_bad_but_has_optimization_headroom', None),
        ('gptoss', 'lifecycle', 'test_rehydration_receipt_has_seven_shards_and_route', None),
        ('gptoss', 'lifecycle', 'test_resource_and_runtime_atlases', None),
        ('gptoss', 'lifecycle', 'test_running_block_precedes_canonical_incomplete_rung', None),
        ('gptoss', 'lifecycle', 'test_salvage_confidence_on_every_prior', None),
        ('gptoss', 'lifecycle', 'test_simple_format_has_decision_and_eta_block', None),
        ('gptoss', 'reseal', 'test_final_when_campaign_sealed_and_g4_present', None),
        ('gptoss', 'reseal', 'test_state_seal_rejects_tampering', None),
        ('gptoss', 'reseal', 'test_tampered_disposition_artifact_fails_closed', None),
        ('gptoss', 'reseal', 'test_tampered_disposition_fails_closed', None),
        ('gptoss', 'reseal', 'test_tampered_result_fails_closed', None),
        ('gravity_frontier', 'checkpoint', 'test_campaign_alive_no_resume', None),
        ('gravity_frontier', 'checkpoint', 'test_campaign_crash_auto_resumes', None),
        ('gravity_frontier', 'checkpoint', 'test_exact_private_crash_temp_does_not_brick_journal', None),
        ('gravity_frontier', 'fences_run', 'test_reverify_gates_fresh_authorized', None),
        ('gravity_frontier', 'lease', 'test_03_source_mapped_refuses_release', None),
        ('gravity_frontier', 'lease', 'test_bootstrap_requires_explicit_release_authorization_flag', None),
        ('gravity_frontier', 'lease', 'test_campaign_missing_lease_resumes', None),
        ('gravity_frontier', 'lease', 'test_release_authorization_is_private_durable_and_head_bound', None),
        ('gravity_frontier', 'lease', 'test_release_refuses_unsafe_paths', None),
        ('gravity_frontier', 'lease', 'test_release_success_deletes_only_shards', None),
        ('gravity_frontier', 'lifecycle', 'test_01_successful_120b_completion_verifies', None),
        ('gravity_frontier', 'lifecycle', 'test_04_deletion_gate_red_refuses', None),
        ('gravity_frontier', 'lifecycle', 'test_05_interrupted_deletion_is_restart_safe', None),
        ('gravity_frontier', 'lifecycle', 'test_07_disk_floor_hardstop_and_pause', None),
        ('gravity_frontier', 'lifecycle', 'test_08_restart_during_every_state', None),
        ('gravity_frontier', 'lifecycle', 'test_09_claim_dedups_telegram_but_never_wedges_advance', None),
        ('gravity_frontier', 'lifecycle', 'test_10_q2_failure_blocks', None),
        ('gravity_frontier', 'lifecycle', 'test_11_successful_qwen_ignition_path', None),
        ('gravity_frontier', 'lifecycle', 'test_allocation_serializes', None),
        ('gravity_frontier', 'lifecycle', 'test_budget_below_floor_raises', None),
        ('gravity_frontier', 'lifecycle', 'test_bytes_concentrate_on_high_utility_organs', None),
        ('gravity_frontier', 'lifecycle', 'test_bytes_strictly_increase_with_rate', None),
        ('gravity_frontier', 'lifecycle', 'test_campaign_baseline_is_not_reset_between_actions', None),
        ('gravity_frontier', 'lifecycle', 'test_controller_waits_for_existing_generate_without_spawning', None),
        ('gravity_frontier', 'lifecycle', 'test_demo_runs_green', None),
        ('gravity_frontier', 'lifecycle', 'test_durable_store_repairs_snapshot_from_atomic_journal', None),
        ('gravity_frontier', 'lifecycle', 'test_executor_requires_exact_official_remote_head_and_pinned_files', None),
        ('gravity_frontier', 'lifecycle', 'test_generous_budget_pushes_organs_up_but_never_over', None),
        ('gravity_frontier', 'lifecycle', 'test_greedy_strictly_beats_uniform_somewhere', None),
        ('gravity_frontier', 'lifecycle', 'test_greedy_weakly_dominates_uniform', None),
        ('gravity_frontier', 'lifecycle', 'test_linked_worktree_is_rejected_as_emergency_executor', None),
        ('gravity_frontier', 'lifecycle', 'test_low_frequency_experts_get_no_more_than_frequent', None),
        ('gravity_frontier', 'lifecycle', 'test_marginal_utility_per_bit_non_increasing_up_to_rounding', None),
        ('gravity_frontier', 'lifecycle', 'test_marginal_utility_zero_when_no_bits_added', None),
        ('gravity_frontier', 'lifecycle', 'test_metadata_charge_is_never_free', None),
        ('gravity_frontier', 'lifecycle', 'test_operation_roots_default_to_clean_executor', None),
        ('gravity_frontier', 'lifecycle', 'test_organ_records_all_prior_fields', None),
        ('gravity_frontier', 'lifecycle', 'test_origin_url_mismatch_fails_closed', None),
        ('gravity_frontier', 'lifecycle', 'test_pid_reuse_is_never_signalled_or_treated_as_controller_child', None),
        ('gravity_frontier', 'lifecycle', 'test_pinned_organs_are_source_native', None),
        ('gravity_frontier', 'lifecycle', 'test_plist_is_caffeinated_and_does_not_touch_overnight_plist', None),
        ('gravity_frontier', 'lifecycle', 'test_quality_curve_concave_in_rate', None),
        ('gravity_frontier', 'lifecycle', 'test_quality_curve_monotone_and_bounded', None),
        ('gravity_frontier', 'lifecycle', 'test_remote_head_mismatch_fails_closed', None),
        ('gravity_frontier', 'lifecycle', 'test_replacement_capsule_status_is_accepted_without_terminal_block', None),
        ('gravity_frontier', 'lifecycle', 'test_resource_parsers_and_zero_growth_policy', None),
        (
            'gravity_frontier',
            'lifecycle',
            'test_sampler_failure_stops_exact_restarted_child_and_retains_watchdog_state',
            None,
        ),
        ('gravity_frontier', 'lifecycle', 'test_sensitive_mlp2_protected_at_least_as_much_as_robust_mlp1', None),
        ('gravity_frontier', 'lifecycle', 'test_sensitive_organ_curve_below_robust_at_low_rate', None),
        ('gravity_frontier', 'lifecycle', 'test_source_contains_no_delete_implementation', None),
        (
            'gravity_frontier',
            'lifecycle',
            'test_spawn_gap_reconciliation_recovers_exact_live_child_without_duplicate',
            None,
        ),
        ('gravity_frontier', 'lifecycle', 'test_taxonomy_covers_required_classes', None),
        ('gravity_frontier', 'lifecycle', 'test_unfinalized_operation_hash_pins_refuse_before_git', None),
        ('gravity_frontier', 'lifecycle', 'test_verified_executor_head_must_remain_bootstrap_head', None),
        ('gravity_frontier', 'preflight', 'test_post_bootstrap_executor_verification_needs_no_network', None),
        ('gravity_frontier', 'reseal', 'test_02_invalid_seal_fails_verification', None),
        ('gravity_frontier', 'reseal', 'test_12_qwen_controller_self_heal_and_seal', None),
        ('gravity_frontier', 'reseal', 'test_journal_chain_tamper_fails_closed', None),
        ('gravity_frontier', 'session_mode', 'test_recovery_process_detection_requires_exact_session', None),
        ('gravity_frontier', 'spec_repro', 'test_06_interrupted_qwen_download_retries_and_respects_floors', None),
        ('gravity_frontier', 'spec_repro', 'test_greedy_respects_budget', None),
        (
            'gravity_frontier',
            'spec_seal_run',
            'test_attention_geometry_is_unstageable_whole_but_stageable_per_block',
            None,
        ),
        ('gravity_frontier', 'spec_seal_run', 'test_b7_verdict_has_a_noise_band_so_a_wobble_is_not_a_win', None),
        ('gravity_frontier', 'spec_seal_run', 'test_blocks_one_has_no_partial_traffic', None),
        ('gravity_frontier', 'spec_seal_run', 'test_blocks_one_skips_the_reduce_dispatch', None),
        ('gravity_frontier', 'spec_seal_run', 'test_chunk_blocks_cover_every_chunk', None),
        (
            'gravity_frontier',
            'spec_seal_run',
            'test_dispatch_matches_the_cpu_authority_for_every_compiled_variant',
            None,
        ),
        ('gravity_frontier', 'spec_seal_run', 'test_dispatch_refuses_an_x_of_the_wrong_length', None),
        (
            'gravity_frontier',
            'spec_seal_run',
            'test_every_kernel_the_planner_can_name_exists_in_the_metal_source',
            None,
        ),
        ('gravity_frontier', 'spec_seal_run', 'test_in_kernel_unpack_matches_the_packer_at_every_bit_phase', None),
        (
            'gravity_frontier',
            'spec_seal_run',
            'test_kernel_name_matches_the_realised_staging_not_the_requested_one',
            None,
        ),
        ('gravity_frontier', 'spec_seal_run', 'test_module_never_writes_to_the_live_artifact_directory', None),
        (
            'gravity_frontier',
            'spec_seal_run',
            'test_not_staging_x_at_the_attention_geometry_bills_the_whole_activation_per_thread',
            None,
        ),
        ('gravity_frontier', 'spec_seal_run', 'test_plan_rejects_nonsense', None),
        ('gravity_frontier', 'spec_seal_run', 'test_reassociation_alone_does_not_move_the_answer_past_the_gate', None),
        ('gravity_frontier', 'spec_seal_run', 'test_scratch_never_exceeds_the_threadgroup_limit', None),
        ('gravity_frontier', 'spec_seal_run', 'test_seven_bit_stream_is_one_eighth_smaller_than_the_uint8_one', None),
        (
            'gravity_frontier',
            'spec_seal_run',
            'test_split_reduce_matches_the_cpu_authority_within_the_fp16_codebook_floor',
            None,
        ),
        ('gravity_frontier', 'spec_seal_run', 'test_split_widens_the_grid_instead_of_repackaging_it', None),
        ('gravity_frontier', 'spec_seal_run', 'test_stage_x_off_is_recorded_as_requested_off_not_as_a_refusal', None),
        ('gravity_frontier', 'spec_seal_run', 'test_unique_bytes_never_exceed_the_re_read_upper_bound', None),
        ('gravity_frontier', 'spec_seal_run', 'test_unpack_window_never_reads_past_the_padded_allocation', None),
        ('gravity_frontier', 'spec_seal_run', 'test_vec4_is_refused_when_D_is_not_a_multiple_of_four', None),
        ('kimi_k26', 'checkpoint', 'test_completed_generate_is_idempotent_and_runs_no_second_child', None),
        ('kimi_k26', 'checkpoint', 'test_exact_partial_capsule_resumes_without_overwrite', None),
        ('kimi_k26', 'checkpoint', 'test_fault_after_unlink_is_journaled_and_retry_receipt_binds_original_set', None),
        ('kimi_k26', 'checkpoint', 'test_hard_crash_after_unlink_before_commit_reconciles_truthfully', None),
        ('kimi_k26', 'checkpoint', 'test_replacement_capsule_population_crash_is_invisible_and_retryable', None),
        ('kimi_k26', 'checkpoint', 'test_resource_guard_terminates_then_kills_and_preserves_resume_cache', None),
        ('kimi_k26', 'checkpoint', 'test_resume_credits_more_than_initial_margin_of_existing_session_bytes', None),
        ('kimi_k26', 'fences_run', 'test_live_shaped_frozen_corpus_source_authority_is_accepted', None),
        ('kimi_k26', 'fences_run', 'test_production_cli_rejects_authority_redefinition', None),
        ('kimi_k26', 'launcher', 'test_inventory_blocks_mop_symlink_and_path_overlap', None),
        ('kimi_k26', 'launcher', 'test_layout_rejects_nonprivate_scratch_mode', None),
        ('kimi_k26', 'launcher', 'test_layout_rejects_symlinked_component', None),
        ('kimi_k26', 'launcher', 'test_layout_rejects_symlinked_scratch_root', None),
        ('kimi_k26', 'launcher', 'test_local_git_loader_rejects_wrong_tree_or_mode', None),
        ('kimi_k26', 'launcher', 'test_real_system_git_binding_accepts_exact_ssv_hardlinks', None),
        ('kimi_k26', 'launcher', 'test_runtime_builder_rejects_unsafe_hf_launcher_node', None),
        ('kimi_k26', 'launcher', 'test_source_verifier_accepts_exact_dedicated_symlink_snapshot', None),
        ('kimi_k26', 'launcher', 'test_source_verifier_rejects_hardlinked_blob', None),
        ('kimi_k26', 'launcher', 'test_source_verifier_rejects_symlink_escape', None),
        ('kimi_k26', 'launcher', 'test_symlink_swap_never_touches_external_victim', None),
        ('kimi_k26', 'launcher', 'test_zip_symlink_member_is_rejected', None),
        ('kimi_k26', 'lease', 'test_cleanup_requires_exact_lease_no_unfinished_child_and_clean_process_audit', None),
        ('kimi_k26', 'lease', 'test_cli_exposes_no_download_delete_or_release_execution_command', None),
        ('kimi_k26', 'lease', 'test_exact_release_deletes_only_weights_and_xet_and_seals_receipt', None),
        ('kimi_k26', 'lease', 'test_exclusive_lease_refuses_concurrent_run_before_popen', None),
        ('kimi_k26', 'lease', 'test_held_download_lease_blocks_before_revalidation_or_delete', None),
        ('kimi_k26', 'lease', 'test_inventory_deduplicates_hardlinks_and_blocks_release', None),
        ('kimi_k26', 'lease', 'test_module_has_no_source_release_primitives', None),
        ('kimi_k26', 'lease', 'test_pre_release_audit_blocks_lsof_process_and_queue', None),
        ('kimi_k26', 'lease', 'test_pre_release_audit_passes_only_clean_inventory_readers_processes_and_queues', None),
        ('kimi_k26', 'lease', 'test_strict_replacement_capsule_is_release_compatible', None),
        ('kimi_k26', 'lifecycle', 'test_audit_rejects_unknown_or_noncanonical_incomplete_name', None),
        ('kimi_k26', 'lifecycle', 'test_auto_discovered_seed_builds_honest_replacement_without_mutating_seed', None),
        ('kimi_k26', 'lifecycle', 'test_capsule_mutation_during_final_inventory_blocks_before_journal_start', None),
        ('kimi_k26', 'lifecycle', 'test_cleanup_source_has_only_exact_dirfd_unlink_and_no_broad_removal', None),
        ('kimi_k26', 'lifecycle', 'test_download_plan_is_exact_dedicated_and_inert', None),
        ('kimi_k26', 'lifecycle', 'test_every_required_audit_blocker_prevents_confirmation', None),
        ('kimi_k26', 'lifecycle', 'test_exact_payload_result_capture_verifier', None),
        ('kimi_k26', 'lifecycle', 'test_execute_refuses_inode_or_mtime_change_after_confirmation', None),
        ('kimi_k26', 'lifecycle', 'test_fast_measured_transfer_does_not_ramp', None),
        ('kimi_k26', 'lifecycle', 'test_fault_after_n_unlinks_has_durable_partial_receipt_and_reconciles', None),
        ('kimi_k26', 'lifecycle', 'test_frozen_corpus_rejects_nonexact_source_fields', None),
        ('kimi_k26', 'lifecycle', 'test_frozen_semantic_verifier_rejects_material_change', None),
        ('kimi_k26', 'lifecycle', 'test_generate_parser_supports_optional_seed_without_controller_change', None),
        ('kimi_k26', 'lifecycle', 'test_incomplete_appearing_at_final_boundary_blocks_before_popen', None),
        ('kimi_k26', 'lifecycle', 'test_incomplete_transfer_blob_is_never_a_weight_target_and_blocks', None),
        ('kimi_k26', 'lifecycle', 'test_incomplete_transfer_blocks_before_generation', None),
        ('kimi_k26', 'lifecycle', 'test_inventory_is_exact_64_weights_32_metadata_and_xet', None),
        ('kimi_k26', 'lifecycle', 'test_journal_refuses_append_before_crossing_replay_bound', None),
        ('kimi_k26', 'lifecycle', 'test_local_git_loader_uses_only_exact_cat_file_allowlist', None),
        ('kimi_k26', 'lifecycle', 'test_missing_phase1_ramp_profile_never_derives_an_unplanned_command', None),
        ('kimi_k26', 'lifecycle', 'test_module_contains_no_glob_or_recursive_delete_primitive', None),
        ('kimi_k26', 'lifecycle', 'test_native_auditor_matches_exact_structured_tokens_not_substrings', None),
        ('kimi_k26', 'lifecycle', 'test_no_delete_api_and_cli_has_only_three_commands', None),
        ('kimi_k26', 'lifecycle', 'test_old_898063_archive_is_explicitly_rejected', None),
        ('kimi_k26', 'lifecycle', 'test_post_start_sampler_fault_stops_child_and_closes_durable_lifecycle', None),
        ('kimi_k26', 'lifecycle', 'test_preexec_process_conflict_fails_before_runtime_or_popen', None),
        ('kimi_k26', 'lifecycle', 'test_probe_time_same_size_retained_metadata_mutation_blocks_zero_delete', None),
        ('kimi_k26', 'lifecycle', 'test_ramp_uses_only_post_warmup_measurement_window', None),
        ('kimi_k26', 'lifecycle', 'test_real_frozen_manifest_and_archive_verify', None),
        ('kimi_k26', 'lifecycle', 'test_recovery_extractor_refuses_overwrite_and_unlisted_entry', None),
        ('kimi_k26', 'lifecycle', 'test_recovery_extracts_only_explicit_text_allowlist', None),
        ('kimi_k26', 'lifecycle', 'test_replacement_capsule_atomic_publish_never_overwrites_racing_destination', None),
        ('kimi_k26', 'lifecycle', 'test_replacement_capsule_is_fsynced_then_atomically_published', None),
        ('kimi_k26', 'lifecycle', 'test_replay_projection_uses_the_exact_pinned_dynamic_marker', None),
        ('kimi_k26', 'lifecycle', 'test_resource_guard_detects_external_consumption_of_remaining_capacity', None),
        ('kimi_k26', 'lifecycle', 'test_resource_guarded_ramp_requires_exact_cleanup_receipt_for_direct_16', None),
        ('kimi_k26', 'lifecycle', 'test_strict_json_rejects_duplicate_keys_and_nan', None),
        ('kimi_k26', 'lifecycle', 'test_sustained_low_measured_transfer_serially_restarts_at_16', None),
        ('kimi_k26', 'lifecycle', 'test_two_phase_exact_cleanup_preserves_final_blob_and_xet', None),
        ('kimi_k26', 'lifecycle', 'test_unsafe_or_unverified_replacement_capsule_is_rejected', None),
        ('kimi_k26', 'lifecycle', 'test_wrong_bracket_binary_prevents_doctor_and_capsule', None),
        ('kimi_k26', 'lifecycle', 'test_wrong_confirmation_token_writes_and_deletes_nothing', None),
        ('kimi_k26', 'lifecycle', 'test_wrong_doctor_binary_leaves_capsule_untouched', None),
        ('kimi_k26', 'lifecycle', 'test_wrong_existing_capsule_is_never_overwritten', None),
        ('kimi_k26', 'lifecycle', 'test_zip_slip_names_are_rejected', None),
        ('kimi_k26', 'preflight', 'test_extracts_only_three_frozen_records_and_verify_is_read_only', None),
        ('kimi_k26', 'preflight', 'test_phase1_preflight_is_deterministic_and_never_calls_subprocess', None),
        ('kimi_k26', 'preflight', 'test_preflight_and_status_start_no_process_or_network_and_write_nothing', None),
        ('kimi_k26', 'preflight', 'test_preflight_enforces_exact_capacity_floor', None),
        ('kimi_k26', 'preflight', 'test_preflight_is_read_only_and_binds_six_blobs', None),
        ('kimi_k26', 'reseal', 'test_archive_hash_substitution_is_rejected', None),
        ('kimi_k26', 'reseal', 'test_blob_substitution_after_audit_blocks_before_any_unlink', None),
        ('kimi_k26', 'reseal', 'test_clean_prior_measured_ramp_resumes_directly_at_sealed_16', None),
        ('kimi_k26', 'reseal', 'test_inventory_seal_and_allocated_sum_detect_substitution', None),
        ('kimi_k26', 'reseal', 'test_manifest_rejects_resealed_substitution', None),
        ('kimi_k26', 'reseal', 'test_payload_hash_substitution_and_hardlink_are_rejected', None),
        ('kimi_k26', 'reseal', 'test_preflight_rejects_resealed_plan_substitution_and_missing_tmp', None),
        ('kimi_k26', 'reseal', 'test_resealed_cross_bundle_substitution_is_rejected', None),
        ('kimi_k26', 'reseal', 'test_resealed_native_xet_artifact_substitution_is_rejected', None),
        ('kimi_k26', 'reseal', 'test_resealed_runtime_binding_substitutions_are_rejected', None),
        ('kimi_k26', 'reseal', 'test_resealed_transfer_pin_substitution_is_rejected', None),
        ('kimi_k26', 'reseal', 'test_run_uses_only_exact_pinned_child_contract_and_seals_evidence', None),
        ('kimi_k26', 'reseal', 'test_source_verifier_rejects_blob_identity_substitution', None),
        ('kimi_k26', 'reseal', 'test_status_replays_hash_chain_and_rejects_tamper', None),
        ('kimi_k26', 'reseal', 'test_tampered_historical_blob_blocks_before_export_or_process', None),
        ('kimi_k26', 'session_mode', 'test_generate_uses_private_export_sandbox_and_exact_capsule', None),
        ('kimi_k26', 'session_mode', 'test_init_session_is_private_and_has_no_live_capability', None),
        ('kimi_k26', 'session_mode', 'test_init_session_rejects_unsafe_ids', None),
        ('kimi_k26', 'session_mode', 'test_layout_rejects_missing_scratch_root', None),
        ('mechanics', 'lifecycle', 'test_b0_b1_m1_all_execute_same_recon', None),
        ('mechanics', 'lifecycle', 'test_b1_cpu_metal_parity', None),
        ('mechanics', 'lifecycle', 'test_deterministic_same_seed', None),
        ('mechanics', 'lifecycle', 'test_m1_batch_matches_b1_batch', None),
        ('mechanics', 'lifecycle', 'test_m1_cpu_metal_parity', None),
        ('mechanics', 'lifecycle', 'test_m1_equals_b1_same_artifact', None),
        ('mechanics', 'lifecycle', 'test_m1_reads_less_than_full_dense_bytes', None),
        ('mechanics', 'lifecycle', 'test_mech_vector_does_not_hide_arithmetic_in_lookups', None),
        ('mechanics', 'lifecycle', 'test_mech_vector_populated_and_labelled', None),
        ('mechanics', 'lifecycle', 'test_module_selftest_green', None),
        ('mechanics', 'lifecycle', 'test_no_dense_shadow_bounded_temporary', None),
        ('mechanics', 'lifecycle', 'test_quality_parity_matches_dense_definition', None),
        ('mechanics', 'reseal', 'test_seal_roundtrip_self_sha256', None),
        ('mechanics', 'spec_seal_run', 'test_M2_runs_and_measured', None),
        ('mechanics', 'spec_seal_run', 'test_M3_M4_M5_M6_run_and_measured', None),
        ('mechanics', 'spec_seal_run', 'test_cluster_ledger_shared_cheaper_than_independent', None),
        ('mechanics', 'spec_seal_run', 'test_conditional_false_negative_gate_fires', None),
        ('mechanics', 'spec_seal_run', 'test_deterministic_same_seed', None),
        ('mechanics', 'spec_seal_run', 'test_fake_win_ban_candidate_marked_inadmissible', None),
        ('mechanics', 'spec_seal_run', 'test_islands_are_billed_and_increase_bytes', None),
        ('mechanics', 'spec_seal_run', 'test_module_selftest_green', None),
        ('mechanics', 'spec_seal_run', 'test_no_dense_shadow_M2_through_M6', None),
        ('mechanics', 'spec_seal_run', 'test_pareto_champions_present', None),
        ('mechanics', 'spec_seal_run', 'test_pareto_excludes_dominated_and_dense', None),
        ('mechanics', 'spec_seal_run', 'test_quality_gate_rejects_lower_quality', None),
        ('mechanics', 'spec_seal_run', 'test_staged_execution_matches_frozen_shared_grammar', None),
        ('qwen', 'launcher', 'test_expert_organ_allocation_is_below_target_but_not_mislabeled_whole_model', None),
        ('qwen', 'launcher', 'test_whole_model_plan_reaches_120b_rate_without_hiding_nonexperts', None),
        ('qwen', 'lease', 'test_lease_claim_refuse_and_checkpoint', None),
        ('qwen', 'lease', 'test_other_heavy_lease_blocks_claim', None),
        ('qwen', 'lifecycle', 'test_bf16_rows_matches_full_gather', None),
        ('qwen', 'lifecycle', 'test_bounded_read_executes_on_synthetic_shard', None),
        ('qwen', 'lifecycle', 'test_bounded_read_stub_untested_pending_source', None),
        ('qwen', 'lifecycle', 'test_candidates_enumerate_over_three_qwen_classes', None),
        ('qwen', 'lifecycle', 'test_classify_all_organ_classes', None),
        ('qwen', 'lifecycle', 'test_classify_rejects_garbage', None),
        ('qwen', 'lifecycle', 'test_control_and_baseline_families', None),
        ('qwen', 'lifecycle', 'test_expected_shapes', None),
        ('qwen', 'lifecycle', 'test_expert_hook_is_called_and_changes_output', None),
        ('qwen', 'lifecycle', 'test_forge_pack_family_shape_and_bpw', None),
        ('qwen', 'lifecycle', 'test_forge_pack_rejects_unknown_family', None),
        ('qwen', 'lifecycle', 'test_forward_is_deterministic', None),
        ('qwen', 'lifecycle', 'test_forward_shapes_and_finiteness', None),
        ('qwen', 'lifecycle', 'test_geometry_decoupled_head_dim', None),
        ('qwen', 'lifecycle', 'test_nll_and_perplexity', None),
        ('qwen', 'lifecycle', 'test_qk_norm_detected_and_partial_blocks', None),
        ('qwen', 'lifecycle', 'test_reader_roundtrips_bf16_and_maps_shards', None),
        ('qwen', 'lifecycle', 'test_real_architecture', None),
        ('qwen', 'lifecycle', 'test_real_bounded_read_pending', None),
        ('qwen', 'lifecycle', 'test_real_grand_total_235b_438gib', None),
        ('qwen', 'lifecycle', 'test_real_meta_geometry_targets_qwen3_moe', None),
        ('qwen', 'lifecycle', 'test_real_name_scheme', None),
        ('qwen', 'lifecycle', 'test_real_shard_plan_and_counts', None),
        ('qwen', 'lifecycle', 'test_real_source_is_untested_pending_source', None),
        ('qwen', 'lifecycle', 'test_remote_forward_matches_local_forward', None),
        ('qwen', 'lifecycle', 'test_remote_reader_uses_exact_ranges_and_cache', None),
        ('qwen', 'lifecycle', 'test_rope_is_norm_preserving_and_identity_at_pos0', None),
        ('qwen', 'lifecycle', 'test_router_softmax_first_topk_and_renorm', None),
        ('qwen', 'lifecycle', 'test_rows_are_decisive_first_and_unique', None),
        ('qwen', 'lifecycle', 'test_standard_swiglu_differs_from_gptoss_clamped_gate', None),
        ('qwen', 'lifecycle', 'test_synthetic_inventory_and_cross_check', None),
        ('qwen', 'lifecycle', 'test_synthetic_name_verification', None),
        ('qwen', 'lifecycle', 'test_synthetic_name_verification_detects_missing', None),
        ('qwen', 'lifecycle', 'test_topk_rejects_bad_k', None),
        ('qwen', 'lifecycle', 'test_topk_routing_shape', None),
        ('qwen', 'lifecycle', 'test_vulture_champion_fallback_when_priors_absent', None),
        ('qwen', 'lifecycle', 'test_vulture_champion_maps_gateup_together_down_distinct', None),
        ('qwen', 'reseal', 'test_source_absent_seals_waiting_source', None),
        ('succession', 'checkpoint', 'test_event_chain_and_resume', None),
        ('succession', 'checkpoint', 'test_split_brain_resume_refused', None),
        ('succession', 'checkpoint', 'test_state_survives_crash_resume', None),
        ('succession', 'fences_run', 'test_giant_adapter_contracts_stable_and_composed_from_authority', None),
        ('succession', 'fences_run', 'test_physical_impossibility_authorizes_ascent', None),
        ('succession', 'lifecycle', 'test_block0_forward_shapes_and_rmsnorm', None),
        ('succession', 'lifecycle', 'test_forge_program_carries_required_section8_fields', None),
        ('succession', 'lifecycle', 'test_pre_run_readiness_receipt_is_derived_not_static', None),
        ('succession', 'lifecycle', 'test_all_required_commands_are_dispatched', None),
        ('succession', 'lifecycle', 'test_no_documented_command_missing_from_parser', None),
        ('succession', 'lifecycle', 'test_parser_accepts_every_command', None),
        ('succession', 'lifecycle', 'test_unknown_command_rejected', None),
        ('succession', 'lifecycle', 'test_default_rows_are_honestly_blocked', None),
        ('succession', 'lifecycle', 'test_engine_selftest', 'TestSuccCore.test_engine_selftest'),
        ('succession', 'lifecycle', 'test_events_selftest', None),
        ('succession', 'lifecycle', 'test_full_lifecycle_waits_then_imports', None),
        ('succession', 'lifecycle', 'test_heavy_dispatch_is_gated', None),
        ('succession', 'lifecycle', 'test_illegal_transition_refused', None),
        ('succession', 'lifecycle', 'test_invalid_status_refused', None),
        ('succession', 'lifecycle', 'test_queue_selftest', None),
        ('succession', 'lifecycle', 'test_state_selftest', None),
        ('succession', 'lifecycle', 'test_unbound_program_fails_validation', None),
        ('succession', 'lifecycle', 'test_classification_never_conflates_deferral_with_collapse', None),
        ('succession', 'lifecycle', 'test_engine_skips_retired_experiments', None),
        ('succession', 'lifecycle', 'test_eta_observations_are_per_segment_not_global', None),
        ('succession', 'lifecycle', 'test_harvest_selftest', None),
        ('succession', 'lifecycle', 'test_retire_selftest', None),
        ('succession', 'lifecycle', 'test_arm_frontier_is_launch_gated', None),
        ('succession', 'lifecycle', 'test_cannot_become_second_heavy_controller', None),
        ('succession', 'lifecycle', 'test_cannot_finalize_above_one_bpw_without_receipt', None),
        ('succession', 'lifecycle', 'test_collapse_triggers_ascent', None),
        ('succession', 'lifecycle', 'test_default_off_until_all_gates', None),
        ('succession', 'lifecycle', 'test_doctor_bytes_counted_in_whole', None),
        ('succession', 'lifecycle', 'test_duplicate_heavy_launch_refused', None),
        ('succession', 'lifecycle', 'test_engine_selftest', 'TestSuccGravity.test_engine_selftest'),
        ('succession', 'lifecycle', 'test_exact_rational_identity', None),
        ('succession', 'lifecycle', 'test_f0_f2_cannot_masquerade_as_f4', None),
        ('succession', 'lifecycle', 'test_failed_scalar_codec_not_justification', None),
        ('succession', 'lifecycle', 'test_finalize_extreme_gate_refuses_unjustified', None),
        ('succession', 'lifecycle', 'test_gravity_bonus_pulls_toward_subbit', None),
        ('succession', 'lifecycle', 'test_gravity_daily_summary_fields', None),
        ('succession', 'lifecycle', 'test_gravity_notifications_compose', None),
        ('succession', 'lifecycle', 'test_missing_experiment_not_justification', None),
        ('succession', 'lifecycle', 'test_no_conflicting_parent_identities', None),
        ('succession', 'lifecycle', 'test_pass_triggers_descent', None),
        ('succession', 'lifecycle', 'test_physically_impossible_candidate_penalized', None),
        ('succession', 'lifecycle', 'test_policy_selftest', None),
        ('succession', 'lifecycle', 'test_queue_and_telegram_survive_restart', None),
        ('succession', 'lifecycle', 'test_real_parent_defers_subbit_no_false_floor', None),
        ('succession', 'lifecycle', 'test_receipts_selftest', None),
        ('succession', 'lifecycle', 'test_scheduler_deferral_not_justification', None),
        ('succession', 'lifecycle', 'test_selector_binding_applies_gravity_priority', None),
        ('succession', 'lifecycle', 'test_starts_below_one_bpw', None),
        ('succession', 'lifecycle', 'test_synthetic_event_horizon_is_half', None),
        ('succession', 'lifecycle', 'test_tries_other_representation_before_ascending', None),
        ('succession', 'lifecycle', 'test_unsupported_treatment_never_selected', None),
        ('succession', 'lifecycle', 'test_whole_artifact_bpw_authoritative', None),
        ('succession', 'reseal', 'test_forge_program_materializes_sealed_and_launch_refused', None),
        ('succession', 'reseal', 'test_checkpoint_tamper_refused', None),
        ('succession', 'reseal', 'test_event_tamper_detected', None),
        ('succession', 'reseal', 'test_queue_row_tamper_detected_on_reload', None),
        ('succession', 'reseal', 'test_deliverables_seal', None),
        ('succession', 'reseal', 'test_escape_receipt_tamper_detected', None),
        ('succession', 'spec_repro', 'test_retirement_receipts_preserve_evidence_and_reopening', None),
        ('tg', 'fences_run', 'test_receipt_carries_all_false_fences', None),
        ('tg', 'fences_run', 'test_schedule_is_deterministic_closed_and_false_fenced', None),
        ('tg', 'lifecycle', 'test_adapter_refuses_other_instead_of_absorbing_gap', None),
        ('tg', 'lifecycle', 'test_bandwidth_provenance_is_closed', None),
        ('tg', 'lifecycle', 'test_categories_json_rejects_duplicate_keys_and_nonfinite_values', None),
        ('tg', 'lifecycle', 'test_category_schema_is_closed_and_byte_counts_are_exact_ints', None),
        ('tg', 'lifecycle', 'test_diagnostic_target_never_mints_a_milestone', None),
        ('tg', 'lifecycle', 'test_geometry_and_touch_identities_are_exact', None),
        ('tg', 'lifecycle', 'test_happy_reconciliation_feeds_only_planning_budget', None),
        ('tg', 'lifecycle', 'test_headroom_and_non_routed_bytes_tighten_routed_allowance', None),
        ('tg', 'lifecycle', 'test_invalid_physics_inputs_refuse', None),
        ('tg', 'lifecycle', 'test_kv_and_transfer_are_separate_margin_not_weight_active', None),
        ('tg', 'lifecycle', 'test_measured_sustained_bandwidth_is_stricter_than_peak_label', None),
        ('tg', 'lifecycle', 'test_peak_800_gbps_has_exact_tg2_tg1_absolute_ceilings', None),
        ('tg', 'lifecycle', 'test_public_reconciler_returns_one_typed_refusal_surface', None),
        ('tg', 'lifecycle', 'test_schedule_mutations_refuse', None),
        ('tg', 'lifecycle', 'test_tg2_byte_boundary_immediately_below_equal_above', None),
    ],
)
def test_retired_case(
    tmp_path: Path, family: str, kind: str, name: str, slot: str | None
) -> None:
    """Dispatch one retired-shell obligation.

    ``slot`` is identity-only for collision rows; shell dispatch uses family/kind/name.
    """
    _identity = slot if slot is not None else name
    del _identity  # identity for pytest/extractor only
    run(kind, tmp_path, family, name)
