/* Generated by hawking-adapters-codegen — do not hand-edit. */
/* Covers: adapters, artifacts, profiles, runtime capabilities, events, Fabric placement, tool effects. */

export type SupportLevel =
| "DECLARED"
| "SOURCE_HEADER_VALIDATED"
| "SYNTHETIC_PARITY"
| "REAL_TENSOR_DECODE"
| "SMALL_REAL_CHECKPOINT"
| "FULL_PARENT_VALIDATED"
| "PRODUCTION";

export type EvidenceKind =
| "description"
| "source_header"
| "synthetic_parity"
| "real_tensor_decode"
| "small_checkpoint_run"
| "full_parent_validation"
| "production_receipt";

export type FamilyId =
  | "deepseek"
  | "gemma"
  | "glm"
  | "kimi"
  | "llama"
  | "minimax"
  | "mistral_mixtral"
  | "phi"
  | "qwen"
  | "state_space";

export interface FamilyEvidence {
	path: string;
	claim: string;
	kind: EvidenceKind;
}

export interface AbiField<T = string> {
	value: T | null;
	null_reason: string | null;
}

export interface FamilyAdapterEntry {
	id: FamilyId;
	aliases: string[];
	displayName: string;
	level: SupportLevel;
	evidence: FamilyEvidence[];
	module: string;
	executes: boolean;
	serveRegistered: boolean;
	gaps: string[];
}

export const FAMILY_ADAPTERS: FamilyAdapterEntry[] = [
  {
    id: "deepseek",
    aliases: ["deepseek", "deepseek2", "deepseek_v2"],
    displayName: "DeepSeek V2",
    level: "SOURCE_HEADER_VALIDATED",
    evidence: [
      { path: "crates/hawking-core/src/model/deepseek_v2.rs", claim: "in-tree DeepSeekV2 engine", kind: "description" },
      { path: "crates/hawking-core/tests/cpu_backend_parity_deepseek.rs", claim: "CPU backend parity for deepseek path", kind: "small_checkpoint_run" },
      { path: "crates/hawking-core/src/model/mod.rs", claim: "load_engine dispatches deepseek2", kind: "description" },
      { path: "adapters/receipts/ADAPTER_DEEPSEEK_RECEIPT.json", claim: "Stage A: official config/tokenizer/safetensors header parsed and mapped", kind: "source_header" },
    ],
    module: "crates/hawking-core/src/model/deepseek_v2.rs",
    executes: true,
    serveRegistered: true,
    gaps: [
      "not FULL_PARENT_VALIDATED: no sealed full-size parent receipt in registry evidence",
      "not PRODUCTION",
      "DeepSeek V3/V4 MLA+DSA ladder rungs are NOT this family's shipping GGUF deepseek2 path",
    ],
  },
  {
    id: "gemma",
    aliases: ["gemma", "gemma2"],
    displayName: "Gemma 2",
    level: "DECLARED",
    evidence: [
      { path: "packs/hawking-adapters-extra.json", claim: "gemma2 extracted off-tree", kind: "description" },
      { path: "crates/hawking-core/tests/gemma2_smoke.rs", claim: "smoke test remains but load_engine rejects unknown gemma2 arch without pack", kind: "description" },
      { path: "crates/hawking-seed-c/src/providers/adapters.rs", claim: "seed-c ArchAdapter::gemma2 is declarative plan-only", kind: "description" },
    ],
    module: "packs/hawking-adapters-extra (gemma2)",
    executes: false,
    serveRegistered: false,
    gaps: [
      "module not in shipping load_engine",
      "pack hydrate required to execute",
      "not PRODUCTION",
    ],
  },
  {
    id: "glm",
    aliases: ["glm", "glm52", "glm_moe_dsa", "glm-5.2"],
    displayName: "GLM (gravity glm_moe_dsa)",
    level: "SMALL_REAL_CHECKPOINT",
    evidence: [
      { path: "evidence/glm52/GLM52_FLAGSHIP_ADAPTER_PARITY.json", claim: "M04_SEALED: Rust adapter vs oracle on real flagship .gravity shards", kind: "small_checkpoint_run" },
      { path: "crates/hawking-core/src/model/gravity_engine.rs", claim: "GravityEngine dispatches glm_moe_dsa", kind: "description" },
      { path: "crates/hawking-core/tests/gravity_engine_registry.rs", claim: "registry path for .gravity artifacts", kind: "description" },
      { path: "crates/hawking-core/tests/gravity_glm_forward.rs", claim: "unconditional: real .gravity container decoded, complete token executed, matches numpy oracle reading the same container (3 passed, 0.04s)", kind: "real_tensor_decode" },
    ],
    module: "crates/hawking-core/src/model/gravity_engine.rs",
    executes: true,
    serveRegistered: true,
    gaps: [
      "not PRODUCTION",
      "gravity_glm.rs is another lane's sealed path — not claimed as open production serve",
      "full parent source safetensors not the parity authority (gravity bytes are)",
    ],
  },
  {
    id: "kimi",
    aliases: ["kimi", "kimi_k2", "kimi_k26", "moonshot"],
    displayName: "Kimi K2.x",
    level: "SYNTHETIC_PARITY",
    evidence: [
      { path: "evidence/kimi-k26/KIMI_K26_ADAPTER_TWIN.json", claim: "synthetic CPU reference + bound real-source metal K1 twin", kind: "synthetic_parity" },
      { path: "crates/hawking-core/src/model/mod.rs", claim: "load_engine has no kimi arch arm (not serve-registered)", kind: "description" },
    ],
    module: "KIMI_K26_ADAPTER_TWIN.json (reference twin; no in-tree serve module)",
    executes: false,
    serveRegistered: false,
    gaps: [
      "not serve-registered in load_engine",
      "no SMALL_REAL_CHECKPOINT sealed receipt for full generate path",
      "not PRODUCTION",
    ],
  },
  {
    id: "llama",
    aliases: ["llama", "llama2", "llama3", "llama3.2"],
    displayName: "Llama (dense GGUF + gravity)",
    level: "SOURCE_HEADER_VALIDATED",
    evidence: [
      { path: "crates/hawking-core/src/model/llama.rs", claim: "in-tree LlamaDense engine module", kind: "description" },
      { path: "adapters/receipts/ADAPTER_LLAMA_RECEIPT.json", claim: "Stage A: official config/tokenizer/safetensors header parsed and mapped", kind: "source_header" },
      { path: "crates/hawking-core/tests/llama32_smoke.rs", claim: "small-parent greedy smoke when GGUF present (skips when absent — not live grade evidence)", kind: "small_checkpoint_run" },
      { path: "crates/hawking-core/tests/gravity_llama_forward.rs", claim: "gravity llama forward vs frozen oracle when off-tree .gravity present (skips when absent)", kind: "real_tensor_decode" },
      { path: "crates/hawking-core/src/model/mod.rs", claim: "load_engine dispatches llama|mistral GGUF arch strings", kind: "description" },
    ],
    module: "crates/hawking-core/src/model/llama.rs",
    executes: true,
    serveRegistered: true,
    gaps: [
      "no standing PRODUCTION parity receipt",
      "smoke and gravity_llama_forward skip when weights/artifacts are absent",
      "REAL_TENSOR_DECODE / SMALL_REAL_CHECKPOINT require committed fixtures or on-disk parents",
      "executes on CPU only: dispatches_per_forward=0 and device_id=null, so no Metal path is reached",
      "output is degenerate on both a raw prompt and a correct Llama-3 chat template, while llama.cpp reads the same GGUF at 338 tok/s against our 3.63",
    ],
  },
  {
    id: "minimax",
    aliases: ["minimax", "minimax_m3", "minimax-m3"],
    displayName: "MiniMax",
    level: "DECLARED",
    evidence: [
      { path: "evidence/fabric/FABRIC_BRIDGE_ARCHAEOLOGY.md", claim: "family listed in bridge archaeology; no serve path found", kind: "description" },
    ],
    module: "(none — declared only)",
    executes: false,
    serveRegistered: false,
    gaps: [
      "no in-tree engine module",
      "not serve-registered",
      "not PRODUCTION",
    ],
  },
  {
    id: "mistral_mixtral",
    aliases: ["mistral", "mixtral", "mistral_mixtral"],
    displayName: "Mistral / Mixtral",
    level: "SOURCE_HEADER_VALIDATED",
    evidence: [
      { path: "crates/hawking-core/src/model/mod.rs", claim: "dense mistral arch string routes to LlamaDense", kind: "description" },
      { path: "adapters/receipts/ADAPTER_MISTRAL_MIXTRAL_RECEIPT.json", claim: "Stage A: official config/tokenizer/safetensors header parsed and mapped", kind: "source_header" },
      { path: "crates/hawking-core/tests/llama32_smoke.rs", claim: "dense llama-family small checkpoint path (mistral shares LlamaDense; skips without GGUF)", kind: "small_checkpoint_run" },
      { path: "packs/hawking-adapters-extra.json", claim: "mixtral extracted off-tree to adapters-extra pack", kind: "description" },
      { path: "crates/hawking-seed-c/src/providers/adapters.rs", claim: "seed-c ArchAdapter::mixtral is declarative plan-only (does not execute)", kind: "description" },
    ],
    module: "crates/hawking-core/src/model/llama.rs (+ pack mixtral)",
    executes: true,
    serveRegistered: true,
    gaps: [
      "mixtral MoE not in shipping load_engine",
      "seed-c ArchAdapter does not execute",
      "no PRODUCTION receipt",
      "SMALL_REAL_CHECKPOINT smoke skips when no GGUF is on disk",
    ],
  },
  {
    id: "phi",
    aliases: ["phi", "phi3"],
    displayName: "Phi-3",
    level: "DECLARED",
    evidence: [
      { path: "packs/hawking-adapters-extra.json", claim: "phi3 extracted off-tree", kind: "description" },
      { path: "crates/hawking-core/tests/phi3_smoke.rs", claim: "smoke test remains; arch not in shipping load_engine", kind: "description" },
      { path: "crates/hawking-seed-c/src/providers/adapters.rs", claim: "seed-c ArchAdapter::phi3 is declarative plan-only", kind: "description" },
    ],
    module: "packs/hawking-adapters-extra (phi3)",
    executes: false,
    serveRegistered: false,
    gaps: [
      "module not in shipping load_engine",
      "pack hydrate required to execute",
      "not PRODUCTION",
    ],
  },
  {
    id: "qwen",
    aliases: ["qwen", "qwen2", "qwen2moe", "qwen-moe", "qwen3"],
    displayName: "Qwen (dense + MoE)",
    level: "SOURCE_HEADER_VALIDATED",
    evidence: [
      { path: "crates/hawking-core/src/model/qwen_dense.rs", claim: "in-tree QwenDense engine", kind: "description" },
      { path: "crates/hawking-core/src/model/qwen_moe.rs", claim: "in-tree QwenMoE engine", kind: "description" },
      { path: "adapters/receipts/ADAPTER_QWEN_RECEIPT.json", claim: "Stage A: official config/tokenizer/safetensors header parsed and mapped", kind: "source_header" },
      { path: "crates/hawking-core/tests/integration_greedy_64.rs", claim: "greedy integration path (skips when no model on disk — not live grade evidence)", kind: "full_parent_validation" },
      { path: "crates/hawking-core/tests/cpu_backend_parity.rs", claim: "CPU backend parity (skips when no qwen0.5b weights)", kind: "full_parent_validation" },
      { path: "crates/hawking-core/tests/qwen_tq_serve_parity.rs", claim: "TQ serve parity (#[ignore] + skips without weights/sidecar)", kind: "small_checkpoint_run" },
      { path: "crates/hawking-core/src/model/mod.rs", claim: "load_engine dispatches qwen2/qwen2moe", kind: "description" },
    ],
    module: "crates/hawking-core/src/model/qwen_dense.rs",
    executes: true,
    serveRegistered: true,
    gaps: [
      "not PRODUCTION: no standing production parity receipt under continuous serve",
      "large MoE parents (235B/397B) are campaign-side, not this registry's PRODUCTION claim",
      "integration/parity tests skip or are #[ignore] without on-disk parents",
    ],
  },
  {
    id: "state_space",
    aliases: ["state_space", "rwkv7", "rwkv", "mamba2", "mamba"],
    displayName: "State-space (RWKV7 + Mamba2)",
    level: "DECLARED",
    evidence: [
      { path: "crates/hawking-core/src/model/rwkv7.rs", claim: "in-tree RwkvSeven engine", kind: "description" },
      { path: "crates/hawking-core/tests/rwkv7_parity.rs", claim: "RWKV7 parity + load_engine routing", kind: "small_checkpoint_run" },
      { path: "packs/hawking-adapters-extra.json", claim: "mamba2 extracted off-tree", kind: "description" },
    ],
    module: "crates/hawking-core/src/model/rwkv7.rs",
    executes: true,
    serveRegistered: true,
    gaps: [
      "mamba2 not in shipping load_engine",
      "not PRODUCTION",
      "family spans RWKV (executes) and Mamba2 (declared pack only)",
    ],
  },
];

export type ArtifactCodec = string;

export interface ArtifactRef {
	codec: ArtifactCodec;
	path: string;
	familyId: FamilyId;
	shardIndex?: number | null;
	digest?: string | null;
	serveRegistered?: boolean;
}

export type RuntimeProfile = "default" | "fast" | "race" | "efficient" | "exact";

export interface KernelProfile {
	schema_version: 1;
	profile_id: string;
	profile_name: string;
	model_id?: string;
	model_arch: string;
	device_name?: string;
	shader_hash?: string;
	selected: Record<string, unknown>;
	evidence?: Record<string, unknown>;
}

export const RUNTIME_PROFILES: RuntimeProfile[] = ["default", "fast", "race", "efficient", "exact"];

export type BridgeEndpointStatus = "live" | "partial" | "not_implemented";

export interface BridgeEndpoint {
	endpoint: string;
	status: BridgeEndpointStatus;
	entry_path: string;
	tests: string[];
}

export interface RuntimeCapabilities {
	schema: "hawking.runtime_capabilities.v1";
	families: FamilyAdapterEntry[];
	runtimeProfiles: RuntimeProfile[];
	bridgeEndpoints: BridgeEndpoint[];
}

export type ContentVerification = "target_verified" | "provisional";

export type ProducingSurface =
| "you" | "chat" | "ide" | "bridge" | "terminal"
| "mcp" | "sdk" | "serve" | "system";

export type EventCategory =
  | "model_lifecycle"
  | "text"
  | "reasoning"
  | "plans"
  | "tools"
  | "permissions"
  | "edits"
  | "tests"
  | "verification"
  | "agents"
  | "acceleration"
  | "fabric_placement"
  | "fabric_node_state"
  | "warnings"
  | "errors"
  | "usage"
  | "you_objects"
  | "you_memory"
  | "you_connectors"
  | "you_research"
  | "you_automation"
  | "you_swarm"
  | "you_projects"
  | "you_handoff";

export interface CanonicalEventEnvelope {
	id: string;
	seq: number;
	session_id: string;
	surface: ProducingSurface;
	subsystem: string;
	verification: ContentVerification;
	category: EventCategory;
	kind: string;
	payload: Record<string, unknown>;
}

export type YouEventName =
  | "ObjectAdded"
  | "ObjectProcessed"
  | "MemoryProposed"
  | "MemoryCommitted"
  | "MemoryCorrected"
  | "ConnectorRead"
  | "ConnectorWriteProposed"
  | "ResearchStarted"
  | "SourceCaptured"
  | "ClaimVerified"
  | "AutomationCreated"
  | "AutomationRan"
  | "SwarmCreated"
  | "AgentDelegated"
  | "AgentResult"
  | "ProjectUpdated"
  | "HandoffCreated";

export type YouEventKind =
  | "you.object.added"
  | "you.object.processed"
  | "you.memory.proposed"
  | "you.memory.committed"
  | "you.memory.corrected"
  | "you.connector.read"
  | "you.connector.write_proposed"
  | "you.research.started"
  | "you.research.source_captured"
  | "you.research.claim_verified"
  | "you.automation.created"
  | "you.automation.ran"
  | "you.swarm.created"
  | "you.agent.delegated"
  | "you.agent.result"
  | "you.project.updated"
  | "you.handoff.created";

export const YOU_EVENTS: { event: YouEventName; kind: YouEventKind; category: EventCategory; defaultVerification: ContentVerification }[] = [
  { event: "ObjectAdded", kind: "you.object.added", category: "you_objects", defaultVerification: "target_verified" },
  { event: "ObjectProcessed", kind: "you.object.processed", category: "you_objects", defaultVerification: "target_verified" },
  { event: "MemoryProposed", kind: "you.memory.proposed", category: "you_memory", defaultVerification: "provisional" },
  { event: "MemoryCommitted", kind: "you.memory.committed", category: "you_memory", defaultVerification: "target_verified" },
  { event: "MemoryCorrected", kind: "you.memory.corrected", category: "you_memory", defaultVerification: "target_verified" },
  { event: "ConnectorRead", kind: "you.connector.read", category: "you_connectors", defaultVerification: "target_verified" },
  { event: "ConnectorWriteProposed", kind: "you.connector.write_proposed", category: "you_connectors", defaultVerification: "provisional" },
  { event: "ResearchStarted", kind: "you.research.started", category: "you_research", defaultVerification: "provisional" },
  { event: "SourceCaptured", kind: "you.research.source_captured", category: "you_research", defaultVerification: "target_verified" },
  { event: "ClaimVerified", kind: "you.research.claim_verified", category: "you_research", defaultVerification: "target_verified" },
  { event: "AutomationCreated", kind: "you.automation.created", category: "you_automation", defaultVerification: "target_verified" },
  { event: "AutomationRan", kind: "you.automation.ran", category: "you_automation", defaultVerification: "target_verified" },
  { event: "SwarmCreated", kind: "you.swarm.created", category: "you_swarm", defaultVerification: "target_verified" },
  { event: "AgentDelegated", kind: "you.agent.delegated", category: "you_swarm", defaultVerification: "provisional" },
  { event: "AgentResult", kind: "you.agent.result", category: "you_swarm", defaultVerification: "provisional" },
  { event: "ProjectUpdated", kind: "you.project.updated", category: "you_projects", defaultVerification: "target_verified" },
  { event: "HandoffCreated", kind: "you.handoff.created", category: "you_handoff", defaultVerification: "target_verified" },
];

export type FabricPlacementKind = "local_serve_eligible" | "not_serve_registered" | "declared_only";

export interface FabricPlacement {
	family: FamilyId;
	placement: FabricPlacementKind;
	serveRegistered: boolean;
	fabricPartition: string | null;
	fabricPartitionNullReason: string | null;
	eventKind: "fabric.placement";
}

export const FABRIC_PLACEMENTS: FabricPlacement[] = [
  { family: "deepseek", placement: "local_serve_eligible", serveRegistered: true, fabricPartition: null, fabricPartitionNullReason: "no Fabric partition declaration for deepseek2", eventKind: "fabric.placement" },
  { family: "gemma", placement: "declared_only", serveRegistered: false, fabricPartition: null, fabricPartitionNullReason: "not serve-registered", eventKind: "fabric.placement" },
  { family: "glm", placement: "local_serve_eligible", serveRegistered: true, fabricPartition: "gravity shard boundaries are the partition unit; Fabric multi-node placement not declared", fabricPartitionNullReason: null, eventKind: "fabric.placement" },
  { family: "kimi", placement: "declared_only", serveRegistered: false, fabricPartition: null, fabricPartitionNullReason: "not serve-registered; no Fabric placement", eventKind: "fabric.placement" },
  { family: "llama", placement: "local_serve_eligible", serveRegistered: true, fabricPartition: null, fabricPartitionNullReason: "Fabric partition placement not declared for llama; serve is single-process today", eventKind: "fabric.placement" },
  { family: "minimax", placement: "declared_only", serveRegistered: false, fabricPartition: null, fabricPartitionNullReason: "not serve-registered", eventKind: "fabric.placement" },
  { family: "mistral_mixtral", placement: "local_serve_eligible", serveRegistered: true, fabricPartition: null, fabricPartitionNullReason: "no Fabric partition declaration for mistral/mixtral", eventKind: "fabric.placement" },
  { family: "phi", placement: "declared_only", serveRegistered: false, fabricPartition: null, fabricPartitionNullReason: "not serve-registered", eventKind: "fabric.placement" },
  { family: "qwen", placement: "local_serve_eligible", serveRegistered: true, fabricPartition: null, fabricPartitionNullReason: "no Fabric multi-node partition declaration for qwen family", eventKind: "fabric.placement" },
  { family: "state_space", placement: "local_serve_eligible", serveRegistered: true, fabricPartition: null, fabricPartitionNullReason: "no Fabric partition for state-space family", eventKind: "fabric.placement" },
];

export type EffectKind = "read" | "write" | "delete" | "execute" | "network" | "model" | "plugin" | "unknown";
export type RiskLevel = "trivial" | "low" | "medium" | "high" | "critical";

export interface ToolEffect {
	kind: EffectKind;
	target: string;
	bytes_hash?: string | null;
	risk: RiskLevel;
	metadata?: Record<string, string>;
}

export interface ToolEffectSet {
	effects: ToolEffect[];
}
