// Generated by hide-sdk from hide-protocol. DO NOT EDIT BY HAND.
// Bible sec 15.7: one schema source generates the frontend types.
// Regenerate with `cargo run -p hide-sdk --bin hide-sdk-codegen`.
// A drift from the Rust wire types is caught by the golden-file test.
// Protocol version: hide.agent.v1
// Root types: Session, Thread, Turn, Item, Method, Notification, InitializeRequest, InitializeResult, Plan, Agent

/**
 * An agent: a worker in the agent tree (Bible sec 14). The root agent has no parent; sub-agents record their parent and the host records their children, so the tree is walkable from either end.
 */
export interface Agent {
  budget?: Budget;
  children?: string[];
  context_scope: ContextScope;
  effects?: Effect[];
  id: string;
  model_policy: ModelPolicy;
  parent?: string | null;
  return_policy: ReturnPolicy;
  role: string;
}

export interface AgentMessage {
  text: string;
}

export interface AgentResult {
  agent: string;
  outcome: CompletionStatus;
  summary?: string | null;
}

export interface AgentSpawn {
  agent: string;
  objective: string;
  role: string;
}

export type ApprovalDecision = "approved" | "denied" | "deferred";

/**
 * A request for the user to approve an effectful action before it runs.
 */
export interface ApprovalRequest {
  action: string;
  detail?: string | null;
  effects?: Effect[];
  request_id: string;
  risk: Risk;
}

export interface ApprovalResult {
  decision: ApprovalDecision;
  reason?: string | null;
  request_id: string;
}

/**
 * A produced artifact: a file, patch, report, or other output. `produced_by` links back to the plan step (Bible sec 14) that generated it.
 */
export interface Artifact {
  created_ms: number;
  digest?: string | null;
  id: string;
  kind: ArtifactKind;
  name: string;
  path?: string | null;
  produced_by?: string | null;
  size_bytes?: number | null;
}

/**
 * The kind of artifact a step or turn produces.
 */
export type ArtifactKind = "file" | "patch" | "report" | "binary" | "log" | "other";

/**
 * An attachment carried on a user message. Mirrors `hide_core::types::BlobRef` so the compat bridge maps between them losslessly.
 */
export interface Attachment {
  hash: string;
  id: string;
  media_type?: string | null;
  size_bytes: number;
}

/**
 * The turn cannot proceed and needs the user. Distinct from an error: a blocker is a solvable stall, not a failure.
 */
export interface Blocker {
  code: string;
  message: string;
  needs?: string | null;
}

/**
 * The resource budget an agent may spend.
 */
export interface Budget {
  tokens?: number | null;
  tool_calls?: number | null;
  usd_micros?: number | null;
  wall_ms?: number | null;
}

/**
 * A checkpoint: a named, restorable boundary in a thread. It may bind a state capsule (the runtime bytes) and/or a VCS ref (the source-tree position).
 */
export interface Checkpoint {
  at_turn?: string | null;
  capsule?: StateCapsuleRef | null;
  created_ms: number;
  id: string;
  label?: string | null;
  session?: string | null;
  thread?: string | null;
  vcs_ref?: string | null;
}

/**
 * What the client can do. The server ANDs these with its own to reach the effective capability set.
 */
export interface ClientCapabilities {
  approvals?: boolean;
  experimental?: Record<string, unknown>;
  fs?: boolean;
  streaming?: boolean;
  subscriptions?: boolean;
  terminal?: boolean;
}

/**
 * The turn finished. Carries the terminal status and an optional summary.
 */
export interface Completion {
  status: CompletionStatus;
  summary?: string | null;
}

/**
 * Terminal outcome of a turn, agent, or completion item.
 */
export type CompletionStatus = "success" | "partial" | "failed" | "cancelled";

/**
 * A context receipt: the honest ledger of what was pulled into context for a turn (Bible: bounded recall is the moat, so the receipt is first-class).
 */
export interface ContextReceipt {
  note?: string | null;
  sources?: ContextSource[];
  total_token_estimate?: number | null;
}

/**
 * What a sub-agent is allowed to see of its parent's context.
 */
export interface ContextScope {
  exclude?: string[];
  include?: string[];
  inherit_parent?: boolean;
}

/**
 * One source folded into the model's context, with the tokens it cost.
 */
export interface ContextSource {
  name: string;
  token_estimate?: number | null;
  trust?: string | null;
  uri?: string | null;
}

/**
 * An estimated cost. Every field is optional so a planner can declare only what it can estimate. These are estimates, not measurements -- the honest framing this crate holds to.
 */
export interface Cost {
  tokens?: number | null;
  usd_micros?: number | null;
  wall_ms?: number | null;
}

/**
 * A per-file diff with reviewable status.
 */
export interface Diff {
  diff_id: string;
  hunks?: DiffHunk[];
  path: string;
  status: DiffStatus;
}

export interface DiffHunk {
  new_lines: number;
  new_start: number;
  old_lines: number;
  old_start: number;
  text: string;
}

export type DiffStatus = "proposed" | "applied" | "rejected" | "reverted";

/**
 * A declared side effect. A step or agent lists the effects it may cause so a scope check can gate it before execution. Kept protocol-local (rather than reusing another crate's effect enum) so this schema authority is self-contained.
 */
export type Effect = "read_fs" | "write_fs" | "network" | "process" | "shell" | "vcs" | "environment" | "approval" | "agent_spawn" | "state" | "other";

export interface ErrorItem {
  code: string;
  message: string;
}

/**
 * The client's opening message (sec 15.3): who it is, which protocol versions it speaks (highest preference first), and what it can do.
 */
export interface InitializeRequest {
  capabilities: ClientCapabilities;
  client: PeerInfo;
  protocolVersions: string[];
}

/**
 * The server's reply: who it is, the ONE negotiated protocol version, and its capabilities.
 */
export interface InitializeResult {
  capabilities: ServerCapabilities;
  protocolVersion: string;
  server: PeerInfo;
}

/**
 * An interrupt of the running turn (sec 15 `turn/interrupt`).
 */
export interface Interrupt {
  reason?: string | null;
}

/**
 * An item: one event in a turn, ordered by `seq`. The `kind` payload is flattened so an item is a single flat object on the wire.
 */
export type Item = { kind: "user_message"; payload: UserMessage; } | { kind: "agent_message"; payload: AgentMessage; } | { kind: "reasoning_summary"; payload: ReasoningSummary; } | { kind: "plan"; payload: Plan; } | { kind: "plan_mutation"; payload: PlanMutation; } | { kind: "context_receipt"; payload: ContextReceipt; } | { kind: "tool_call"; payload: ToolCall; } | { kind: "tool_result"; payload: ToolResult; } | { kind: "shell_stream"; payload: ShellStream; } | { kind: "patch"; payload: Patch; } | { kind: "diff"; payload: Diff; } | { kind: "approval_request"; payload: ApprovalRequest; } | { kind: "approval_result"; payload: ApprovalResult; } | { kind: "verification_request"; payload: VerificationRequest; } | { kind: "verification_receipt"; payload: VerificationReceipt; } | { kind: "artifact"; payload: Artifact; } | { kind: "checkpoint"; payload: Checkpoint; } | { kind: "state_capsule"; payload: StateCapsuleRef; } | { kind: "agent_spawn"; payload: AgentSpawn; } | { kind: "agent_result"; payload: AgentResult; } | { kind: "steer"; payload: Steer; } | { kind: "interrupt"; payload: Interrupt; } | { kind: "error"; payload: ErrorItem; } | { kind: "completion"; payload: Completion; } | { kind: "blocker"; payload: Blocker; };

/**
 * A streaming delta applied to an already-added item (for token-by-token agent messages and live shell output).
 */
export interface ItemDelta {
  append_text?: string | null;
  shell_chunk?: string | null;
}

/**
 * The closed set of request methods (Bible sec 15), grouped by namespace. Serializes as its slash-namespaced string.
 */
export type Method = "workspace/create" | "workspace/open" | "workspace/close" | "workspace/get" | "workspace/list" | "environment/create" | "environment/get" | "environment/list" | "environment/dispose" | "session/new" | "session/get" | "session/list" | "session/close" | "thread/new" | "thread/get" | "thread/list" | "thread/fork" | "thread/fork_ephemeral" | "thread/merge_summary" | "goal/set" | "goal/get" | "goal/list" | "turn/create" | "turn/get" | "turn/steer" | "turn/interrupt" | "turn/pause" | "turn/resume" | "item/get" | "item/list" | "item/subscribe" | "agent/spawn" | "agent/get" | "agent/list" | "agent/result" | "checkpoint/create" | "checkpoint/list" | "checkpoint/restore" | "state/save" | "state/load" | "state/fork" | "state/release" | "state/inspect" | "approval/request" | "approval/respond" | "artifact/get" | "artifact/list" | "artifact/put";

/**
 * The model policy an agent runs under.
 * 
 * DEFERRED_MODEL_REQUIRED: this only names a policy; binding a policy to an actual model and honoring `allow_fallback` at inference time is the job of a model-bearing runtime and is not implemented or claimed here.
 */
export interface ModelPolicy {
  allow_fallback?: boolean;
  /**
   * A named policy (for example `"default"`, `"cheap"`, `"frontier"`).
   */
  policy: string;
  tier?: string | null;
}

/**
 * Server-to-client notifications (Bible sec 15.5). Adjacently tagged with a slash-namespaced `method`, matching the request namespaces so a client routes both by the same key.
 */
export type Notification = { method: "session/updated"; params: { session: string; status: SessionStatus; }; } | { method: "thread/updated"; params: { thread: string; }; } | { method: "turn/started"; params: { turn: string; }; } | { method: "turn/updated"; params: { status: TurnStatus; turn: string; }; } | { method: "turn/completed"; params: { status: CompletionStatus; turn: string; }; } | { method: "item/added"; params: { item: Item; }; } | { method: "item/updated"; params: { item: Item; }; } | { method: "item/delta"; params: { delta: ItemDelta; item: string; }; } | { method: "plan/updated"; params: { plan: Plan; }; } | { method: "tool/progress"; params: { call_id: string; message: string; }; } | { method: "approval/requested"; params: { request: ApprovalRequest; }; } | { method: "checkpoint/created"; params: { checkpoint: string; }; } | { method: "agent/spawned"; params: { agent: string; }; } | { method: "agent/updated"; params: { agent: string; status: TurnStatus; }; } | { method: "state/saved"; params: { capsule: string; }; } | { method: "runtime/status"; params: { detail?: string | null; status: string; }; } | { method: "error"; params: { code: string; message: string; }; } | { method: "custom"; params: { name: string; payload: unknown; }; };

/**
 * A proposed multi-file patch, carried as a unified diff.
 */
export interface Patch {
  files?: string[];
  patch_id: string;
  summary?: string | null;
  unified_diff: string;
}

/**
 * Identifies the peer at either end of the handshake.
 */
export interface PeerInfo {
  name: string;
  version: string;
}

/**
 * A plan: a DAG of steps that reaches a goal.
 */
export interface Plan {
  created_ms: number;
  goal?: string | null;
  id: string;
  steps: PlanStep[];
}

export interface PlanMutation {
  detail?: string | null;
  kind: PlanMutationKind;
  plan: string;
  step?: string | null;
}

/**
 * What changed about a plan.
 */
export type PlanMutationKind = "add_step" | "remove_step" | "update_step" | "reorder" | "replace";

/**
 * One node in the plan DAG. Its edges are `dependencies`; a valid plan is acyclic and every dependency resolves to another step in the same plan (checked by [`Plan::validate_dag`]).
 */
export interface PlanStep {
  acceptance_oracle?: string | null;
  cost?: Cost;
  dependencies?: string[];
  effects?: Effect[];
  expected_artifacts?: string[];
  id: string;
  objective: string;
  parallelizable?: boolean;
  rollback_boundary?: RollbackBoundary;
  scope: Scope;
}

export interface ReasoningSummary {
  text: string;
}

/**
 * How a sub-agent's results return to its parent.
 */
export type ReturnPolicy = "summary" | "full_transcript" | "artifacts" | "state_capsule";

/**
 * Risk banding on an action that may need approval. Mirrors the concept in `hide_core::types::RiskLevel` but is defined locally so the schema authority stays self-contained.
 */
export type Risk = "trivial" | "low" | "medium" | "high" | "critical";

/**
 * The rollback boundary a step commits to before mutating anything.
 */
export interface RollbackBoundary {
  kind: RollbackKind;
  /**
   * A reference to the boundary marker (checkpoint id, capsule id, stash ref), when the kind implies one.
   */
  reference?: string | null;
}

/**
 * How far a step's effects can be unwound if it is rejected or fails.
 */
export type RollbackKind = "none" | "checkpoint" | "state_capsule" | "git_stash";

/**
 * The blast radius a step is allowed to touch. `paths` are the files or globs it may read/write; `network` says whether it may reach out.
 */
export interface Scope {
  description?: string | null;
  network?: boolean;
  paths?: string[];
}

/**
 * What the server offers.
 */
export interface ServerCapabilities {
  agents?: boolean;
  checkpoints?: boolean;
  experimental?: Record<string, unknown>;
  methods?: Method[];
  remote?: boolean;
  state?: boolean;
  streaming?: boolean;
  subscriptions?: boolean;
}

/**
 * A session: one working context over a workspace. Threads (including forks) hang off it; the session references them by id so a session stays a light header while threads carry the turn history.
 */
export interface Session {
  created_ms: number;
  environment?: string | null;
  id: string;
  repository?: string | null;
  status: SessionStatus;
  threads?: string[];
  title?: string | null;
  workspace: string;
}

/**
 * Lifecycle state of a session.
 */
export type SessionStatus = "active" | "idle" | "closed";

export type ShellChannel = "stdout" | "stderr";

/**
 * A chunk of a running command's output stream.
 */
export interface ShellStream {
  call_id?: string | null;
  channel: ShellChannel;
  chunk: string;
}

/**
 * A pointer to a state capsule held by `hide-state`. This is only a reference: it names the capsule and pins its digest and identity binding so a reader can locate and verify the bytes.
 * 
 * DEFERRED_MODEL_REQUIRED: the live production of capsule bytes from a running engine, and their rebind into a runtime, is not implemented here and cannot be claimed. `hide-state` defines the byte schema; a model-bearing runtime fills it. This struct only carries the address and the integrity pins.
 */
export interface StateCapsuleRef {
  /**
   * The capsule id as known to the `hide-state` store.
   */
  capsule_id: string;
  created_ms: number;
  /**
   * Integrity digest of the capsule payload (verified by `hide-state`).
   */
  digest: string;
  id: string;
  model_id?: string | null;
  size_bytes?: number | null;
}

/**
 * A mid-turn steering directive from the user (sec 15 `turn/steer`).
 */
export interface Steer {
  directive: string;
}

/**
 * A thread: an ordered line of turns within a session. Forking a thread (sec 15 `thread/fork`, `thread/fork_ephemeral`) records the parent and the turn it branched from, so lineage is always recoverable. An ephemeral fork is a scratch branch whose only durable return is a merge summary (`thread/merge_summary`).
 */
export interface Thread {
  created_ms: number;
  ephemeral?: boolean;
  forked_at_turn?: string | null;
  id: string;
  parent?: string | null;
  session: string;
  title?: string | null;
  turns: Turn[];
}

export interface ToolCall {
  arguments: unknown;
  call_id: string;
  tool: string;
}

export interface ToolResult {
  call_id: string;
  error?: string | null;
  ok: boolean;
  output: unknown;
}

/**
 * A turn: one authored contribution to a thread, carrying an ordered list of items. `parent_turn` records causal provenance (the "why" spine).
 */
export interface Turn {
  created_ms: number;
  id: string;
  items: Item[];
  parent_turn?: string | null;
  role: TurnRole;
  status: TurnStatus;
  thread: string;
}

/**
 * Who authored a turn.
 */
export type TurnRole = "user" | "agent" | "system" | "tool";

/**
 * Lifecycle state of a turn. `steer`/`interrupt`/`pause`/`resume` (sec 15) move a turn between these.
 */
export type TurnStatus = "pending" | "running" | "paused" | "completed" | "interrupted" | "failed";

export interface UserMessage {
  attachments?: Attachment[];
  text: string;
}

export type VerificationOutcome = "pass" | "fail" | "inconclusive";

/**
 * The receipt returned when an oracle finishes grading.
 */
export interface VerificationReceipt {
  detail?: string | null;
  oracle: string;
  outcome: VerificationOutcome;
  request_id: string;
}

/**
 * A request to grade a target against an oracle.
 */
export interface VerificationRequest {
  oracle: string;
  request_id: string;
  target?: string | null;
}

