#!/usr/bin/env python3.12
"""Publish the light-only campaign's status from live evidence.

Restart-safe: everything here is re-derived from disk, so a new session reads the same
picture without inheriting a previous agent's beliefs.

    python3.12 tools/campaign/light_status.py
"""
from __future__ import annotations

import json
import subprocess
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MD = ROOT / "HAWKING_LIGHT_ONLY_STATUS.md"
JS = ROOT / "HAWKING_LIGHT_ONLY_STATUS.json"
NEXT = ROOT / "HAWKING_LIGHT_ONLY_NEXT_COMMAND.sh"

SUITES = [
    ("odyssey T0", ["python3.12", "tools/odyssey/test_odyssey_t0.py"]),
    ("odyssey apparatus", ["python3.12", "tools/odyssey/test_odyssey_apparatus.py"]),
    ("odyssey data", ["python3.12", "-m", "tools.odyssey.test_odyssey_data"]),
    ("ramanujan governance", ["python3.12", "-m", "ramanujan.test_ramanujan"]),
    ("ramanujan search", ["python3.12", "-m", "ramanujan.test_search"]),
    ("ramanujan cognition", ["python3.12", "-m", "ramanujan.test_cognition"]),
]


def run(cmd: list[str]) -> tuple[bool, str]:
    r = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
    tail = (r.stderr or r.stdout).strip().splitlines()
    return r.returncode == 0, (tail[-1] if tail else "")


def main() -> int:
    gov = json.loads(subprocess.run(
        ["python3.12", "tools/campaign/light_governor.py", "--json"],
        capture_output=True, text=True, cwd=ROOT).stdout)

    reg = json.loads((ROOT / "HAWKING_ADAPTER_REGISTRY.json").read_text())
    fams = reg["families"]
    fams = fams if isinstance(fams, list) else list(fams.values())
    grades = {str(f.get("family", f.get("id"))): f.get("level") for f in fams}

    suites = {}
    for name, cmd in SUITES:
        ok, last = run(cmd)
        suites[name] = {"pass": ok, "last_line": last}

    fence = (ROOT / "odyssey/launch/ODYSSEY_LAUNCH_AUTHORIZED").read_text().strip()
    cap = subprocess.run(["python3.12", "tools/odyssey/substrate_capability.py", "--check"],
                         capture_output=True, text=True, cwd=ROOT).returncode

    doc = {
        "schema": "hawking.light_only.status.v1",
        "at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "endpoint": "HAWKING_LIGHT_ONLY_FOUNDATION_COMPLETE",
        "resource_mode": gov["mode"],
        "machine": gov["sample"],
        "fences": {
            "ODYSSEY_LAUNCH_AUTHORIZED": fence,
            "substrate_capability_gate": "REFUSING" if cap == 1 else "NOT REFUSING -- INVESTIGATE",
            "RAMANUJAN_RESEARCH_AUTHORIZED": False,
        },
        "adapter_grades": grades,
        "production_families": [k for k, v in grades.items() if v == "PRODUCTION"],
        "test_suites": suites,
        "all_suites_green": all(s["pass"] for s in suites.values()),
    }
    JS.write_text(json.dumps(doc, indent=2) + "\n")

    g = "\n".join(f"- `{k}` **{v}**" for k, v in sorted(grades.items()))
    s = "\n".join(f"- {k}: {'green' if v['pass'] else 'FAILED'}" for k, v in suites.items())
    MD.write_text(
        "# HAWKING LIGHT-ONLY STATUS\n\n"
        "Generated by `tools/campaign/light_status.py`. Do not hand-edit.\n\n"
        f"    at:            {doc['at']}\n"
        f"    resource mode: {doc['resource_mode']}\n"
        f"    load/core:     {gov['sample']['load_per_core']}  "
        f"(foreign ~{gov['sample']['foreign_cpu_cores']} cores)\n"
        f"    endpoint:      HAWKING_LIGHT_ONLY_FOUNDATION_COMPLETE\n\n"
        "## Fences\n\n"
        f"- ODYSSEY_LAUNCH_AUTHORIZED = **{fence}**\n"
        f"- substrate capability gate = **{doc['fences']['substrate_capability_gate']}**\n"
        "- RAMANUJAN_RESEARCH_AUTHORIZED = **false**\n\n"
        f"## Adapter grades (0 PRODUCTION)\n\n{g}\n\n"
        f"## Test suites\n\n{s}\n\n"
        "## Next\n\n"
        "    bash HAWKING_LIGHT_ONLY_NEXT_COMMAND.sh\n"
    )
    NEXT.write_text(
        "#!/usr/bin/env bash\n"
        "# Re-derive the campaign's state. Safe to run at any time; changes nothing.\n"
        "set -euo pipefail\n"
        "cd \"$(dirname \"$0\")\"\n"
        "python3.12 tools/campaign/light_governor.py --watch 3\n"
        "python3.12 tools/campaign/light_status.py\n"
        "echo\n"
        "echo 'If the governor says HEAVY_WINDOW_AVAILABLE, the next action is H1 in'\n"
        "echo 'HAWKING_NEXT_HEAVY_TOURNAMENT.json -- representation arms on a real SMALL parent.'\n"
        "echo 'It is never started automatically. A human decides.'\n"
    )
    NEXT.chmod(0o755)
    print(f"{doc['resource_mode']}; suites green={doc['all_suites_green']}; "
          f"PRODUCTION families={len(doc['production_families'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
