// Generated by hide-sdk from the hide-protocol command registry. DO NOT EDIT BY HAND.
// The ONE command table: hide-protocol owns CommandSpec + command_catalog().
// Regenerate with `cargo run -p hide-protocol --bin hide-sdk-codegen`.
// A drift from the Rust catalog is caught by the golden-file test.

/**
 * The approval gate a command passes through before it takes effect.
 */
export type ApprovalPolicy = "auto" | "ask" | "require_sandbox" | "deny";

/**
 * How a surface reaches the backend for this command.
 *
 * - [`BackendBinding::Intent`] names a real `hide-core` `Intent` variant (`crates/hide-core/src/api.rs`) for the HCLI backend bridge. - [`BackendBinding::Custom`] names an `Intent::Custom{name}` the HCLI host handles and exposes through [`WIRE_CUSTOM_NAMES`]. There is no pending tier: a name the host does not handle is not on the contract at all. - [`BackendBinding::Rpc`] names an elevated capability: either a real [`Method`](crate::protocol::Method) string or a census-confirmed host capability in [`HOST_CAPABILITIES`]. - [`BackendBinding::LocalOnly`] is a client-local action with no backend call.
 */
export type BackendBinding = { kind: "intent"; target: string; } | { kind: "custom"; target: string; } | { kind: "rpc"; target: string; } | { kind: "local_only"; };

/**
 * The domain a command belongs to. The coverage test asserts the priority domains are all present, so this doubles as the campaign's progress ledger.
 */
export type Category = "turn" | "diff" | "timeline" | "verify" | "side_chat" | "checkpoint" | "memory" | "goal" | "steer" | "workspace" | "environment" | "search" | "file" | "terminal" | "plan" | "background" | "handoff" | "surface";

/**
 * One command in the ONE registry: a capability mapped to the control(s) it appears under, with everything a surface needs to render, gate, invoke, and undo it.
 */
export interface CommandSpec {
  approval_policy: ApprovalPolicy;
  /**
   * Every surface that offers the command.
   */
  available_surfaces: Surface[];
  backend_binding: BackendBinding;
  category: Category;
  /**
   * Whether the command palette lists it.
   */
  command_palette: boolean;
  /**
   * Whether a context menu offers it.
   */
  context_menu: boolean;
  /**
   * One-line description of what the command does.
   */
  description: string;
  /**
   * The effect classes the command may cause.
   */
  effects: Effect[];
  /**
   * Stable unique id (the capability name), the key every surface resolves on.
   */
  id: string;
  /**
   * A keyboard shortcut (`Mod` is Cmd on macOS, Ctrl elsewhere), if bound.
   */
  keyboard_shortcut?: string | null;
  /**
   * The surface this command lives on first.
   */
  primary_surface: Surface;
  /**
   * The receipt kind the command emits, if it seals one.
   */
  receipt_kind?: string | null;
  /**
   * Negotiated server capabilities the command requires (see [`ServerCapabilities`](crate::protocol::ServerCapabilities)).
   */
  required_capabilities: string[];
  /**
   * The selection kind the command needs before it can run.
   */
  required_selection: RequiredSelection;
  /**
   * A telemetry event name, if the command is instrumented.
   */
  telemetry?: string | null;
  /**
   * Human title for menus and the palette.
   */
  title: string;
  /**
   * A toolbar button id it binds to, if any.
   */
  toolbar_binding?: string | null;
  undo_strategy: UndoStrategy;
}

/**
 * A declared side effect. A step or agent lists the effects it may cause so a scope check can gate it before execution. Kept protocol-local (rather than reusing another crate's effect enum) so this schema authority is self-contained.
 */
export type Effect = "read_fs" | "write_fs" | "network" | "process" | "shell" | "vcs" | "environment" | "approval" | "agent_spawn" | "state" | "other";

/**
 * Whether the command needs a live selection before it can run.
 */
export type RequiredSelection = "none" | "text" | "file" | "hunk" | "plan_step" | "any";

/**
 * A UI surface a command can appear on. The closed set of places the shipped shell renders controls (Bible surfaces, plus the palette as the universal fallback surface).
 */
export type Surface = "chat" | "ide" | "home" | "context_stack" | "status_bar" | "state_timeline" | "terminal" | "diff_review" | "settings" | "fleet" | "palette" | "editor" | "you";

/**
 * How a command's effect is unwound.
 */
export type UndoStrategy = "none" | "inverse" | "checkpoint" | "reject";

// Runtime values: import command_catalog.json (generated sibling).
export declare const COMMAND_CATALOG: CommandSpec[];
